# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_rules/codegen/generate.py
# Source: 9.1 Derivative integration rules.m, 9.1 Integrand simplification rules.m
# Module: 9.1 Derivative integration rules
#
# This file contains Rubi integration rules as RubiRulePattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Integer, Integral, Lambda, Rational, Symbol, Tuple as SympyTuple, Eq, Ne, Lt, Gt, Le, Ge, log, sqrt, pi, I, oo
from rubi_rules.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (sin, cos, tan, sec, csc, cot, asin, acos, atan, atan2, asec, acsc, acot,
                   sinh, cosh, tanh, sech, csch, coth, asinh, acosh, atanh, asech, acsch, acoth,
                   exp, Abs, diff, denom, frac, floor, root, simplify,
                   elliptic_e, elliptic_f, hyper, appellf1)

from sympy_matching.wild import WildSymbol, WildHeadApp, WildHeadDeriv, IDENTITY_ELEMENT
from rubi_rules.base_objects import Int, RubiRulePattern
from rubi_rules.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, OddQ, EvenQ, NumberQ, NumericQ, AtomQ, MemberQ,
    PositiveQ, NegativeQ, PolynomialQ, TrueQ, FalseQ, MatchQ, PrimeQ, UnsameQ,
    # RUBI-specific constraints
    EqQ, NeQ, IGtQ, ILtQ, IGeQ, ILeQ, GtQ, LtQ, GeQ, LeQ, PosQ, NegQ,
    IntegersQ, HalfIntegerQ, FractionQ, RationalQ, ComplexNumberQ, RealNumberQ,
    FractionOrNegativeQ, SqrtNumberQ, PowerQ, ProductQ, SumQ, NonsumQ,
    IntegerPowerQ, FractionalPowerQ, PolyQ, LinearQ, QuadraticQ, BinomialQ,
    TrinomialQ, LinearMatchQ, QuadraticMatchQ, BinomialMatchQ, TrinomialMatchQ,
    TrigQ, HyperbolicQ, InverseTrigQ, InverseHyperbolicQ, LogQ, ComplexFreeQ,
    InverseFunctionFreeQ, FractionalPowerFreeQ, TrigHyperbolicFreeQ, IntegralFreeQ,
    RationalFunctionQ, AlgebraicFunctionQ, IndependentQ, SimplerQ, SumSimplerQ,
    FunctionOfQ, PiecewiseLinearQ, ExpressionEqQ,
    IntLinearQ, IntBinomialQ, IntQuadraticQ,
    MonomialQ, LinearPairQ,
    GeneralizedBinomialQ, GeneralizedBinomialMatchQ,
    GeneralizedTrinomialQ, GeneralizedTrinomialMatchQ,
    NiceSqrtQ, SimplerSqrtQ, FractionalPowerFactorQ,
    SumBaseQ, InverseFunctionQ, InertTrigQ, InertTrigFreeQ,
    CalculusFreeQ, QuotientOfLinearsQ,
    PowerOfLinearQ, PowerOfLinearMatchQ,
    FunctionOfExponentialQ,
    KnownSineIntegrandQ, KnownSecantIntegrandQ,
    KnownTangentIntegrandQ, KnownCotangentIntegrandQ,
    EulerIntegrandQ, SubstForFractionalPowerQ,
    PerfectSquareQ, PolynomialInQ, FunctionOfTrigOfLinearQ,
    SimplerIntegrandQ, PseudoBinomialPairQ, QuadraticProductQ,
    EveryQ, TrigSimplifyQ, EqM, TryPureTanSubst,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

_A_ = WildSymbol('A', optional_value=IDENTITY_ELEMENT)
A_ = WildSymbol('A')
_B_ = WildSymbol('B', optional_value=IDENTITY_ELEMENT)
B_ = WildSymbol('B')
_C_ = WildSymbol('C', optional_value=IDENTITY_ELEMENT)
C_ = WildSymbol('C')
F_ = WildSymbol('F')
Px_ = WildSymbol('Px')
_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
f_ = WildSymbol('f')
g_ = WildSymbol('g')
_j_ = WildSymbol('j', optional_value=IDENTITY_ELEMENT)
j_ = WildSymbol('j')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
m1_ = WildSymbol('m1')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')
n1_ = WildSymbol('n1')
_n2_ = WildSymbol('n2', optional_value=IDENTITY_ELEMENT)
n2_ = WildSymbol('n2')
_p_ = WildSymbol('p', optional_value=IDENTITY_ELEMENT)
p_ = WildSymbol('p')
_q_ = WildSymbol('q', optional_value=IDENTITY_ELEMENT)
q_ = WildSymbol('q')
_u_ = WildSymbol('u', optional_value=IDENTITY_ELEMENT)
u_ = WildSymbol('u')
v_ = WildSymbol('v')
_w_ = WildSymbol('w', optional_value=IDENTITY_ELEMENT)
w_ = WildSymbol('w')

RULES = [
    # Rule 1
    RubiRulePattern(
        pattern=Int(WildHeadDeriv(f_, x, n_), x),
        constraints=(FreeQ([f_, n_], x),),
        replacement=WFDeriv(f_, x, n_ - 1),
        module_name='9.1 Derivative integration rules',
        rule_number=1,
    ),
    # Rule 2
    RubiRulePattern(
        pattern=Int((F_**(x*_b_ + _a_)*_c_)**_p_*WildHeadDeriv(f_, x, n_), x),
        constraints=(FreeQ([_a_, _b_, _c_, f_, F_, _p_], x), IGtQ(n_, 0),),
        replacement=(F_**(x*_b_ + _a_)*_c_)**_p_*WFDeriv(f_, x, n_ - 1) - Star(_b_*_p_*log(F_), Int((F_**(x*_b_ + _a_)*_c_)**_p_*WFDeriv(f_, x, n_ - 1), x)),
        module_name='9.1 Derivative integration rules',
        rule_number=2,
    ),
    # Rule 3
    RubiRulePattern(
        pattern=Int((F_**(x*_b_ + _a_)*_c_)**_p_*WildHeadDeriv(f_, x, n_), x),
        constraints=(FreeQ([_a_, _b_, _c_, f_, F_, _p_], x), ILtQ(n_, 0),),
        replacement=-Star(1/(_b_*_p_*log(F_)), Int((F_**(x*_b_ + _a_)*_c_)**_p_*WFDeriv(f_, x, n_ + 1), x)) + (F_**(x*_b_ + _a_)*_c_)**_p_*WFDeriv(f_, x, n_)/(_b_*_p_*log(F_)),
        module_name='9.1 Derivative integration rules',
        rule_number=3,
    ),
    # Rule 4
    RubiRulePattern(
        pattern=Int(sin(x*_b_ + _a_)*WildHeadDeriv(f_, x, n_), x),
        constraints=(FreeQ([_a_, _b_, f_], x), IGtQ(n_, 0),),
        replacement=-Star(_b_, Int(WFDeriv(f_, x, n_ - 1)*cos(x*_b_ + _a_), x)) + WFDeriv(f_, x, n_ - 1)*sin(x*_b_ + _a_),
        module_name='9.1 Derivative integration rules',
        rule_number=4,
    ),
    # Rule 5
    RubiRulePattern(
        pattern=Int(cos(x*_b_ + _a_)*WildHeadDeriv(f_, x, n_), x),
        constraints=(FreeQ([_a_, _b_, f_], x), IGtQ(n_, 0),),
        replacement=Star(_b_, Int(WFDeriv(f_, x, n_ - 1)*sin(x*_b_ + _a_), x)) + WFDeriv(f_, x, n_ - 1)*cos(x*_b_ + _a_),
        module_name='9.1 Derivative integration rules',
        rule_number=5,
    ),
    # Rule 6
    RubiRulePattern(
        pattern=Int(sin(x*_b_ + _a_)*WildHeadDeriv(f_, x, n_), x),
        constraints=(FreeQ([_a_, _b_, f_], x), ILtQ(n_, 0),),
        replacement=Star(1/_b_, Int(WFDeriv(f_, x, n_ + 1)*cos(x*_b_ + _a_), x)) - WFDeriv(f_, x, n_)*cos(x*_b_ + _a_)/_b_,
        module_name='9.1 Derivative integration rules',
        rule_number=6,
    ),
    # Rule 7
    RubiRulePattern(
        pattern=Int(cos(x*_b_ + _a_)*WildHeadDeriv(f_, x, n_), x),
        constraints=(FreeQ([_a_, _b_, f_], x), ILtQ(n_, 0),),
        replacement=-Star(1/_b_, Int(WFDeriv(f_, x, n_ + 1)*sin(x*_b_ + _a_), x)) + WFDeriv(f_, x, n_)*sin(x*_b_ + _a_)/_b_,
        module_name='9.1 Derivative integration rules',
        rule_number=7,
    ),
    # Rule 8
    RubiRulePattern(
        pattern=Int(u_*WildHeadDeriv(f_, x, n_), x),
        constraints=(FreeQ([f_, n_], x), FunctionOfQ(WFDeriv(f_, x, n_ - 1), u_, x),),
        replacement=Subst(Int(SimplifyIntegrand(SubstFor(WFDeriv(f_, x, n_ - 1), u_, x), x), x), x, WFDeriv(f_, x, n_ - 1)),
        module_name='9.1 Derivative integration rules',
        rule_number=8,
    ),
    # Rule 9
    RubiRulePattern(
        pattern=Int(u_*(_a_*WildHeadApp(f_, x)*WildHeadDeriv(g_, x, 1) + _a_*WildHeadDeriv(f_, x, 1)*WildHeadApp(g_, x)), x),
        constraints=(FreeQ([_a_, f_, g_], x), FunctionOfQ(WFApply(f_, x)*WFApply(g_, x), u_, x),),
        replacement=Star(_a_, Subst(Int(SimplifyIntegrand(SubstFor(WFApply(f_, x)*WFApply(g_, x), u_, x), x), x), x, WFApply(f_, x)*WFApply(g_, x))),
        module_name='9.1 Derivative integration rules',
        rule_number=9,
    ),
    # Rule 10
    RubiRulePattern(
        pattern=Int(u_*(_a_*WildHeadDeriv(f_, x, m_)*WildHeadApp(g_, x) + _a_*WildHeadDeriv(f_, x, m1_)*WildHeadDeriv(g_, x, 1)), x),
        constraints=(FreeQ([_a_, f_, g_, m_], x), EqQ(m1_, m_ - 1), FunctionOfQ(WFApply(g_, x)*WFDeriv(f_, x, m_ - 1), u_, x),),
        replacement=Star(_a_, Subst(Int(SimplifyIntegrand(SubstFor(WFApply(g_, x)*WFDeriv(f_, x, m_ - 1), u_, x), x), x), x, WFApply(g_, x)*WFDeriv(f_, x, m_ - 1))),
        module_name='9.1 Derivative integration rules',
        rule_number=10,
    ),
    # Rule 11
    RubiRulePattern(
        pattern=Int(u_*(_a_*WildHeadDeriv(f_, x, m_)*WildHeadDeriv(g_, x, n1_) + _a_*WildHeadDeriv(f_, x, m1_)*WildHeadDeriv(g_, x, n_)), x),
        constraints=(FreeQ([_a_, f_, g_, m_, n_], x), EqQ(m1_, m_ - 1), EqQ(n1_, n_ - 1), FunctionOfQ(WFDeriv(f_, x, m_ - 1)*WFDeriv(g_, x, n_ - 1), u_, x),),
        replacement=Star(_a_, Subst(Int(SimplifyIntegrand(SubstFor(WFDeriv(f_, x, m_ - 1)*WFDeriv(g_, x, n_ - 1), u_, x), x), x), x, WFDeriv(f_, x, m_ - 1)*WFDeriv(g_, x, n_ - 1))),
        module_name='9.1 Derivative integration rules',
        rule_number=11,
    ),
    # Rule 12
    RubiRulePattern(
        pattern=Int(u_*WildHeadApp(f_, x)**_p_*(_a_*WildHeadDeriv(f_, x, 1)*WildHeadApp(g_, x) + _b_*WildHeadApp(f_, x)*WildHeadDeriv(g_, x, 1)), x),
        constraints=(FreeQ([_a_, _b_, f_, g_, _p_], x), EqQ(_a_, _b_*(_p_ + 1)), FunctionOfQ(WFApply(f_, x)**(_p_ + 1)*WFApply(g_, x), u_, x),),
        replacement=Star(_b_, Subst(Int(SimplifyIntegrand(SubstFor(WFApply(f_, x)**(_p_ + 1)*WFApply(g_, x), u_, x), x), x), x, WFApply(f_, x)**(_p_ + 1)*WFApply(g_, x))),
        module_name='9.1 Derivative integration rules',
        rule_number=12,
    ),
    # Rule 13
    RubiRulePattern(
        pattern=Int(u_*WildHeadDeriv(f_, x, m1_)**_p_*(_a_*WildHeadDeriv(f_, x, m_)*WildHeadApp(g_, x) + _b_*WildHeadDeriv(f_, x, m1_)*WildHeadDeriv(g_, x, 1)), x),
        constraints=(FreeQ([_a_, _b_, f_, g_, m_, _p_], x), EqQ(m1_, m_ - 1), EqQ(_a_, _b_*(_p_ + 1)), FunctionOfQ(WFApply(g_, x)*WFDeriv(f_, x, m_ - 1)**(_p_ + 1), u_, x),),
        replacement=Star(_b_, Subst(Int(SimplifyIntegrand(SubstFor(WFApply(g_, x)*WFDeriv(f_, x, m_ - 1)**(_p_ + 1), u_, x), x), x), x, WFApply(g_, x)*WFDeriv(f_, x, m_ - 1)**(_p_ + 1))),
        module_name='9.1 Derivative integration rules',
        rule_number=13,
    ),
    # Rule 14
    RubiRulePattern(
        pattern=Int(u_*WildHeadApp(g_, x)**_q_*(_a_*WildHeadDeriv(f_, x, m_)*WildHeadApp(g_, x) + _b_*WildHeadDeriv(f_, x, m1_)*WildHeadDeriv(g_, x, 1)), x),
        constraints=(FreeQ([_a_, _b_, f_, g_, m_, _q_], x), EqQ(m1_, m_ - 1), EqQ(_a_*(_q_ + 1), _b_), FunctionOfQ(WFApply(g_, x)**(_q_ + 1)*WFDeriv(f_, x, m_ - 1), u_, x),),
        replacement=Star(_a_, Subst(Int(SimplifyIntegrand(SubstFor(WFApply(g_, x)**(_q_ + 1)*WFDeriv(f_, x, m_ - 1), u_, x), x), x), x, WFApply(g_, x)**(_q_ + 1)*WFDeriv(f_, x, m_ - 1))),
        module_name='9.1 Derivative integration rules',
        rule_number=14,
    ),
    # Rule 15
    RubiRulePattern(
        pattern=Int(u_*WildHeadDeriv(f_, x, m1_)**_p_*(_a_*WildHeadDeriv(f_, x, m_)*WildHeadDeriv(g_, x, n1_) + _b_*WildHeadDeriv(f_, x, m1_)*WildHeadDeriv(g_, x, n_)), x),
        constraints=(FreeQ([_a_, _b_, f_, g_, m_, n_, _p_], x), EqQ(m1_, m_ - 1), EqQ(n1_, n_ - 1), EqQ(_a_, _b_*(_p_ + 1)), FunctionOfQ(WFDeriv(f_, x, m_ - 1)**(_p_ + 1)*WFDeriv(g_, x, n_ - 1), u_, x),),
        replacement=Star(_b_, Subst(Int(SimplifyIntegrand(SubstFor(WFDeriv(f_, x, m_ - 1)**(_p_ + 1)*WFDeriv(g_, x, n_ - 1), u_, x), x), x), x, WFDeriv(f_, x, m_ - 1)**(_p_ + 1)*WFDeriv(g_, x, n_ - 1))),
        module_name='9.1 Derivative integration rules',
        rule_number=15,
    ),
    # Rule 16
    RubiRulePattern(
        pattern=Int(u_*WildHeadApp(f_, x)**_p_*WildHeadApp(g_, x)**_q_*(_a_*WildHeadDeriv(f_, x, 1)*WildHeadApp(g_, x) + _b_*WildHeadApp(f_, x)*WildHeadDeriv(g_, x, 1)), x),
        constraints=(FreeQ([_a_, _b_, f_, g_, _p_, _q_], x), EqQ(_a_*(_q_ + 1), _b_*(_p_ + 1)), FunctionOfQ(WFApply(f_, x)**(_p_ + 1)*WFApply(g_, x)**(_q_ + 1), u_, x),),
        replacement=Star(_a_/(_p_ + 1), Subst(Int(SimplifyIntegrand(SubstFor(WFApply(f_, x)**(_p_ + 1)*WFApply(g_, x)**(_q_ + 1), u_, x), x), x), x, WFApply(f_, x)**(_p_ + 1)*WFApply(g_, x)**(_q_ + 1))),
        module_name='9.1 Derivative integration rules',
        rule_number=16,
    ),
    # Rule 17
    RubiRulePattern(
        pattern=Int(u_*WildHeadDeriv(f_, x, m1_)**_p_*WildHeadApp(g_, x)**_q_*(_a_*WildHeadDeriv(f_, x, m_)*WildHeadApp(g_, x) + _b_*WildHeadDeriv(f_, x, m1_)*WildHeadDeriv(g_, x, 1)), x),
        constraints=(FreeQ([_a_, _b_, f_, g_, m_, _p_, _q_], x), EqQ(m1_, m_ - 1), EqQ(_a_*(_q_ + 1), _b_*(_p_ + 1)), FunctionOfQ(WFApply(g_, x)**(_q_ + 1)*WFDeriv(f_, x, m_ - 1)**(_p_ + 1), u_, x),),
        replacement=Star(_a_/(_p_ + 1), Subst(Int(SimplifyIntegrand(SubstFor(WFApply(g_, x)**(_q_ + 1)*WFDeriv(f_, x, m_ - 1)**(_p_ + 1), u_, x), x), x), x, WFApply(g_, x)**(_q_ + 1)*WFDeriv(f_, x, m_ - 1)**(_p_ + 1))),
        module_name='9.1 Derivative integration rules',
        rule_number=17,
    ),
    # Rule 18
    RubiRulePattern(
        pattern=Int(u_*WildHeadDeriv(f_, x, m1_)**_p_*WildHeadDeriv(g_, x, n1_)**_q_*(_a_*WildHeadDeriv(f_, x, m_)*WildHeadDeriv(g_, x, n1_) + _b_*WildHeadDeriv(f_, x, m1_)*WildHeadDeriv(g_, x, n_)), x),
        constraints=(FreeQ([_a_, _b_, f_, g_, m_, n_, _p_, _q_], x), EqQ(m1_, m_ - 1), EqQ(n1_, n_ - 1), EqQ(_a_*(_q_ + 1), _b_*(_p_ + 1)), FunctionOfQ(WFDeriv(f_, x, m_ - 1)**(_p_ + 1)*WFDeriv(g_, x, n_ - 1)**(_q_ + 1), u_, x),),
        replacement=Star(_a_/(_p_ + 1), Subst(Int(SimplifyIntegrand(SubstFor(WFDeriv(f_, x, m_ - 1)**(_p_ + 1)*WFDeriv(g_, x, n_ - 1)**(_q_ + 1), u_, x), x), x), x, WFDeriv(f_, x, m_ - 1)**(_p_ + 1)*WFDeriv(g_, x, n_ - 1)**(_q_ + 1))),
        module_name='9.1 Derivative integration rules',
        rule_number=18,
    ),
    # Rule 19
    RubiRulePattern(
        pattern=Int(WildHeadApp(f_, x)*WildHeadDeriv(g_, x, 1) + WildHeadDeriv(f_, x, 1)*WildHeadApp(g_, x), x),
        constraints=(FreeQ([f_, g_], x),),
        replacement=WFApply(f_, x)*WFApply(g_, x),
        module_name='9.1 Derivative integration rules',
        rule_number=19,
    ),
    # Rule 20
    RubiRulePattern(
        pattern=Int((-WildHeadApp(f_, x)*WildHeadDeriv(g_, x, 1) + WildHeadDeriv(f_, x, 1)*WildHeadApp(g_, x))*WildHeadApp(g_, x)**(-2), x),
        constraints=(FreeQ([f_, g_], x),),
        replacement=WFApply(f_, x)/WFApply(g_, x),
        module_name='9.1 Derivative integration rules',
        rule_number=20,
    ),
    # Rule 21
    RubiRulePattern(
        pattern=Int((-WildHeadApp(f_, x)*WildHeadDeriv(g_, x, 1) + WildHeadDeriv(f_, x, 1)*WildHeadApp(g_, x))*(WildHeadApp(f_, x)*WildHeadApp(g_, x))**(-1), x),
        constraints=(FreeQ([f_, g_], x),),
        replacement=log(WFApply(f_, x)/WFApply(g_, x)),
        module_name='9.1 Derivative integration rules',
        rule_number=21,
    ),
    # Rule 22
    RubiRulePattern(
        pattern=Int(_u_*(x**_n_*_b_ + a_)**_p_, x),
        constraints=(FreeQ([a_, _b_, _n_, _p_], x), EqQ(a_, 0),),
        replacement=Int(_u_*(x**_n_*_b_)**_p_, x),
        module_name='9.1 Derivative integration rules',
        rule_number=22,
    ),
    # Rule 23
    RubiRulePattern(
        pattern=Int(_u_*(x**_n_*_b_ + _a_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _n_, _p_], x), EqQ(_b_, 0),),
        replacement=Int(_a_**_p_*_u_, x),
        module_name='9.1 Derivative integration rules',
        rule_number=23,
    ),
    # Rule 24
    RubiRulePattern(
        pattern=Int(_u_*(x**_j_*_c_ + x**_n_*_b_ + a_)**_p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _n_, _p_], x), EqQ(_j_, 2*_n_), EqQ(a_, 0),),
        replacement=Int(_u_*(x**(2*_n_)*_c_ + x**_n_*_b_)**_p_, x),
        module_name='9.1 Derivative integration rules',
        rule_number=24,
    ),
    # Rule 25
    RubiRulePattern(
        pattern=Int(_u_*(x**_j_*_c_ + x**_n_*_b_ + _a_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _n_, _p_], x), EqQ(_j_, 2*_n_), EqQ(_b_, 0),),
        replacement=Int(_u_*(x**(2*_n_)*_c_ + _a_)**_p_, x),
        module_name='9.1 Derivative integration rules',
        rule_number=25,
    ),
    # Rule 26
    RubiRulePattern(
        pattern=Int(_u_*(x**_j_*_c_ + x**_n_*_b_ + _a_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _n_, _p_], x), EqQ(_j_, 2*_n_), EqQ(_c_, 0),),
        replacement=Int(_u_*(x**_n_*_b_ + _a_)**_p_, x),
        module_name='9.1 Derivative integration rules',
        rule_number=26,
    ),
    # Rule 27
    RubiRulePattern(
        pattern=Int(_u_*(_a_*v_ + _b_*v_ + _w_)**_p_, x),
        constraints=(FreeQ([_a_, _b_], x), Not(FreeQ(v_, x)),),
        replacement=Int(_u_*(v_*(_a_ + _b_) + _w_)**_p_, x),
        module_name='9.1 Derivative integration rules',
        rule_number=27,
    ),
    # Rule 28
    RubiRulePattern(
        pattern=Int(Px_**p_*_u_, x),
        constraints=(PolyQ(Px_, x), Not(RationalQ(p_)), FreeQ(p_, x), RationalQ(Simplify(p_)),),
        replacement=Int(Px_**Simplify(p_)*_u_, x),
        module_name='9.1 Derivative integration rules',
        rule_number=28,
    ),
    # Rule 29
    RubiRulePattern(
        pattern=Int(a_, x),
        constraints=(FreeQ(a_, x),),
        replacement=x*a_,
        module_name='9.1 Derivative integration rules',
        rule_number=29,
    ),
    # Rule 30
    RubiRulePattern(
        pattern=Int(a_*(x*_c_ + b_), x),
        constraints=(FreeQ([a_, b_, _c_], x),),
        replacement=a_*(x*_c_ + b_)**2/(2*_c_),
        module_name='9.1 Derivative integration rules',
        rule_number=30,
    ),
    # Rule 31
    RubiRulePattern(
        pattern=Int(-u_, x),
        constraints=(),
        replacement=(sympy.Function('Identity')(Integer(-1)) * Int(u_, x)),
        module_name='9.1 Derivative integration rules',
        rule_number=31,
    ),
    # Rule 32
    RubiRulePattern(
        pattern=Int((sympy.Function('Complex')(Integer(0), a_) * u_), x),
        constraints=(FreeQ(a_, x), EqQ(a_**2, 1),),
        replacement=(Complex(sympy.Function('Identity')(Integer(0)), a_) * Int(u_, x)),
        module_name='9.1 Derivative integration rules',
        rule_number=32,
    ),
    # Rule 33
    RubiRulePattern(
        pattern=Int(a_*u_, x),
        constraints=(FreeQ(a_, x), Not(MatchQ(u_, Condition(b_*v_, FreeQ(b_, x)))),),
        replacement=a_*Int(u_, x),
        module_name='9.1 Derivative integration rules',
        rule_number=33,
    ),
    # Rule 34
    RubiRulePattern(
        pattern=Int(u_*(x*_c_)**_m_, x),
        constraints=(FreeQ([_c_, _m_], x), SumQ(u_), Not(LinearQ(u_, x)), Not(MatchQ(u_, Condition((a_ + (_b_ * v_)), And(FreeQ([a_, _b_], x), InverseFunctionQ(v_))))),),
        replacement=Int(ExpandIntegrand(u_*(x*_c_)**_m_, x), x),
        module_name='9.1 Derivative integration rules',
        rule_number=34,
    ),
    # Rule 35
    RubiRulePattern(
        pattern=Int(_u_*(x**n_*_a_)**m_, x),
        constraints=(FreeQ([_a_, m_, n_], x), Not(IntegerQ(m_)),),
        replacement=_a_**IntPart(m_)*(x**n_*_a_)**FracPart(m_)*Int(x**(m_*n_)*_u_, x)/x**(n_*FracPart(m_)),
        module_name='9.1 Derivative integration rules',
        rule_number=35,
    ),
    # Rule 36
    RubiRulePattern(
        pattern=Int(_u_*v_**_m_*(b_*v_)**n_, x),
        constraints=(FreeQ([b_, n_], x), IntegerQ(_m_),),
        replacement=Int(_u_*(b_*v_)**(_m_ + n_), x)/b_**_m_,
        module_name='9.1 Derivative integration rules',
        rule_number=36,
    ),
    # Rule 37
    RubiRulePattern(
        pattern=Int(_u_*(_a_*v_)**m_*(_b_*v_)**n_, x),
        constraints=(FreeQ([_a_, _b_, m_], x), Not(IntegerQ(m_)), IGtQ(n_ + sympy.S.Half, 0), IntegerQ(m_ + n_),),
        replacement=_a_**(m_ + sympy.S.Half)*_b_**(n_ + sympy.S(-1)/2)*sqrt(_b_*v_)*Int(_u_*v_**(m_ + n_), x)/sqrt(_a_*v_),
        module_name='9.1 Derivative integration rules',
        rule_number=37,
    ),
    # Rule 38
    RubiRulePattern(
        pattern=Int(_u_*(_a_*v_)**m_*(_b_*v_)**n_, x),
        constraints=(FreeQ([_a_, _b_, m_], x), Not(IntegerQ(m_)), ILtQ(n_ + sympy.S(-1)/2, 0), IntegerQ(m_ + n_),),
        replacement=_a_**(m_ + sympy.S(-1)/2)*_b_**(n_ + sympy.S.Half)*sqrt(_a_*v_)*Int(_u_*v_**(m_ + n_), x)/sqrt(_b_*v_),
        module_name='9.1 Derivative integration rules',
        rule_number=38,
    ),
    # Rule 39
    RubiRulePattern(
        pattern=Int(_u_*(_a_*v_)**m_*(_b_*v_)**n_, x),
        constraints=(FreeQ([_a_, _b_, m_, n_], x), Not(IntegerQ(m_)), Not(IntegerQ(n_)), IntegerQ(m_ + n_),),
        replacement=_a_**(m_ + n_)*(_b_*v_)**n_*Int(_u_*v_**(m_ + n_), x)/(_a_*v_)**n_,
        module_name='9.1 Derivative integration rules',
        rule_number=39,
    ),
    # Rule 40
    RubiRulePattern(
        pattern=Int(_u_*(_a_*v_)**m_*(_b_*v_)**n_, x),
        constraints=(FreeQ([_a_, _b_, m_, n_], x), Not(IntegerQ(m_)), Not(IntegerQ(n_)), Not(IntegerQ(m_ + n_)),),
        replacement=_b_**IntPart(n_)*(_b_*v_)**FracPart(n_)*Int(_u_*(_a_*v_)**(m_ + n_), x)/(_a_**IntPart(n_)*(_a_*v_)**FracPart(n_)),
        module_name='9.1 Derivative integration rules',
        rule_number=40,
    ),
    # Rule 41
    RubiRulePattern(
        pattern=Int(_u_*(a_ + _b_*v_)**_m_*(c_ + _d_*v_)**_n_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _n_], x), EqQ(-a_*_d_ + _b_*c_, 0), IntegerQ(_m_), Or(Not(IntegerQ(_n_)), SimplerQ(x*_d_ + c_, x*_b_ + a_)),),
        replacement=(_b_/_d_)**_m_*Int(_u_*(c_ + _d_*v_)**(_m_ + _n_), x),
        module_name='9.1 Derivative integration rules',
        rule_number=41,
    ),
    # Rule 42
    RubiRulePattern(
        pattern=Int(_u_*(a_ + _b_*v_)**m_*(c_ + _d_*v_)**n_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, m_, n_], x), EqQ(-a_*_d_ + _b_*c_, 0), GtQ(_b_/_d_, 0), Not(Or(IntegerQ(m_), IntegerQ(n_))),),
        replacement=(_b_/_d_)**m_*Int(_u_*(c_ + _d_*v_)**(m_ + n_), x),
        module_name='9.1 Derivative integration rules',
        rule_number=42,
    ),
    # Rule 43
    RubiRulePattern(
        pattern=Int(_u_*(a_ + _b_*v_)**m_*(c_ + _d_*v_)**n_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, m_, n_], x), EqQ(-a_*_d_ + _b_*c_, 0), Not(Or(IntegerQ(m_), IntegerQ(n_), GtQ(_b_/_d_, 0))),),
        replacement=(a_ + _b_*v_)**m_*Int(_u_*(c_ + _d_*v_)**(m_ + n_), x)/(c_ + _d_*v_)**m_,
        module_name='9.1 Derivative integration rules',
        rule_number=43,
    ),
    # Rule 44
    RubiRulePattern(
        pattern=Int(_u_*(a_ + _b_*v_)**m_*(_A_ + _B_*v_ + _C_*v_**2), x),
        constraints=(FreeQ([a_, _b_, _A_, _B_, _C_], x), EqQ(_A_*_b_**2 - _B_*a_*_b_ + _C_*a_**2, 0), LeQ(m_, -1),),
        replacement=Int(_u_*(a_ + _b_*v_)**(m_ + 1)*Simp(_B_*_b_ - _C_*a_ + _C_*_b_*v_, x), x)/_b_**2,
        module_name='9.1 Derivative integration rules',
        rule_number=44,
    ),
    # Rule 45
    RubiRulePattern(
        pattern=Int(_u_*(x**_n_*_b_ + a_)**_m_*(x**_q_*_d_ + c_)**_p_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _m_, _n_], x), EqQ(_q_, -_n_), IntegerQ(_p_), EqQ(a_*c_ - _b_*_d_, 0), Not(And(IntegerQ(_m_), NegQ(_n_))),),
        replacement=(_d_/a_)**_p_*Int(_u_*(x**_n_*_b_ + a_)**(_m_ + _p_)/x**(_n_*_p_), x),
        module_name='9.1 Derivative integration rules',
        rule_number=45,
    ),
    # Rule 46
    RubiRulePattern(
        pattern=Int(_u_*(x**j_*_d_ + c_)**_p_*(x**_n_*_b_ + a_)**_m_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _m_, _n_, _p_], x), EqQ(j_, 2*_n_), EqQ(_p_, -_m_), EqQ(a_**2*_d_ + _b_**2*c_, 0), GtQ(a_, 0), LtQ(_d_, 0),),
        replacement=(-_b_**2/_d_)**_m_*Int(_u_/(-x**_n_*_b_ + a_)**_m_, x),
        module_name='9.1 Derivative integration rules',
        rule_number=46,
    ),
    # Rule 47
    RubiRulePattern(
        pattern=Int(_u_*(x**2*_c_ + x*_b_ + a_)**_p_, x),
        constraints=(FreeQ([a_, _b_, _c_], x), EqQ(-4*a_*_c_ + _b_**2, 0), IntegerQ(_p_),),
        replacement=Int(_u_*(2*x*_c_ + _b_)**(2*_p_)/(2**(2*_p_)*_c_**_p_), x),
        module_name='9.1 Derivative integration rules',
        rule_number=47,
    ),
    # Rule 48
    RubiRulePattern(
        pattern=Int(_u_*(x**n_*_b_ + x**_n2_*_c_ + a_)**_p_, x),
        constraints=(FreeQ([a_, _b_, _c_, n_], x), EqQ(_n2_, 2*n_), EqQ(-4*a_*_c_ + _b_**2, 0), IntegerQ(_p_),),
        replacement=Int(_u_*(x**n_*_c_ + _b_/2)**(2*_p_), x)/_c_**_p_,
        module_name='9.1 Derivative integration rules',
        rule_number=48,
    ),

]

# Summary: 48 rules translated, 0 skipped
