# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_rules/codegen/generate.py
# Source: 4.7.5 Inert trig functions.m
# Module: 4.7.5 Inert trig functions
#
# This file contains Rubi integration rules as RubiRulePattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Integer, Integral, Lambda, Rational, Symbol, Tuple as SympyTuple, Eq, Ne, Lt, Gt, Le, Ge, log, sqrt, pi, I, oo
from rubi_rules.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (sin, cos, tan, sec, csc, cot, asin, acos, atan, atan2, asec, acsc, acot,
                   sinh, cosh, tanh, sech, csch, coth, asinh, acosh, atanh, asech, acsch, acoth,
                   exp, Abs, diff, denom, frac, floor, root, simplify,
                   elliptic_e, elliptic_f, hyper, appellf1)

from sympy_objects.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_rules.base_objects import Int, RubiRulePattern
from rubi_rules.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, OddQ, EvenQ, NumberQ, NumericQ, AtomQ, MemberQ,
    PositiveQ, NegativeQ, PolynomialQ, TrueQ, FalseQ, MatchQ, PrimeQ, UnsameQ,
    # RUBI-specific constraints
    EqQ, NeQ, IGtQ, ILtQ, IGeQ, ILeQ, GtQ, LtQ, GeQ, LeQ, PosQ, NegQ,
    IntegersQ, HalfIntegerQ, FractionQ, RationalQ, ComplexNumberQ, RealNumberQ,
    FractionOrNegativeQ, SqrtNumberQ, PowerQ, ProductQ, SumQ, NonsumQ,
    IntegerPowerQ, FractionalPowerQ, PolyQ, LinearQ, QuadraticQ, BinomialQ,
    TrinomialQ, LinearMatchQ, QuadraticMatchQ, BinomialMatchQ, TrinomialMatchQ,
    TrigQ, HyperbolicQ, InverseTrigQ, InverseHyperbolicQ, LogQ, ComplexFreeQ,
    InverseFunctionFreeQ, FractionalPowerFreeQ, TrigHyperbolicFreeQ, IntegralFreeQ,
    RationalFunctionQ, AlgebraicFunctionQ, IndependentQ, SimplerQ, SumSimplerQ,
    FunctionOfQ, PiecewiseLinearQ, ExpressionEqQ,
    IntLinearQ, IntBinomialQ, IntQuadraticQ,
    MonomialQ, LinearPairQ,
    GeneralizedBinomialQ, GeneralizedBinomialMatchQ,
    GeneralizedTrinomialQ, GeneralizedTrinomialMatchQ,
    NiceSqrtQ, SimplerSqrtQ, FractionalPowerFactorQ,
    SumBaseQ, InverseFunctionQ, InertTrigQ, InertTrigFreeQ,
    CalculusFreeQ, QuotientOfLinearsQ,
    PowerOfLinearQ, PowerOfLinearMatchQ,
    FunctionOfExponentialQ,
    KnownSineIntegrandQ, KnownSecantIntegrandQ,
    KnownTangentIntegrandQ, KnownCotangentIntegrandQ,
    EulerIntegrandQ, SubstForFractionalPowerQ,
    PerfectSquareQ, PolynomialInQ, FunctionOfTrigOfLinearQ,
    SimplerIntegrandQ, PseudoBinomialPairQ, QuadraticProductQ,
    EveryQ, TrigSimplifyQ, EqM, TryPureTanSubst,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')
_p_ = WildSymbol('p', optional_value=IDENTITY_ELEMENT)
p_ = WildSymbol('p')
_u_ = WildSymbol('u', optional_value=IDENTITY_ELEMENT)
u_ = WildSymbol('u')
v_ = WildSymbol('v')
w_ = WildSymbol('w')
y_ = WildSymbol('y')
z_ = WildSymbol('z')

RULES = [
    # Rule 1: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 2: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 3: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 4: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 5
    RubiRulePattern(
        pattern=Int(u_*cosh(_c_*(x*_b_ + _a_)), x),
        constraints=(FreeQ([_a_, _b_, _c_], x), FunctionOfQ(sinh(_c_*(x*_b_ + _a_))/FreeFactors(sinh(_c_*(x*_b_ + _a_)), x), u_, x, True),),
        replacement=With(List(Set(Symbol('d'), FreeFactors(sympy.sinh((_c_ * (_a_ + (_b_ * x)))), x))), (Symbol('d') * ((_b_ * _c_))**(Integer(-1)) * Subst(Int(SubstFor(Integer(1), (sympy.sinh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1))), u_, x), x), x, (sympy.sinh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1)))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=5,
    ),
    # Rule 6
    RubiRulePattern(
        pattern=Int(u_*sinh(_c_*(x*_b_ + _a_)), x),
        constraints=(FreeQ([_a_, _b_, _c_], x), FunctionOfQ(cosh(_c_*(x*_b_ + _a_))/FreeFactors(cosh(_c_*(x*_b_ + _a_)), x), u_, x, True),),
        replacement=With(List(Set(Symbol('d'), FreeFactors(sympy.cosh((_c_ * (_a_ + (_b_ * x)))), x))), (Symbol('d') * ((_b_ * _c_))**(Integer(-1)) * Subst(Int(SubstFor(Integer(1), (sympy.cosh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1))), u_, x), x), x, (sympy.cosh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1)))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=6,
    ),
    # Rule 7: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 8: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 9
    RubiRulePattern(
        pattern=Int(u_*coth(_c_*(x*_b_ + _a_)), x),
        constraints=(FreeQ([_a_, _b_, _c_], x), FunctionOfQ(sinh(_c_*(x*_b_ + _a_))/FreeFactors(sinh(_c_*(x*_b_ + _a_)), x), u_, x, True),),
        replacement=With(List(Set(Symbol('d'), FreeFactors(sympy.sinh((_c_ * (_a_ + (_b_ * x)))), x))), (((_b_ * _c_))**(Integer(-1)) * Subst(Int(SubstFor((x)**(Integer(-1)), (sympy.sinh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1))), u_, x), x), x, (sympy.sinh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1)))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=9,
    ),
    # Rule 10
    RubiRulePattern(
        pattern=Int(u_*tanh(_c_*(x*_b_ + _a_)), x),
        constraints=(FreeQ([_a_, _b_, _c_], x), FunctionOfQ(cosh(_c_*(x*_b_ + _a_))/FreeFactors(cosh(_c_*(x*_b_ + _a_)), x), u_, x, True),),
        replacement=With(List(Set(Symbol('d'), FreeFactors(sympy.cosh((_c_ * (_a_ + (_b_ * x)))), x))), (((_b_ * _c_))**(Integer(-1)) * Subst(Int(SubstFor((x)**(Integer(-1)), (sympy.cosh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1))), u_, x), x), x, (sympy.cosh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1)))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=10,
    ),
    # Rule 11: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 12
    RubiRulePattern(
        pattern=Int(u_/cos(_c_*(x*_b_ + _a_))**2, x),
        constraints=(FreeQ([_a_, _b_, _c_], x), NonsumQ(u_), FunctionOfQ(tan(_c_*(x*_b_ + _a_))/FreeFactors(tan(_c_*(x*_b_ + _a_)), x), u_, x, True),),
        replacement=With(List(Set(Symbol('d'), FreeFactors(sympy.tan((_c_ * (_a_ + (_b_ * x)))), x))), (Symbol('d') * ((_b_ * _c_))**(Integer(-1)) * Subst(Int(SubstFor(Integer(1), (sympy.tan((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1))), u_, x), x), x, (sympy.tan((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1)))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=12,
    ),
    # Rule 13: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 14
    RubiRulePattern(
        pattern=Int(u_/sin(_c_*(x*_b_ + _a_))**2, x),
        constraints=(FreeQ([_a_, _b_, _c_], x), NonsumQ(u_), FunctionOfQ(cot(_c_*(x*_b_ + _a_))/FreeFactors(cot(_c_*(x*_b_ + _a_)), x), u_, x, True),),
        replacement=With(List(Set(Symbol('d'), FreeFactors(sympy.cot((_c_ * (_a_ + (_b_ * x)))), x))), ((Integer(-1) * Symbol('d')) * ((_b_ * _c_))**(Integer(-1)) * Subst(Int(SubstFor(Integer(1), (sympy.cot((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1))), u_, x), x), x, (sympy.cot((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1)))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=14,
    ),
    # Rule 15
    RubiRulePattern(
        pattern=Int(u_*sech(_c_*(x*_b_ + _a_))**2, x),
        constraints=(FreeQ([_a_, _b_, _c_], x), NonsumQ(u_), FunctionOfQ(tanh(_c_*(x*_b_ + _a_))/FreeFactors(tanh(_c_*(x*_b_ + _a_)), x), u_, x, True),),
        replacement=With(List(Set(Symbol('d'), FreeFactors(sympy.tanh((_c_ * (_a_ + (_b_ * x)))), x))), (Symbol('d') * ((_b_ * _c_))**(Integer(-1)) * Subst(Int(SubstFor(Integer(1), (sympy.tanh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1))), u_, x), x), x, (sympy.tanh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1)))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=15,
    ),
    # Rule 16
    RubiRulePattern(
        pattern=Int(u_*csch(_c_*(x*_b_ + _a_))**2, x),
        constraints=(FreeQ([_a_, _b_, _c_], x), NonsumQ(u_), FunctionOfQ(coth(_c_*(x*_b_ + _a_))/FreeFactors(coth(_c_*(x*_b_ + _a_)), x), u_, x, True),),
        replacement=With(List(Set(Symbol('d'), FreeFactors(sympy.coth((_c_ * (_a_ + (_b_ * x)))), x))), ((Integer(-1) * Symbol('d')) * ((_b_ * _c_))**(Integer(-1)) * Subst(Int(SubstFor(Integer(1), (sympy.coth((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1))), u_, x), x), x, (sympy.coth((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1)))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=16,
    ),
    # Rule 17: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 18: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 19
    RubiRulePattern(
        pattern=Int(u_*coth(_c_*(x*_b_ + _a_))**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_], x), IntegerQ(_n_), FunctionOfQ(tanh(_c_*(x*_b_ + _a_))/FreeFactors(tanh(_c_*(x*_b_ + _a_)), x), u_, x, True), TryPureTanSubst(ActivateTrig(u_)*coth(_c_*(x*_b_ + _a_))**_n_, x),),
        replacement=With(List(Set(Symbol('d'), FreeFactors(sympy.tanh((_c_ * (_a_ + (_b_ * x)))), x))), (((_b_ * _c_ * (Symbol('d'))**((_n_ + Integer(-1)))))**(Integer(-1)) * Subst(Int(SubstFor((((x)**(_n_) * (Integer(1) + (Integer(-1) * ((Symbol('d'))**(Integer(2)) * (x)**(Integer(2)))))))**(Integer(-1)), (sympy.tanh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1))), u_, x), x), x, (sympy.tanh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1)))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=19,
    ),
    # Rule 20
    RubiRulePattern(
        pattern=Int(u_*tanh(_c_*(x*_b_ + _a_))**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_], x), IntegerQ(_n_), FunctionOfQ(coth(_c_*(x*_b_ + _a_))/FreeFactors(coth(_c_*(x*_b_ + _a_)), x), u_, x, True), TryPureTanSubst(ActivateTrig(u_)*tanh(_c_*(x*_b_ + _a_))**_n_, x),),
        replacement=With(List(Set(Symbol('d'), FreeFactors(sympy.coth((_c_ * (_a_ + (_b_ * x)))), x))), (((_b_ * _c_ * (Symbol('d'))**((_n_ + Integer(-1)))))**(Integer(-1)) * Subst(Int(SubstFor((((x)**(_n_) * (Integer(1) + (Integer(-1) * ((Symbol('d'))**(Integer(2)) * (x)**(Integer(2)))))))**(Integer(-1)), (sympy.coth((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1))), u_, x), x), x, (sympy.coth((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1)))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=20,
    ),
    # Rule 23: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 24: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 25: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 26: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 27
    RubiRulePattern(
        pattern=Int(u_*cosh(_c_*(x*_b_ + _a_)), x),
        constraints=(FreeQ([_a_, _b_, _c_], x), FunctionOfQ(sinh(_c_*(x*_b_ + _a_))/FreeFactors(sinh(_c_*(x*_b_ + _a_)), x), u_, x),),
        replacement=With(List(Set(Symbol('d'), FreeFactors(sympy.sinh((_c_ * (_a_ + (_b_ * x)))), x))), (Symbol('d') * ((_b_ * _c_))**(Integer(-1)) * Subst(Int(SubstFor(Integer(1), (sympy.sinh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1))), u_, x), x), x, (sympy.sinh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1)))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=27,
    ),
    # Rule 28
    RubiRulePattern(
        pattern=Int(u_*sinh(_c_*(x*_b_ + _a_)), x),
        constraints=(FreeQ([_a_, _b_, _c_], x), FunctionOfQ(cosh(_c_*(x*_b_ + _a_))/FreeFactors(cosh(_c_*(x*_b_ + _a_)), x), u_, x),),
        replacement=With(List(Set(Symbol('d'), FreeFactors(sympy.cosh((_c_ * (_a_ + (_b_ * x)))), x))), (Symbol('d') * ((_b_ * _c_))**(Integer(-1)) * Subst(Int(SubstFor(Integer(1), (sympy.cosh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1))), u_, x), x), x, (sympy.cosh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1)))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=28,
    ),
    # Rule 29: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 30: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 31
    RubiRulePattern(
        pattern=Int(u_*coth(_c_*(x*_b_ + _a_)), x),
        constraints=(FreeQ([_a_, _b_, _c_], x), FunctionOfQ(sinh(_c_*(x*_b_ + _a_))/FreeFactors(sinh(_c_*(x*_b_ + _a_)), x), u_, x),),
        replacement=With(List(Set(Symbol('d'), FreeFactors(sympy.sinh((_c_ * (_a_ + (_b_ * x)))), x))), (((_b_ * _c_))**(Integer(-1)) * Subst(Int(SubstFor((x)**(Integer(-1)), (sympy.sinh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1))), u_, x), x), x, (sympy.sinh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1)))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=31,
    ),
    # Rule 32
    RubiRulePattern(
        pattern=Int(u_*tanh(_c_*(x*_b_ + _a_)), x),
        constraints=(FreeQ([_a_, _b_, _c_], x), FunctionOfQ(cosh(_c_*(x*_b_ + _a_))/FreeFactors(cosh(_c_*(x*_b_ + _a_)), x), u_, x),),
        replacement=With(List(Set(Symbol('d'), FreeFactors(sympy.cosh((_c_ * (_a_ + (_b_ * x)))), x))), (((_b_ * _c_))**(Integer(-1)) * Subst(Int(SubstFor((x)**(Integer(-1)), (sympy.cosh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1))), u_, x), x), x, (sympy.cosh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1)))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=32,
    ),
    # Rule 33: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 34: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 35: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 36: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 37
    RubiRulePattern(
        pattern=Int(u_*cosh(_c_*(x*_b_ + _a_))**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_], x), IntegerQ(n_/2 + sympy.S(-1)/2), NonsumQ(u_), FunctionOfQ(sinh(_c_*(x*_b_ + _a_))/FreeFactors(sinh(_c_*(x*_b_ + _a_)), x), u_, x),),
        replacement=With(List(Set(Symbol('d'), FreeFactors(sympy.sinh((_c_ * (_a_ + (_b_ * x)))), x))), (Symbol('d') * ((_b_ * _c_))**(Integer(-1)) * Subst(Int(SubstFor(((Integer(1) + ((Symbol('d'))**(Integer(2)) * (x)**(Integer(2)))))**(((n_ + Integer(-1)) * (Integer(2))**(Integer(-1)))), (sympy.sinh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1))), u_, x), x), x, (sympy.sinh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1)))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=37,
    ),
    # Rule 38
    RubiRulePattern(
        pattern=Int(u_*sech(_c_*(x*_b_ + _a_))**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_], x), IntegerQ(n_/2 + sympy.S(-1)/2), NonsumQ(u_), FunctionOfQ(sinh(_c_*(x*_b_ + _a_))/FreeFactors(sinh(_c_*(x*_b_ + _a_)), x), u_, x),),
        replacement=With(List(Set(Symbol('d'), FreeFactors(sympy.sinh((_c_ * (_a_ + (_b_ * x)))), x))), (Symbol('d') * ((_b_ * _c_))**(Integer(-1)) * Subst(Int(SubstFor(((Integer(1) + ((Symbol('d'))**(Integer(2)) * (x)**(Integer(2)))))**((((Integer(-1) * n_) + Integer(-1)) * (Integer(2))**(Integer(-1)))), (sympy.sinh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1))), u_, x), x), x, (sympy.sinh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1)))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=38,
    ),
    # Rule 39
    RubiRulePattern(
        pattern=Int(u_*sinh(_c_*(x*_b_ + _a_))**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_], x), IntegerQ(n_/2 + sympy.S(-1)/2), NonsumQ(u_), FunctionOfQ(cosh(_c_*(x*_b_ + _a_))/FreeFactors(cosh(_c_*(x*_b_ + _a_)), x), u_, x),),
        replacement=With(List(Set(Symbol('d'), FreeFactors(sympy.cosh((_c_ * (_a_ + (_b_ * x)))), x))), (Symbol('d') * ((_b_ * _c_))**(Integer(-1)) * Subst(Int(SubstFor(((Integer(-1) + ((Symbol('d'))**(Integer(2)) * (x)**(Integer(2)))))**(((n_ + Integer(-1)) * (Integer(2))**(Integer(-1)))), (sympy.cosh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1))), u_, x), x), x, (sympy.cosh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1)))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=39,
    ),
    # Rule 40
    RubiRulePattern(
        pattern=Int(u_*csch(_c_*(x*_b_ + _a_))**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_], x), IntegerQ(n_/2 + sympy.S(-1)/2), NonsumQ(u_), FunctionOfQ(cosh(_c_*(x*_b_ + _a_))/FreeFactors(cosh(_c_*(x*_b_ + _a_)), x), u_, x),),
        replacement=With(List(Set(Symbol('d'), FreeFactors(sympy.cosh((_c_ * (_a_ + (_b_ * x)))), x))), (Symbol('d') * ((_b_ * _c_))**(Integer(-1)) * Subst(Int(SubstFor(((Integer(-1) + ((Symbol('d'))**(Integer(2)) * (x)**(Integer(2)))))**((((Integer(-1) * n_) + Integer(-1)) * (Integer(2))**(Integer(-1)))), (sympy.cosh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1))), u_, x), x), x, (sympy.cosh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1)))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=40,
    ),
    # Rule 41: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 42: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 43
    RubiRulePattern(
        pattern=Int(u_*coth(_c_*(x*_b_ + _a_))**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_], x), IntegerQ(n_/2 + sympy.S(-1)/2), NonsumQ(u_), FunctionOfQ(sinh(_c_*(x*_b_ + _a_))/FreeFactors(sinh(_c_*(x*_b_ + _a_)), x), u_, x),),
        replacement=With(List(Set(Symbol('d'), FreeFactors(sympy.sinh((_c_ * (_a_ + (_b_ * x)))), x))), (((_b_ * _c_ * (Symbol('d'))**((n_ + Integer(-1)))))**(Integer(-1)) * Subst(Int(SubstFor((((Integer(1) + ((Symbol('d'))**(Integer(2)) * (x)**(Integer(2)))))**(((n_ + Integer(-1)) * (Integer(2))**(Integer(-1)))) * ((x)**(n_))**(Integer(-1))), (sympy.sinh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1))), u_, x), x), x, (sympy.sinh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1)))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=43,
    ),
    # Rule 44
    RubiRulePattern(
        pattern=Int(u_*tanh(_c_*(x*_b_ + _a_))**n_, x),
        constraints=(FreeQ([_a_, _b_, _c_], x), IntegerQ(n_/2 + sympy.S(-1)/2), NonsumQ(u_), FunctionOfQ(cosh(_c_*(x*_b_ + _a_))/FreeFactors(cosh(_c_*(x*_b_ + _a_)), x), u_, x),),
        replacement=With(List(Set(Symbol('d'), FreeFactors(sympy.cosh((_c_ * (_a_ + (_b_ * x)))), x))), (((_b_ * _c_ * (Symbol('d'))**((n_ + Integer(-1)))))**(Integer(-1)) * Subst(Int(SubstFor((((Integer(-1) + ((Symbol('d'))**(Integer(2)) * (x)**(Integer(2)))))**(((n_ + Integer(-1)) * (Integer(2))**(Integer(-1)))) * ((x)**(n_))**(Integer(-1))), (sympy.cosh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1))), u_, x), x), x, (sympy.cosh((_c_ * (_a_ + (_b_ * x)))) * (Symbol('d'))**(Integer(-1)))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=44,
    ),
    # Rule 45: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 46: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 49
    RubiRulePattern(
        pattern=Int(_u_*(_a_ + _b_*cos(x*_e_ + _d_)**2 + _c_*sin(x*_e_ + _d_)**2)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _p_], x), EqQ(_b_ - _c_, 0),),
        replacement=(_a_ + _c_)**_p_*Int(ActivateTrig(_u_), x),
        module_name='4.7.5 Inert trig functions',
        rule_number=49,
    ),
    # Rule 50
    RubiRulePattern(
        pattern=Int(_u_*(_a_ + _b_*tan(x*_e_ + _d_)**2 + _c_*sec(x*_e_ + _d_)**2)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _p_], x), EqQ(_b_ + _c_, 0),),
        replacement=(_a_ + _c_)**_p_*Int(ActivateTrig(_u_), x),
        module_name='4.7.5 Inert trig functions',
        rule_number=50,
    ),
    # Rule 51
    RubiRulePattern(
        pattern=Int(_u_*(_a_ + _b_*cot(x*_e_ + _d_)**2 + _c_*csc(x*_e_ + _d_)**2)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _p_], x), EqQ(_b_ + _c_, 0),),
        replacement=(_a_ + _c_)**_p_*Int(ActivateTrig(_u_), x),
        module_name='4.7.5 Inert trig functions',
        rule_number=51,
    ),
    # Rule 52
    RubiRulePattern(
        pattern=Int(u_/y_, x),
        constraints=(Not(InertTrigFreeQ(u_)), Not(FalseQ(DerivativeDivides(ActivateTrig(y_), ActivateTrig(u_), x))),),
        replacement=With(List(Set(Symbol('q'), DerivativeDivides(ActivateTrig(y_), ActivateTrig(u_), x))), (Symbol('q') * sympy.log(ActivateTrig(y_)))),
        module_name='4.7.5 Inert trig functions',
        rule_number=52,
    ),
    # Rule 53
    RubiRulePattern(
        pattern=Int(u_/(w_*y_), x),
        constraints=(Not(InertTrigFreeQ(u_)), Not(FalseQ(DerivativeDivides(ActivateTrig(w_*y_), ActivateTrig(u_), x))),),
        replacement=With(List(Set(Symbol('q'), DerivativeDivides(ActivateTrig((y_ * w_)), ActivateTrig(u_), x))), (Symbol('q') * sympy.log(ActivateTrig((y_ * w_))))),
        module_name='4.7.5 Inert trig functions',
        rule_number=53,
    ),
    # Rule 54
    RubiRulePattern(
        pattern=Int(u_*y_**_m_, x),
        constraints=(FreeQ(_m_, x), NeQ(_m_, -1), Not(InertTrigFreeQ(u_)), Not(FalseQ(DerivativeDivides(ActivateTrig(y_), ActivateTrig(u_), x))),),
        replacement=With(List(Set(Symbol('q'), DerivativeDivides(ActivateTrig(y_), ActivateTrig(u_), x))), (Symbol('q') * ActivateTrig((y_)**((_m_ + Integer(1)))) * ((_m_ + Integer(1)))**(Integer(-1)))),
        module_name='4.7.5 Inert trig functions',
        rule_number=54,
    ),
    # Rule 55
    RubiRulePattern(
        pattern=Int(u_*y_**_m_*z_**_n_, x),
        constraints=(FreeQ([_m_, _n_], x), NeQ(_m_, -1), Not(InertTrigFreeQ(u_)), Not(FalseQ(DerivativeDivides(ActivateTrig(y_*z_), ActivateTrig(u_*z_**(-_m_ + _n_)), x))),),
        replacement=With(List(Set(Symbol('q'), DerivativeDivides(ActivateTrig((y_ * z_)), ActivateTrig((u_ * (z_)**((_n_ + (Integer(-1) * _m_))))), x))), (Symbol('q') * ActivateTrig(((y_)**((_m_ + Integer(1))) * (z_)**((_m_ + Integer(1))))) * ((_m_ + Integer(1)))**(Integer(-1)))),
        module_name='4.7.5 Inert trig functions',
        rule_number=55,
    ),
    # Rule 56: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 57: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 59
    RubiRulePattern(
        pattern=Int(u_*(_c_*sin(v_))**m_, x),
        constraints=(FreeQ(_c_, x), LinearQ(v_, x), IntegerQ(m_ + sympy.S.Half), Not(SumQ(u_)), InverseFunctionFreeQ(u_, x), Not(FalseQ(FunctionOfTrig(u_*sin(v_/2)**(2*m_)/(_c_*tan(v_/2))**m_, x))), FunctionOfQ(NonfreeFactors(tan(FunctionOfTrig(u_*sin(v_/2)**(2*m_)/(_c_*tan(v_/2))**m_, x)), x), u_*sin(v_/2)**(2*m_)/(_c_*tan(v_/2))**m_, x),),
        replacement=With(List(Set(Symbol('w'), FunctionOfTrig((u_ * (sympy.sin((v_ * (Integer(2))**(Integer(-1)))))**((Integer(2) * m_)) * (((_c_ * sympy.tan((v_ * (Integer(2))**(Integer(-1))))))**(m_))**(Integer(-1))), x))), (((_c_ * sympy.sin(v_)))**(m_) * ((_c_ * sympy.tan((v_ * (Integer(2))**(Integer(-1))))))**(m_) * ((sympy.sin((v_ * (Integer(2))**(Integer(-1)))))**((Integer(2) * m_)))**(Integer(-1)) * Int((u_ * (sympy.sin((v_ * (Integer(2))**(Integer(-1)))))**((Integer(2) * m_)) * (((_c_ * sympy.tan((v_ * (Integer(2))**(Integer(-1))))))**(m_))**(Integer(-1))), x))),
        module_name='4.7.5 Inert trig functions',
        rule_number=59,
    ),
    # Rule 60
    RubiRulePattern(
        pattern=Int(_u_*(_a_*tan(x*_d_ + _c_)**_n_ + _b_*sec(x*_d_ + _c_)**_n_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_], x), IntegersQ(_n_, p_),),
        replacement=Int((_a_*sin(x*_d_ + _c_)**_n_ + _b_)**p_*ActivateTrig(_u_)*sec(x*_d_ + _c_)**(_n_*p_), x),
        module_name='4.7.5 Inert trig functions',
        rule_number=60,
    ),
    # Rule 61
    RubiRulePattern(
        pattern=Int(_u_*(_a_*cot(x*_d_ + _c_)**_n_ + _b_*csc(x*_d_ + _c_)**_n_)**p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_], x), IntegersQ(_n_, p_),),
        replacement=Int((_a_*cos(x*_d_ + _c_)**_n_ + _b_)**p_*ActivateTrig(_u_)*csc(x*_d_ + _c_)**(_n_*p_), x),
        module_name='4.7.5 Inert trig functions',
        rule_number=61,
    ),
    # Rule 62: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 63: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 64: SKIPPED - ValueError: Non-string function head ['Pattern', 'F', ['Blank']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 65
    RubiRulePattern(
        pattern=Int(_u_*(_a_*cos(x*_d_ + _c_) + _b_*sin(x*_d_ + _c_))**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _n_], x), EqQ(_a_**2 + _b_**2, 0),),
        replacement=Int((_a_*exp(-_a_*(x*_d_ + _c_)/_b_))**_n_*ActivateTrig(_u_), x),
        module_name='4.7.5 Inert trig functions',
        rule_number=65,
    ),
    # Rule 66
    RubiRulePattern(
        pattern=Int(u_, x),
        constraints=(TrigSimplifyQ(u_),),
        replacement=Int(TrigSimplify(u_), x),
        module_name='4.7.5 Inert trig functions',
        rule_number=66,
    ),
    # Rule 67
    RubiRulePattern(
        pattern=Int(_u_*(a_*v_)**p_, x),
        constraints=(FreeQ([a_, p_], x), Not(IntegerQ(p_)), Not(InertTrigFreeQ(v_)),),
        replacement=With(List(Set(Symbol('uu'), ActivateTrig(_u_)), Set(Symbol('vv'), ActivateTrig(v_))), ((a_)**(IntPart(p_)) * ((a_ * Symbol('vv')))**(FracPart(p_)) * ((Symbol('vv'))**(FracPart(p_)))**(Integer(-1)) * Int((Symbol('uu') * (Symbol('vv'))**(p_)), x))),
        module_name='4.7.5 Inert trig functions',
        rule_number=67,
    ),
    # Rule 68
    RubiRulePattern(
        pattern=Int(_u_*(v_**m_)**p_, x),
        constraints=(FreeQ([m_, p_], x), Not(IntegerQ(p_)), Not(InertTrigFreeQ(v_)),),
        replacement=With(List(Set(Symbol('uu'), ActivateTrig(_u_)), Set(Symbol('vv'), ActivateTrig(v_))), (((Symbol('vv'))**(m_))**(FracPart(p_)) * ((Symbol('vv'))**((m_ * FracPart(p_))))**(Integer(-1)) * Int((Symbol('uu') * (Symbol('vv'))**((m_ * p_))), x))),
        module_name='4.7.5 Inert trig functions',
        rule_number=68,
    ),
    # Rule 69
    RubiRulePattern(
        pattern=Int(_u_*(v_**_m_*w_**_n_)**p_, x),
        constraints=(FreeQ([_m_, _n_, p_], x), Not(IntegerQ(p_)), Or(Not(InertTrigFreeQ(v_)), Not(InertTrigFreeQ(w_))),),
        replacement=With(List(Set(Symbol('uu'), ActivateTrig(_u_)), Set(Symbol('vv'), ActivateTrig(v_)), Set(Symbol('ww'), ActivateTrig(w_))), ((((Symbol('vv'))**(_m_) * (Symbol('ww'))**(_n_)))**(FracPart(p_)) * (((Symbol('vv'))**((_m_ * FracPart(p_))) * (Symbol('ww'))**((_n_ * FracPart(p_)))))**(Integer(-1)) * Int((Symbol('uu') * (Symbol('vv'))**((_m_ * p_)) * (Symbol('ww'))**((_n_ * p_))), x))),
        module_name='4.7.5 Inert trig functions',
        rule_number=69,
    ),
    # Rule 70
    RubiRulePattern(
        pattern=Int(u_, x),
        constraints=(Not(InertTrigFreeQ(u_)), SumQ(ExpandTrig(u_, x)),),
        replacement=With(List(Set(Symbol('v'), ExpandTrig(u_, x))), Int(Symbol('v'), x)),
        module_name='4.7.5 Inert trig functions',
        rule_number=70,
    ),
    # Rule 72
    RubiRulePattern(
        pattern=Int(u_, x),
        constraints=(Not(InertTrigFreeQ(u_)),),
        replacement=With(List(Set(Symbol('v'), ActivateTrig(u_))), CannotIntegrate(Symbol('v'), x)),
        module_name='4.7.5 Inert trig functions',
        rule_number=72,
    ),

]

# Summary: 37 rules translated, 35 skipped
