# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_rules/codegen/generate.py
# Source: 4.7.2 Tangent normalization rules.m
# Module: 4.7.2 Tangent normalization rules
#
# This file contains Rubi integration rules as RubiRulePattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Integer, Integral, Lambda, Rational, Symbol, Tuple as SympyTuple, Eq, Ne, Lt, Gt, Le, Ge, log, sqrt, pi, I, oo
from rubi_rules.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (sin, cos, tan, sec, csc, cot, asin, acos, atan, atan2, asec, acsc, acot,
                   sinh, cosh, tanh, sech, csch, coth, asinh, acosh, atanh, asech, acsch, acoth,
                   exp, Abs, diff, denom, frac, floor, root, simplify,
                   elliptic_e, elliptic_f, hyper, appellf1)

from sympy_matching.wild import WildSymbol, WildHeadApp, WildHeadDeriv, IDENTITY_ELEMENT
from rubi_rules.base_objects import Int, RubiRulePattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_rules.utils.inert_functions import (
    InertSin, InertCos, InertTan, InertCot, InertSec, InertCsc)
from rubi_rules.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, OddQ, EvenQ, NumberQ, NumericQ, AtomQ, MemberQ,
    PositiveQ, NegativeQ, PolynomialQ, TrueQ, FalseQ, MatchQ, PrimeQ, UnsameQ,
    # RUBI-specific constraints
    EqQ, NeQ, IGtQ, ILtQ, IGeQ, ILeQ, GtQ, LtQ, GeQ, LeQ, PosQ, NegQ,
    IntegersQ, HalfIntegerQ, FractionQ, RationalQ, ComplexNumberQ, RealNumberQ,
    FractionOrNegativeQ, SqrtNumberQ, PowerQ, ProductQ, SumQ, NonsumQ,
    IntegerPowerQ, FractionalPowerQ, PolyQ, LinearQ, QuadraticQ, BinomialQ,
    TrinomialQ, LinearMatchQ, QuadraticMatchQ, BinomialMatchQ, TrinomialMatchQ,
    TrigQ, HyperbolicQ, InverseTrigQ, InverseHyperbolicQ, LogQ, ComplexFreeQ,
    InverseFunctionFreeQ, FractionalPowerFreeQ, TrigHyperbolicFreeQ, IntegralFreeQ,
    RationalFunctionQ, AlgebraicFunctionQ, IndependentQ, SimplerQ, SumSimplerQ,
    FunctionOfQ, PiecewiseLinearQ, ExpressionEqQ,
    IntLinearQ, IntBinomialQ, IntQuadraticQ,
    MonomialQ, LinearPairQ,
    GeneralizedBinomialQ, GeneralizedBinomialMatchQ,
    GeneralizedTrinomialQ, GeneralizedTrinomialMatchQ,
    NiceSqrtQ, SimplerSqrtQ, FractionalPowerFactorQ,
    SumBaseQ, InverseFunctionQ, InertTrigQ, InertTrigFreeQ,
    CalculusFreeQ, QuotientOfLinearsQ,
    PowerOfLinearQ, PowerOfLinearMatchQ,
    FunctionOfExponentialQ,
    KnownSineIntegrandQ, KnownSecantIntegrandQ,
    KnownTangentIntegrandQ, KnownCotangentIntegrandQ,
    EulerIntegrandQ, SubstForFractionalPowerQ,
    PerfectSquareQ, PolynomialInQ, FunctionOfTrigOfLinearQ,
    SimplerIntegrandQ, PseudoBinomialPairQ, QuadraticProductQ,
    EveryQ, TrigSimplifyQ, EqM, TryPureTanSubst,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

_A_ = WildSymbol('A', optional_value=IDENTITY_ELEMENT)
A_ = WildSymbol('A')
_B_ = WildSymbol('B', optional_value=IDENTITY_ELEMENT)
B_ = WildSymbol('B')
_C_ = WildSymbol('C', optional_value=IDENTITY_ELEMENT)
C_ = WildSymbol('C')
_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')
n1_ = WildSymbol('n1')
n2_ = WildSymbol('n2')
_u_ = WildSymbol('u', optional_value=IDENTITY_ELEMENT)
u_ = WildSymbol('u')

RULES = [
    # Rule 1
    RubiRulePattern(
        pattern=Int(u_*(_c_*InertCot(x*_b_ + _a_))**_m_*(_d_*InertTan(x*_b_ + _a_))**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _m_, _n_], x), KnownTangentIntegrandQ(u_, x),),
        replacement=(_c_*cot(x*_b_ + _a_))**_m_*(_d_*tan(x*_b_ + _a_))**_m_*Int((_d_*tan(x*_b_ + _a_))**(-_m_ + _n_)*ActivateTrig(u_), x),
        module_name='4.7.2 Tangent normalization rules',
        rule_number=1,
    ),
    # Rule 2
    RubiRulePattern(
        pattern=Int(u_*(_c_*InertTan(x*_b_ + _a_))**_m_*(_d_*InertCos(x*_b_ + _a_))**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _m_, _n_], x), KnownCotangentIntegrandQ(u_, x),),
        replacement=(_c_*tan(x*_b_ + _a_))**_m_*(_d_*cos(x*_b_ + _a_))**_m_*Int((_d_*sin(x*_b_ + _a_))**_m_*(_d_*cos(x*_b_ + _a_))**(-_m_ + _n_)*ActivateTrig(u_), x)/(_d_*sin(x*_b_ + _a_))**_m_,
        module_name='4.7.2 Tangent normalization rules',
        rule_number=2,
    ),
    # Rule 3
    RubiRulePattern(
        pattern=Int(u_*(_c_*InertCot(x*_b_ + _a_))**_m_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _m_], x), Not(IntegerQ(_m_)), KnownTangentIntegrandQ(u_, x),),
        replacement=(_c_*tan(x*_b_ + _a_))**_m_*(_c_*cot(x*_b_ + _a_))**_m_*Int(ActivateTrig(u_)/(_c_*tan(x*_b_ + _a_))**_m_, x),
        module_name='4.7.2 Tangent normalization rules',
        rule_number=3,
    ),
    # Rule 4
    RubiRulePattern(
        pattern=Int(u_*(_c_*InertTan(x*_b_ + _a_))**_m_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _m_], x), Not(IntegerQ(_m_)), KnownCotangentIntegrandQ(u_, x),),
        replacement=(_c_*tan(x*_b_ + _a_))**_m_*(_c_*cot(x*_b_ + _a_))**_m_*Int(ActivateTrig(u_)/(_c_*cot(x*_b_ + _a_))**_m_, x),
        module_name='4.7.2 Tangent normalization rules',
        rule_number=4,
    ),
    # Rule 5
    RubiRulePattern(
        pattern=Int(u_*(_c_*InertTan(x*_b_ + _a_))**_n_*(A_ + _B_*InertCot(x*_b_ + _a_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, A_, _B_, _n_], x), KnownTangentIntegrandQ(u_, x),),
        replacement=_c_*Int((_c_*tan(x*_b_ + _a_))**(_n_ - 1)*(A_*tan(x*_b_ + _a_) + _B_)*ActivateTrig(u_), x),
        module_name='4.7.2 Tangent normalization rules',
        rule_number=5,
    ),
    # Rule 6
    RubiRulePattern(
        pattern=Int(u_*(_c_*InertCot(x*_b_ + _a_))**_n_*(A_ + _B_*InertTan(x*_b_ + _a_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, A_, _B_, _n_], x), KnownCotangentIntegrandQ(u_, x),),
        replacement=_c_*Int((_c_*cot(x*_b_ + _a_))**(_n_ - 1)*(A_*cot(x*_b_ + _a_) + _B_)*ActivateTrig(u_), x),
        module_name='4.7.2 Tangent normalization rules',
        rule_number=6,
    ),
    # Rule 7
    RubiRulePattern(
        pattern=Int(u_*(A_ + _B_*InertCot(x*_b_ + _a_)), x),
        constraints=(FreeQ([_a_, _b_, A_, _B_], x), KnownTangentIntegrandQ(u_, x),),
        replacement=Int((A_*tan(x*_b_ + _a_) + _B_)*ActivateTrig(u_)/tan(x*_b_ + _a_), x),
        module_name='4.7.2 Tangent normalization rules',
        rule_number=7,
    ),
    # Rule 8
    RubiRulePattern(
        pattern=Int(u_*(A_ + _B_*InertTan(x*_b_ + _a_)), x),
        constraints=(FreeQ([_a_, _b_, A_, _B_], x), KnownCotangentIntegrandQ(u_, x),),
        replacement=Int((A_*cot(x*_b_ + _a_) + _B_)*ActivateTrig(u_)/cot(x*_b_ + _a_), x),
        module_name='4.7.2 Tangent normalization rules',
        rule_number=8,
    ),
    # Rule 9
    RubiRulePattern(
        pattern=Int(_u_*(_c_*InertTan(x*_b_ + _a_))**_n_*(_A_ + _B_*InertCot(x*_b_ + _a_) + _C_*InertCot(x*_b_ + _a_)**2), x),
        constraints=(FreeQ([_a_, _b_, _c_, _A_, _B_, _C_, _n_], x), KnownTangentIntegrandQ(_u_, x),),
        replacement=_c_**2*Int((_c_*tan(x*_b_ + _a_))**(_n_ - 2)*(_A_*tan(x*_b_ + _a_)**2 + _B_*tan(x*_b_ + _a_) + _C_)*ActivateTrig(_u_), x),
        module_name='4.7.2 Tangent normalization rules',
        rule_number=9,
    ),
    # Rule 10
    RubiRulePattern(
        pattern=Int(_u_*(_c_*InertCot(x*_b_ + _a_))**_n_*(_A_ + _B_*InertTan(x*_b_ + _a_) + _C_*InertTan(x*_b_ + _a_)**2), x),
        constraints=(FreeQ([_a_, _b_, _c_, _A_, _B_, _C_, _n_], x), KnownCotangentIntegrandQ(_u_, x),),
        replacement=_c_**2*Int((_c_*cot(x*_b_ + _a_))**(_n_ - 2)*(_A_*cot(x*_b_ + _a_)**2 + _B_*cot(x*_b_ + _a_) + _C_)*ActivateTrig(_u_), x),
        module_name='4.7.2 Tangent normalization rules',
        rule_number=10,
    ),
    # Rule 11
    RubiRulePattern(
        pattern=Int(_u_*(_c_*InertTan(x*_b_ + _a_))**_n_*(A_ + _C_*InertCot(x*_b_ + _a_)**2), x),
        constraints=(FreeQ([_a_, _b_, _c_, A_, _C_, _n_], x), KnownTangentIntegrandQ(_u_, x),),
        replacement=_c_**2*Int((_c_*tan(x*_b_ + _a_))**(_n_ - 2)*(A_*tan(x*_b_ + _a_)**2 + _C_)*ActivateTrig(_u_), x),
        module_name='4.7.2 Tangent normalization rules',
        rule_number=11,
    ),
    # Rule 12
    RubiRulePattern(
        pattern=Int(_u_*(_c_*InertCot(x*_b_ + _a_))**_n_*(A_ + _C_*InertTan(x*_b_ + _a_)**2), x),
        constraints=(FreeQ([_a_, _b_, _c_, A_, _C_, _n_], x), KnownCotangentIntegrandQ(_u_, x),),
        replacement=_c_**2*Int((_c_*cot(x*_b_ + _a_))**(_n_ - 2)*(A_*cot(x*_b_ + _a_)**2 + _C_)*ActivateTrig(_u_), x),
        module_name='4.7.2 Tangent normalization rules',
        rule_number=12,
    ),
    # Rule 13
    RubiRulePattern(
        pattern=Int(u_*(_A_ + _B_*InertCot(x*_b_ + _a_) + _C_*InertCot(x*_b_ + _a_)**2), x),
        constraints=(FreeQ([_a_, _b_, _A_, _B_, _C_], x), KnownTangentIntegrandQ(u_, x),),
        replacement=Int((_A_*tan(x*_b_ + _a_)**2 + _B_*tan(x*_b_ + _a_) + _C_)*ActivateTrig(u_)/tan(x*_b_ + _a_)**2, x),
        module_name='4.7.2 Tangent normalization rules',
        rule_number=13,
    ),
    # Rule 14
    RubiRulePattern(
        pattern=Int(u_*(_A_ + _B_*InertTan(x*_b_ + _a_) + _C_*InertTan(x*_b_ + _a_)**2), x),
        constraints=(FreeQ([_a_, _b_, _A_, _B_, _C_], x), KnownCotangentIntegrandQ(u_, x),),
        replacement=Int((_A_*cot(x*_b_ + _a_)**2 + _B_*cot(x*_b_ + _a_) + _C_)*ActivateTrig(u_)/cot(x*_b_ + _a_)**2, x),
        module_name='4.7.2 Tangent normalization rules',
        rule_number=14,
    ),
    # Rule 15
    RubiRulePattern(
        pattern=Int(u_*(A_ + _C_*InertCot(x*_b_ + _a_)**2), x),
        constraints=(FreeQ([_a_, _b_, A_, _C_], x), KnownTangentIntegrandQ(u_, x),),
        replacement=Int((A_*tan(x*_b_ + _a_)**2 + _C_)*ActivateTrig(u_)/tan(x*_b_ + _a_)**2, x),
        module_name='4.7.2 Tangent normalization rules',
        rule_number=15,
    ),
    # Rule 16
    RubiRulePattern(
        pattern=Int(u_*(A_ + _C_*InertTan(x*_b_ + _a_)**2), x),
        constraints=(FreeQ([_a_, _b_, A_, _C_], x), KnownCotangentIntegrandQ(u_, x),),
        replacement=Int((A_*cot(x*_b_ + _a_)**2 + _C_)*ActivateTrig(u_)/cot(x*_b_ + _a_)**2, x),
        module_name='4.7.2 Tangent normalization rules',
        rule_number=16,
    ),
    # Rule 17
    RubiRulePattern(
        pattern=Int(u_*(_A_ + _B_*InertTan(x*_b_ + _a_) + _C_*InertCot(x*_b_ + _a_)), x),
        constraints=(FreeQ([_a_, _b_, _A_, _B_, _C_], x),),
        replacement=Int((_A_*tan(x*_b_ + _a_) + _B_*tan(x*_b_ + _a_)**2 + _C_)*ActivateTrig(u_)/tan(x*_b_ + _a_), x),
        module_name='4.7.2 Tangent normalization rules',
        rule_number=17,
    ),
    # Rule 18
    RubiRulePattern(
        pattern=Int(u_*(_A_*InertTan(x*_b_ + _a_)**_n_ + _B_*InertTan(x*_b_ + _a_)**n1_ + _C_*InertTan(x*_b_ + _a_)**n2_), x),
        constraints=(FreeQ([_a_, _b_, _A_, _B_, _C_, _n_], x), EqQ(n1_, _n_ + 1), EqQ(n2_, _n_ + 2),),
        replacement=Int((_A_ + _B_*tan(x*_b_ + _a_) + _C_*tan(x*_b_ + _a_)**2)*ActivateTrig(u_)*tan(x*_b_ + _a_)**_n_, x),
        module_name='4.7.2 Tangent normalization rules',
        rule_number=18,
    ),
    # Rule 19
    RubiRulePattern(
        pattern=Int(u_*(_A_*InertCot(x*_b_ + _a_)**_n_ + _B_*InertCot(x*_b_ + _a_)**n1_ + _C_*InertCot(x*_b_ + _a_)**n2_), x),
        constraints=(FreeQ([_a_, _b_, _A_, _B_, _C_, _n_], x), EqQ(n1_, _n_ + 1), EqQ(n2_, _n_ + 2),),
        replacement=Int((_A_ + _B_*cot(x*_b_ + _a_) + _C_*cot(x*_b_ + _a_)**2)*ActivateTrig(u_)*cot(x*_b_ + _a_)**_n_, x),
        module_name='4.7.2 Tangent normalization rules',
        rule_number=19,
    ),

]

# Summary: 19 rules translated, 0 skipped
