channels:
  - conda-forge
name: py310
dependencies:
- openssl
- pip
- python=3.10
- readline
- setuptools
- sqlite
- wheel
- zlib
- pip:
  - Sphinx
  - graphviz
  - multiset>=2.0,<3.0
  - setuptools_scm
