# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_rules/codegen/generate.py
# Source: 1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p.m
# Module: 1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p
#
# This file contains Rubi integration rules as RubiRulePattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Integer, Integral, Lambda, Rational, Symbol, Tuple as SympyTuple, Eq, Ne, Lt, Gt, Le, Ge, log, sqrt, pi, I, oo
from rubi_rules.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (sin, cos, tan, sec, csc, cot, asin, acos, atan, atan2, asec, acsc, acot,
                   sinh, cosh, tanh, sech, csch, coth, asinh, acosh, atanh, asech, acsch, acoth,
                   exp, Abs, diff, denom, frac, floor, root, simplify,
                   elliptic_e, elliptic_f, hyper, appellf1)

from sympy_matching.wild import WildSymbol, WildHeadApp, WildHeadDeriv, IDENTITY_ELEMENT
from rubi_rules.base_objects import Int, RubiRulePattern
from rubi_rules.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, OddQ, EvenQ, NumberQ, NumericQ, AtomQ, MemberQ,
    PositiveQ, NegativeQ, PolynomialQ, TrueQ, FalseQ, MatchQ, PrimeQ, UnsameQ,
    # RUBI-specific constraints
    EqQ, NeQ, IGtQ, ILtQ, IGeQ, ILeQ, GtQ, LtQ, GeQ, LeQ, PosQ, NegQ,
    IntegersQ, HalfIntegerQ, FractionQ, RationalQ, ComplexNumberQ, RealNumberQ,
    FractionOrNegativeQ, SqrtNumberQ, PowerQ, ProductQ, SumQ, NonsumQ,
    IntegerPowerQ, FractionalPowerQ, PolyQ, LinearQ, QuadraticQ, BinomialQ,
    TrinomialQ, LinearMatchQ, QuadraticMatchQ, BinomialMatchQ, TrinomialMatchQ,
    TrigQ, HyperbolicQ, InverseTrigQ, InverseHyperbolicQ, LogQ, ComplexFreeQ,
    InverseFunctionFreeQ, FractionalPowerFreeQ, TrigHyperbolicFreeQ, IntegralFreeQ,
    RationalFunctionQ, AlgebraicFunctionQ, IndependentQ, SimplerQ, SumSimplerQ,
    FunctionOfQ, PiecewiseLinearQ, ExpressionEqQ,
    IntLinearQ, IntBinomialQ, IntQuadraticQ,
    MonomialQ, LinearPairQ,
    GeneralizedBinomialQ, GeneralizedBinomialMatchQ,
    GeneralizedTrinomialQ, GeneralizedTrinomialMatchQ,
    NiceSqrtQ, SimplerSqrtQ, FractionalPowerFactorQ,
    SumBaseQ, InverseFunctionQ, InertTrigQ, InertTrigFreeQ,
    CalculusFreeQ, QuotientOfLinearsQ,
    PowerOfLinearQ, PowerOfLinearMatchQ,
    FunctionOfExponentialQ,
    KnownSineIntegrandQ, KnownSecantIntegrandQ,
    KnownTangentIntegrandQ, KnownCotangentIntegrandQ,
    EulerIntegrandQ, SubstForFractionalPowerQ,
    PerfectSquareQ, PolynomialInQ, FunctionOfTrigOfLinearQ,
    SimplerIntegrandQ, PseudoBinomialPairQ, QuadraticProductQ,
    EveryQ, TrigSimplifyQ, EqM, TryPureTanSubst,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

_A_ = WildSymbol('A', optional_value=IDENTITY_ELEMENT)
A_ = WildSymbol('A')
_B_ = WildSymbol('B', optional_value=IDENTITY_ELEMENT)
B_ = WildSymbol('B')
_C_ = WildSymbol('C', optional_value=IDENTITY_ELEMENT)
C_ = WildSymbol('C')
P4_ = WildSymbol('P4')
_Px_ = WildSymbol('Px', optional_value=IDENTITY_ELEMENT)
Px_ = WildSymbol('Px')
_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
f_ = WildSymbol('f')
_g_ = WildSymbol('g', optional_value=IDENTITY_ELEMENT)
g_ = WildSymbol('g')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
p_ = WildSymbol('p')
_u_ = WildSymbol('u', optional_value=IDENTITY_ELEMENT)
u_ = WildSymbol('u')

RULES = [
    # Rule 1
    RubiRulePattern(
        pattern=Int(Px_**p_*_u_, x),
        constraints=(FreeQ(p_, x), PolyQ(Px_, x, 4), EqQ(Coeff(Px_, x, 0), 0), Not(IntegerQ(p_)),),
        replacement=With(List(Set(Symbol('b'), Coeff(Px_, x, Integer(1))), Set(Symbol('c'), Coeff(Px_, x, Integer(2))), Set(Symbol('d'), Coeff(Px_, x, Integer(3))), Set(Symbol('e'), Coeff(Px_, x, Integer(4)))), Star(((Px_)**(FracPart(p_)) * (((x)**(FracPart(p_)) * ((Symbol('b') + (Symbol('c') * x) + (Symbol('d') * (x)**(Integer(2))) + (Symbol('e') * (x)**(Integer(3)))))**(FracPart(p_))))**(Integer(-1))), Int((_u_ * (x)**(p_) * ((Symbol('b') + (Symbol('c') * x) + (Symbol('d') * (x)**(Integer(2))) + (Symbol('e') * (x)**(Integer(3)))))**(p_)), x))),
        module_name='1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p',
        rule_number=1,
    ),
    # Rule 2
    RubiRulePattern(
        pattern=Int(_Px_*(x**4*_e_ + x**3*_d_ + x**2*_c_ + x*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), PolyQ(_Px_, x), ILtQ(p_, 0), EqQ(a_*_d_**2 - _b_**2*_e_, 0),),
        replacement=Star(_e_**p_, Int(ExpandIntegrand(_Px_*(x**2 + x*(_d_ - sqrt(8*a_*_d_*_e_/_b_ + _e_*(-4*a_*_c_ + _b_**2)/a_))/(2*_e_) + _b_/_d_)**p_*(x**2 + x*(_d_ + sqrt(8*a_*_d_*_e_/_b_ + _e_*(-4*a_*_c_ + _b_**2)/a_))/(2*_e_) + _b_/_d_)**p_, x), x)),
        module_name='1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p',
        rule_number=2,
    ),
    # Rule 3
    RubiRulePattern(
        pattern=Int(_Px_*(x**4*_e_ + x**3*_d_ + x*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_], x), PolyQ(_Px_, x), ILtQ(p_, 0), EqQ(a_*_d_**2 - _b_**2*_e_, 0),),
        replacement=Star(_e_**p_, Int(ExpandIntegrand(_Px_*(x**2 + x*(_d_ - sqrt(8*a_*_d_*_e_/_b_ + _d_**2))/(2*_e_) + _b_/_d_)**p_*(x**2 + x*(_d_ + sqrt(8*a_*_d_*_e_/_b_ + _d_**2))/(2*_e_) + _b_/_d_)**p_, x), x)),
        module_name='1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p',
        rule_number=3,
    ),
    # Rule 4
    RubiRulePattern(
        pattern=Int(_Px_*(x**4*_e_ + x**3*_d_ + x**2*_c_ + x*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), PolyQ(_Px_, x), ILtQ(p_, 0), RationalQ(a_, _b_, _c_, _d_, _e_), NeQ(a_*_d_**2 - _b_**2*_e_, 0), RationalQ(sympy.Function('Root')(((a_ * (_d_)**(Integer(2))) + (Integer(-1) * ((_b_)**(Integer(2)) * _e_)) + (((_b_ * (_d_)**(Integer(2))) + (Integer(-1) * (Integer(4) * _b_ * _c_ * _e_)) + (Integer(8) * a_ * _d_ * _e_)) * x) + (((_c_ * (_d_)**(Integer(2))) + (Integer(-1) * (Integer(4) * (_c_)**(Integer(2)) * _e_)) + (Integer(2) * _b_ * _d_ * _e_) + (Integer(16) * a_ * (_e_)**(Integer(2)))) * (x)**(Integer(2))) + (((_d_)**(Integer(3)) + (Integer(-1) * (Integer(4) * _c_ * _d_ * _e_)) + (Integer(8) * _b_ * (_e_)**(Integer(2)))) * (x)**(Integer(3)))), Integer(3))),),
        replacement=With(List(Set(Symbol('S'), sympy.Function('Root')(((a_ * (_d_)**(Integer(2))) + (Integer(-1) * ((_b_)**(Integer(2)) * _e_)) + (((_b_ * (_d_)**(Integer(2))) + (Integer(-1) * (Integer(4) * _b_ * _c_ * _e_)) + (Integer(8) * a_ * _d_ * _e_)) * x) + (((_c_ * (_d_)**(Integer(2))) + (Integer(-1) * (Integer(4) * (_c_)**(Integer(2)) * _e_)) + (Integer(2) * _b_ * _d_ * _e_) + (Integer(16) * a_ * (_e_)**(Integer(2)))) * (x)**(Integer(2))) + (((_d_)**(Integer(3)) + (Integer(-1) * (Integer(4) * _c_ * _d_ * _e_)) + (Integer(8) * _b_ * (_e_)**(Integer(2)))) * (x)**(Integer(3)))), Integer(3)))), Subst(Int((ReplaceAll(_Px_, Rule(x, (x + Symbol('S')))) * (ExpandToSum((a_ + (_b_ * (x + Symbol('S'))) + (_c_ * ((x + Symbol('S')))**(Integer(2))) + (_d_ * ((x + Symbol('S')))**(Integer(3))) + (_e_ * ((x + Symbol('S')))**(Integer(4)))), x))**(p_)), x), x, (x + (Integer(-1) * Symbol('S'))))),
        module_name='1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p',
        rule_number=4,
    ),
    # Rule 5
    RubiRulePattern(
        pattern=Int(_Px_*(x**4*_e_ + x**3*_d_ + x*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_], x), PolyQ(_Px_, x), ILtQ(p_, 0), RationalQ(a_, _b_, _d_, _e_), NeQ(a_*_d_**2 - _b_**2*_e_, 0), RationalQ(sympy.Function('Root')(((a_ * (_d_)**(Integer(2))) + (Integer(-1) * ((_b_)**(Integer(2)) * _e_)) + (((_b_ * (_d_)**(Integer(2))) + (Integer(8) * a_ * _d_ * _e_)) * x) + (((Integer(2) * _b_ * _d_ * _e_) + (Integer(16) * a_ * (_e_)**(Integer(2)))) * (x)**(Integer(2))) + (((_d_)**(Integer(3)) + (Integer(8) * _b_ * (_e_)**(Integer(2)))) * (x)**(Integer(3)))), Integer(3))),),
        replacement=With(List(Set(Symbol('S'), sympy.Function('Root')(((a_ * (_d_)**(Integer(2))) + (Integer(-1) * ((_b_)**(Integer(2)) * _e_)) + (((_b_ * (_d_)**(Integer(2))) + (Integer(8) * a_ * _d_ * _e_)) * x) + (((Integer(2) * _b_ * _d_ * _e_) + (Integer(16) * a_ * (_e_)**(Integer(2)))) * (x)**(Integer(2))) + (((_d_)**(Integer(3)) + (Integer(8) * _b_ * (_e_)**(Integer(2)))) * (x)**(Integer(3)))), Integer(3)))), Subst(Int((ReplaceAll(_Px_, Rule(x, (x + Symbol('S')))) * (ExpandToSum((a_ + (_b_ * (x + Symbol('S'))) + (_d_ * ((x + Symbol('S')))**(Integer(3))) + (_e_ * ((x + Symbol('S')))**(Integer(4)))), x))**(p_)), x), x, (x + (Integer(-1) * Symbol('S'))))),
        module_name='1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p',
        rule_number=5,
    ),
    # Rule 6
    RubiRulePattern(
        pattern=Int(x**_m_*_Px_*(x**4*_e_ + x**3*_d_ + x**2*_c_ + x*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _m_], x), PolyQ(_Px_, x), ILtQ(p_, 0), EqQ(a_*_d_**2 - _b_**2*_e_, 0),),
        replacement=Star(_e_**p_, Int(ExpandIntegrand(x**_m_*_Px_*(x**2 + x*(_d_ - sqrt(8*a_*_d_*_e_/_b_ + _e_*(-4*a_*_c_ + _b_**2)/a_))/(2*_e_) + _b_/_d_)**p_*(x**2 + x*(_d_ + sqrt(8*a_*_d_*_e_/_b_ + _e_*(-4*a_*_c_ + _b_**2)/a_))/(2*_e_) + _b_/_d_)**p_, x), x)),
        module_name='1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p',
        rule_number=6,
    ),
    # Rule 7
    RubiRulePattern(
        pattern=Int(x**_m_*_Px_*(x**4*_e_ + x**3*_d_ + x*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _d_, _e_, _m_], x), PolyQ(_Px_, x), ILtQ(p_, 0), EqQ(a_*_d_**2 - _b_**2*_e_, 0),),
        replacement=Star(_e_**p_, Int(ExpandIntegrand(x**_m_*_Px_*(x**2 + x*(_d_ - sqrt(8*a_*_d_*_e_/_b_ + _d_**2))/(2*_e_) + _b_/_d_)**p_*(x**2 + x*(_d_ + sqrt(8*a_*_d_*_e_/_b_ + _d_**2))/(2*_e_) + _b_/_d_)**p_, x), x)),
        module_name='1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p',
        rule_number=7,
    ),
    # Rule 8
    RubiRulePattern(
        pattern=Int(_Px_*(x**4*_e_ + x**3*_d_ + x**2*_c_ + x*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_], x), PolyQ(_Px_, x), ILtQ(p_, 0), NeQ(a_, 0), EqQ(_c_, _b_**2/a_), EqQ(_d_, _b_**3/a_**2), EqQ(_e_, _b_**4/a_**3),),
        replacement=Star(a_**(-3*p_), Int(ExpandIntegrand(_Px_*(-x**5*_b_**5 + a_**5)**p_/(-x*_b_ + a_)**p_, x), x)),
        module_name='1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p',
        rule_number=8,
    ),
    # Rule 9
    RubiRulePattern(
        pattern=Int(x**_m_*_Px_*(x**4*_e_ + x**3*_d_ + x**2*_c_ + x*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _m_], x), PolyQ(_Px_, x), ILtQ(p_, 0), NeQ(a_, 0), EqQ(_c_, _b_**2/a_), EqQ(_d_, _b_**3/a_**2), EqQ(_e_, _b_**4/a_**3),),
        replacement=Star(a_**(-3*p_), Int(ExpandIntegrand(x**_m_*_Px_*(-x**5*_b_**5 + a_**5)**p_/(-x*_b_ + a_)**p_, x), x)),
        module_name='1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p',
        rule_number=9,
    ),
    # Rule 10
    RubiRulePattern(
        pattern=Int((x**2*_C_ + x*_B_ + _A_)/(x**4*_e_ + x**3*_d_ + x**2*_c_ + x*_b_ + a_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _A_, _B_, _C_], x), EqQ(_B_**2*_d_ - 2*_B_*(2*_A_*_e_ + _C_*_c_) + 2*_C_*(_A_*_d_ + _C_*_b_), 0), EqQ(-4*_A_*_B_*_C_*_d_ + 4*_A_*_e_*(2*_A_*_C_ + _B_**2) - _B_**3*_d_ + 2*_B_**2*_C_*_c_ - 8*_C_**3*a_, 0), PosQ(_C_*(_C_*(-4*_c_*_e_ + _d_**2) + 2*_e_*(-4*_A_*_e_ + _B_*_d_))),),
        replacement=With(List(Set(Symbol('q'), sympy.root((_C_ * ((Integer(2) * _e_ * ((_B_ * _d_) + (Integer(-1) * (Integer(4) * _A_ * _e_)))) + (_C_ * ((_d_)**(Integer(2)) + (Integer(-1) * (Integer(4) * _c_ * _e_)))))), Integer(2)))), ((Integer(-2) * (_C_)**(Integer(2)) * (Symbol('q'))**(Integer(-1)) * sympy.atanh((((_C_ * _d_) + (Integer(-1) * (_B_ * _e_)) + (Integer(2) * _C_ * _e_ * x)) * (Symbol('q'))**(Integer(-1))))) + (Integer(2) * (_C_)**(Integer(2)) * (Symbol('q'))**(Integer(-1)) * sympy.atanh((_C_ * ((Integer(4) * _B_ * _c_ * _C_) + (Integer(-1) * (Integer(3) * (_B_)**(Integer(2)) * _d_)) + (Integer(-1) * (Integer(4) * _A_ * _C_ * _d_)) + (Integer(12) * _A_ * _B_ * _e_) + (Integer(4) * _C_ * ((Integer(2) * _c_ * _C_) + (Integer(-1) * (_B_ * _d_)) + (Integer(2) * _A_ * _e_)) * x) + (Integer(4) * _C_ * ((Integer(2) * _C_ * _d_) + (Integer(-1) * (_B_ * _e_))) * (x)**(Integer(2))) + (Integer(8) * (_C_)**(Integer(2)) * _e_ * (x)**(Integer(3)))) * ((Symbol('q') * ((_B_)**(Integer(2)) + (Integer(-1) * (Integer(4) * _A_ * _C_)))))**(Integer(-1))))))),
        module_name='1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p',
        rule_number=10,
    ),
    # Rule 11
    RubiRulePattern(
        pattern=Int((x**2*_C_ + _A_)/(x**4*_e_ + x**3*_d_ + x**2*_c_ + x*_b_ + a_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _A_, _C_], x), EqQ(_A_*_d_ + _C_*_b_, 0), EqQ(-_A_**2*_e_ + _C_**2*a_, 0), PosQ(_C_*(-8*_A_*_e_**2 + _C_*(-4*_c_*_e_ + _d_**2))),),
        replacement=With(List(Set(Symbol('q'), sympy.root((_C_ * ((Integer(-8) * _A_ * (_e_)**(Integer(2))) + (_C_ * ((_d_)**(Integer(2)) + (Integer(-1) * (Integer(4) * _c_ * _e_)))))), Integer(2)))), ((Integer(-2) * (_C_)**(Integer(2)) * (Symbol('q'))**(Integer(-1)) * sympy.atanh((_C_ * (_d_ + (Integer(2) * _e_ * x)) * (Symbol('q'))**(Integer(-1))))) + (Integer(2) * (_C_)**(Integer(2)) * (Symbol('q'))**(Integer(-1)) * sympy.atanh((_C_ * ((_A_ * _d_) + (Integer(-1) * (Integer(2) * ((_c_ * _C_) + (_A_ * _e_)) * x)) + (Integer(-1) * (Integer(2) * _C_ * _d_ * (x)**(Integer(2)))) + (Integer(-1) * (Integer(2) * _C_ * _e_ * (x)**(Integer(3))))) * ((_A_ * Symbol('q')))**(Integer(-1))))))),
        module_name='1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p',
        rule_number=11,
    ),
    # Rule 12
    RubiRulePattern(
        pattern=Int((x**2*_C_ + x*_B_ + _A_)/(x**4*_e_ + x**3*_d_ + x**2*_c_ + x*_b_ + a_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _A_, _B_, _C_], x), EqQ(_B_**2*_d_ - 2*_B_*(2*_A_*_e_ + _C_*_c_) + 2*_C_*(_A_*_d_ + _C_*_b_), 0), EqQ(-4*_A_*_B_*_C_*_d_ + 4*_A_*_e_*(2*_A_*_C_ + _B_**2) - _B_**3*_d_ + 2*_B_**2*_C_*_c_ - 8*_C_**3*a_, 0), NegQ(_C_*(_C_*(-4*_c_*_e_ + _d_**2) + 2*_e_*(-4*_A_*_e_ + _B_*_d_))),),
        replacement=With(List(Set(Symbol('q'), sympy.root(((Integer(-1) * _C_) * ((Integer(2) * _e_ * ((_B_ * _d_) + (Integer(-1) * (Integer(4) * _A_ * _e_)))) + (_C_ * ((_d_)**(Integer(2)) + (Integer(-1) * (Integer(4) * _c_ * _e_)))))), Integer(2)))), ((Integer(2) * (_C_)**(Integer(2)) * (Symbol('q'))**(Integer(-1)) * sympy.atan((((_C_ * _d_) + (Integer(-1) * (_B_ * _e_)) + (Integer(2) * _C_ * _e_ * x)) * (Symbol('q'))**(Integer(-1))))) + (Integer(-1) * (Integer(2) * (_C_)**(Integer(2)) * (Symbol('q'))**(Integer(-1)) * sympy.atan((_C_ * ((Integer(4) * _B_ * _c_ * _C_) + (Integer(-1) * (Integer(3) * (_B_)**(Integer(2)) * _d_)) + (Integer(-1) * (Integer(4) * _A_ * _C_ * _d_)) + (Integer(12) * _A_ * _B_ * _e_) + (Integer(4) * _C_ * ((Integer(2) * _c_ * _C_) + (Integer(-1) * (_B_ * _d_)) + (Integer(2) * _A_ * _e_)) * x) + (Integer(4) * _C_ * ((Integer(2) * _C_ * _d_) + (Integer(-1) * (_B_ * _e_))) * (x)**(Integer(2))) + (Integer(8) * (_C_)**(Integer(2)) * _e_ * (x)**(Integer(3)))) * ((Symbol('q') * ((_B_)**(Integer(2)) + (Integer(-1) * (Integer(4) * _A_ * _C_)))))**(Integer(-1)))))))),
        module_name='1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p',
        rule_number=12,
    ),
    # Rule 13
    RubiRulePattern(
        pattern=Int((x**2*_C_ + _A_)/(x**4*_e_ + x**3*_d_ + x**2*_c_ + x*_b_ + a_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _A_, _C_], x), EqQ(_A_*_d_ + _C_*_b_, 0), EqQ(-_A_**2*_e_ + _C_**2*a_, 0), NegQ(_C_*(-8*_A_*_e_**2 + _C_*(-4*_c_*_e_ + _d_**2))),),
        replacement=With(List(Set(Symbol('q'), sympy.root(((Integer(-1) * _C_) * ((Integer(-8) * _A_ * (_e_)**(Integer(2))) + (_C_ * ((_d_)**(Integer(2)) + (Integer(-1) * (Integer(4) * _c_ * _e_)))))), Integer(2)))), ((Integer(2) * (_C_)**(Integer(2)) * (Symbol('q'))**(Integer(-1)) * sympy.atan((((_C_ * _d_) + (Integer(2) * _C_ * _e_ * x)) * (Symbol('q'))**(Integer(-1))))) + (Integer(-1) * (Integer(2) * (_C_)**(Integer(2)) * (Symbol('q'))**(Integer(-1)) * sympy.atan(((Integer(-1) * _C_) * (((Integer(-1) * _A_) * _d_) + (Integer(2) * ((_c_ * _C_) + (_A_ * _e_)) * x) + (Integer(2) * _C_ * _d_ * (x)**(Integer(2))) + (Integer(2) * _C_ * _e_ * (x)**(Integer(3)))) * ((_A_ * Symbol('q')))**(Integer(-1)))))))),
        module_name='1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p',
        rule_number=13,
    ),
    # Rule 14
    RubiRulePattern(
        pattern=Int(P4_**p_, x),
        constraints=(FreeQ(p_, x), PolyQ(P4_, x, 4), IntegerQ(2*p_), Not(IGtQ(p_, 0)), NeQ(Coeff(P4_, x, 0), 0), NeQ(Coeff(P4_, x, 1), 0), EqQ(8*Coeff(P4_, x, 0)**2*Coeff(P4_, x, 3) - 4*Coeff(P4_, x, 0)*Coeff(P4_, x, 1)*Coeff(P4_, x, 2) + Coeff(P4_, x, 1)**3, 0),),
        replacement=With(List(Set(Symbol('a'), Coeff(P4_, x, Integer(0))), Set(Symbol('b'), Coeff(P4_, x, Integer(1))), Set(Symbol('c'), Coeff(P4_, x, Integer(2))), Set(Symbol('d'), Coeff(P4_, x, Integer(3))), Set(Symbol('e'), Coeff(P4_, x, Integer(4)))), Star((Integer(-16) * (Symbol('a'))**(Integer(2))), Subst(Int(((((Symbol('b') + (Integer(-1) * (Integer(4) * Symbol('a') * x))))**(Integer(2)))**(Integer(-1)) * ((Symbol('a') * ((Integer(-3) * (Symbol('b'))**(Integer(4))) + (Integer(16) * Symbol('a') * (Symbol('b'))**(Integer(2)) * Symbol('c')) + (Integer(-1) * (Integer(64) * (Symbol('a'))**(Integer(2)) * Symbol('b') * Symbol('d'))) + (Integer(256) * (Symbol('a'))**(Integer(3)) * Symbol('e')) + (Integer(-1) * (Integer(32) * (Symbol('a'))**(Integer(2)) * ((Integer(3) * (Symbol('b'))**(Integer(2))) + (Integer(-1) * (Integer(8) * Symbol('a') * Symbol('c')))) * (x)**(Integer(2)))) + (Integer(256) * (Symbol('a'))**(Integer(4)) * (x)**(Integer(4)))) * (((Symbol('b') + (Integer(-1) * (Integer(4) * Symbol('a') * x))))**(Integer(4)))**(Integer(-1))))**(p_)), x), x, ((Symbol('b') * ((Integer(4) * Symbol('a')))**(Integer(-1))) + (x)**(Integer(-1)))))),
        module_name='1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p',
        rule_number=14,
    ),
    # Rule 15
    RubiRulePattern(
        pattern=Int(x/sqrt(x**4*_e_ + x**2*_c_ + x*_b_ + a_), x),
        constraints=(FreeQ([a_, _b_, _c_, _e_], x), EqQ(100*a_*_e_ + 71*_c_**2, 0), EqQ(-125*_b_**2*_e_ + 1152*_c_**3, 0),),
        replacement=With(List(Set(Symbol('Px'), (((Integer(320))**(Integer(-1)) * ((Integer(33) * (_b_)**(Integer(2)) * _c_) + (Integer(6) * a_ * (_c_)**(Integer(2))) + (Integer(40) * (a_)**(Integer(2)) * _e_))) + (Integer(-1) * (Integer(22) * (Integer(5))**(Integer(-1)) * a_ * _c_ * _e_ * (x)**(Integer(2)))) + (Integer(22) * (Integer(15))**(Integer(-1)) * _b_ * _c_ * _e_ * (x)**(Integer(3))) + ((Integer(4))**(Integer(-1)) * _e_ * ((Integer(5) * (_c_)**(Integer(2))) + (Integer(4) * a_ * _e_)) * (x)**(Integer(4))) + (Integer(4) * (Integer(3))**(Integer(-1)) * _b_ * (_e_)**(Integer(2)) * (x)**(Integer(5))) + (Integer(2) * _c_ * (_e_)**(Integer(2)) * (x)**(Integer(6))) + ((_e_)**(Integer(3)) * (x)**(Integer(8)))))), (((Integer(8) * sympy.root(_e_, Integer(2))))**(Integer(-1)) * sympy.log((Symbol('Px') + (Star(((Integer(8) * sympy.root(_e_, Integer(2)) * x))**(Integer(-1)), D(Symbol('Px'), x)) * sympy.sqrt((a_ + (_b_ * x) + (_c_ * (x)**(Integer(2))) + (_e_ * (x)**(Integer(4)))))))))),
        module_name='1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p',
        rule_number=15,
    ),
    # Rule 16
    RubiRulePattern(
        pattern=Int((x*_B_ + A_)/sqrt(x**4*_e_ + x**3*_d_ + x**2*_c_ + x*_b_ + a_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, A_, _B_], x), EqQ(-4*A_*_e_ + _B_*_d_, 0), EqQ(_d_*(-400*_b_*_e_**2 - 752*_c_*_d_*_e_ + 141*_d_**3) + 16*_e_**2*(100*a_*_e_ + 71*_c_**2), 0), EqQ(144*(-8*_c_*_e_ + 3*_d_**2)**3 + 125*(8*_b_*_e_**2 - 4*_c_*_d_*_e_ + _d_**3)**2, 0),),
        replacement=Star(_B_, Subst(Int(x/sqrt(x**4*_e_ - x**2*(-8*_c_*_e_ + 3*_d_**2)/(8*_e_) + x*(8*_b_*_e_**2 - 4*_c_*_d_*_e_ + _d_**3)/(8*_e_**2) + (256*a_*_e_**3 - 64*_b_*_d_*_e_**2 + 16*_c_*_d_**2*_e_ - 3*_d_**4)/(256*_e_**3)), x), x, x + _d_/(4*_e_))),
        module_name='1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p',
        rule_number=16,
    ),
    # Rule 17
    RubiRulePattern(
        pattern=Int((x**2*_g_ + f_)/((x**2*_d_ + x*_e_ + d_)*sqrt(x**4*_a_ + x**3*_b_ + x**2*_c_ + x*_b_ + a_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, f_, _g_], x), EqQ(-_a_*_e_ + _b_*_d_, 0), EqQ(f_ + _g_, 0), PosQ(_a_**2*(2*_a_ - _c_)),),
        replacement=_a_*f_*atan((x**2*_a_*_b_ + x*(4*_a_**2 - 2*_a_*_c_ + _b_**2) + _a_*_b_)/(2*sqrt(_a_**2*(2*_a_ - _c_))*sqrt(x**4*_a_ + x**3*_b_ + x**2*_c_ + x*_b_ + _a_)))/(_d_*sqrt(_a_**2*(2*_a_ - _c_))),
        module_name='1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p',
        rule_number=17,
    ),
    # Rule 18
    RubiRulePattern(
        pattern=Int((x**2*_g_ + f_)/((x**2*_d_ + x*_e_ + d_)*sqrt(x**4*_a_ + x**3*_b_ + x**2*_c_ + x*_b_ + a_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, f_, _g_], x), EqQ(-_a_*_e_ + _b_*_d_, 0), EqQ(f_ + _g_, 0), NegQ(_a_**2*(2*_a_ - _c_)),),
        replacement=-_a_*f_*atanh((x**2*_a_*_b_ + x*(4*_a_**2 - 2*_a_*_c_ + _b_**2) + _a_*_b_)/(2*sqrt(-_a_**2*(2*_a_ - _c_))*sqrt(x**4*_a_ + x**3*_b_ + x**2*_c_ + x*_b_ + _a_)))/(_d_*sqrt(-_a_**2*(2*_a_ - _c_))),
        module_name='1.3.2 u (a+b x+c x^2+d x^3+e x^4)^p',
        rule_number=18,
    ),

]

# Summary: 18 rules translated, 0 skipped
