# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_rules/codegen/generate.py
# Source: 1.3.4 P(x) Q(x)^p.m
# Module: 1.3.4 P(x) Q(x)^p
#
# This file contains Rubi integration rules as RubiRulePattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Integer, Integral, Lambda, Rational, Symbol, Tuple as SympyTuple, Eq, Ne, Lt, Gt, Le, Ge, log, sqrt, pi, I, oo
from rubi_rules.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (sin, cos, tan, sec, csc, cot, asin, acos, atan, atan2, asec, acsc, acot,
                   sinh, cosh, tanh, sech, csch, coth, asinh, acosh, atanh, asech, acsch, acoth,
                   exp, Abs, diff, denom, frac, floor, root, simplify,
                   elliptic_e, elliptic_f, hyper, appellf1)

from sympy_matching.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_rules.base_objects import Int, RubiRulePattern
from rubi_rules.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, OddQ, EvenQ, NumberQ, NumericQ, AtomQ, MemberQ,
    PositiveQ, NegativeQ, PolynomialQ, TrueQ, FalseQ, MatchQ, PrimeQ, UnsameQ,
    # RUBI-specific constraints
    EqQ, NeQ, IGtQ, ILtQ, IGeQ, ILeQ, GtQ, LtQ, GeQ, LeQ, PosQ, NegQ,
    IntegersQ, HalfIntegerQ, FractionQ, RationalQ, ComplexNumberQ, RealNumberQ,
    FractionOrNegativeQ, SqrtNumberQ, PowerQ, ProductQ, SumQ, NonsumQ,
    IntegerPowerQ, FractionalPowerQ, PolyQ, LinearQ, QuadraticQ, BinomialQ,
    TrinomialQ, LinearMatchQ, QuadraticMatchQ, BinomialMatchQ, TrinomialMatchQ,
    TrigQ, HyperbolicQ, InverseTrigQ, InverseHyperbolicQ, LogQ, ComplexFreeQ,
    InverseFunctionFreeQ, FractionalPowerFreeQ, TrigHyperbolicFreeQ, IntegralFreeQ,
    RationalFunctionQ, AlgebraicFunctionQ, IndependentQ, SimplerQ, SumSimplerQ,
    FunctionOfQ, PiecewiseLinearQ, ExpressionEqQ,
    IntLinearQ, IntBinomialQ, IntQuadraticQ,
    MonomialQ, LinearPairQ,
    GeneralizedBinomialQ, GeneralizedBinomialMatchQ,
    GeneralizedTrinomialQ, GeneralizedTrinomialMatchQ,
    NiceSqrtQ, SimplerSqrtQ, FractionalPowerFactorQ,
    SumBaseQ, InverseFunctionQ, InertTrigQ, InertTrigFreeQ,
    CalculusFreeQ, QuotientOfLinearsQ,
    PowerOfLinearQ, PowerOfLinearMatchQ,
    FunctionOfExponentialQ,
    KnownSineIntegrandQ, KnownSecantIntegrandQ,
    KnownTangentIntegrandQ, KnownCotangentIntegrandQ,
    EulerIntegrandQ, SubstForFractionalPowerQ,
    PerfectSquareQ, PolynomialInQ, FunctionOfTrigOfLinearQ,
    SimplerIntegrandQ, PseudoBinomialPairQ, QuadraticProductQ,
    EveryQ, TrigSimplifyQ, EqM, TryPureTanSubst,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

A_ = WildSymbol('A')
_B_ = WildSymbol('B', optional_value=IDENTITY_ELEMENT)
B_ = WildSymbol('B')
Pm_ = WildSymbol('Pm')
Pn_ = WildSymbol('Pn')
Qn_ = WildSymbol('Qn')
Rn_ = WildSymbol('Rn')
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
_f_ = WildSymbol('f', optional_value=IDENTITY_ELEMENT)
f_ = WildSymbol('f')
_g_ = WildSymbol('g', optional_value=IDENTITY_ELEMENT)
g_ = WildSymbol('g')
_h_ = WildSymbol('h', optional_value=IDENTITY_ELEMENT)
h_ = WildSymbol('h')
_k_ = WildSymbol('k', optional_value=IDENTITY_ELEMENT)
k_ = WildSymbol('k')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')
n2_ = WildSymbol('n2')
_p_ = WildSymbol('p', optional_value=IDENTITY_ELEMENT)
p_ = WildSymbol('p')
_q_ = WildSymbol('q', optional_value=IDENTITY_ELEMENT)
q_ = WildSymbol('q')
_r_ = WildSymbol('r', optional_value=IDENTITY_ELEMENT)
r_ = WildSymbol('r')
u_ = WildSymbol('u')
v_ = WildSymbol('v')

RULES = [
    # Rule 1
    RubiRulePattern(
        pattern=Int(Pn_**_p_*(x*_h_ + g_)**_m_, x),
        constraints=(FreeQ([g_, _h_, _m_, _p_], x), PolyQ(Pn_, x), BinomialQ(ReplaceAll(Pn_, Rule(x, (x - g_)/_h_)), x),),
        replacement=With(List(Set(Symbol('Px'), ReplaceAll(Pn_, Rule(x, ((x + (Integer(-1) * g_)) * (_h_)**(Integer(-1))))))), ((sympy.Function('h')(Symbol('Star')))**(Integer(-1)) * Subst(Int(((x)**(_m_) * (ExpandToSum(Symbol('Px'), x))**(_p_)), x), x, (g_ + (_h_ * x))))),
        module_name='1.3.4 P(x) Q(x)^p',
        rule_number=1,
    ),
    # Rule 2: SKIPPED - ValueError: Non-string function head ['Coeff', 'u', 'x', '1'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 3
    RubiRulePattern(
        pattern=Int(Pn_**_p_*Qn_**_q_*(x*_h_ + g_)**_m_, x),
        constraints=(FreeQ([g_, _h_, _m_, _p_, _q_], x), PolyQ(Pn_, x), PolyQ(Qn_, x), EqQ(Expon(Pn_, x), Expon(Qn_, x)), BinomialQ(ReplaceAll(Pn_, Rule(x, (x - g_)/_h_)), x), BinomialQ(ReplaceAll(Qn_, Rule(x, (x - g_)/_h_)), x),),
        replacement=With(List(Set(Symbol('Px'), ReplaceAll(Pn_, Rule(x, ((x + (Integer(-1) * g_)) * (_h_)**(Integer(-1)))))), Set(Symbol('Qx'), ReplaceAll(Qn_, Rule(x, ((x + (Integer(-1) * g_)) * (_h_)**(Integer(-1))))))), ((sympy.Function('h')(Symbol('Star')))**(Integer(-1)) * Subst(Int(((x)**(_m_) * (ExpandToSum(Symbol('Px'), x))**(_p_) * (ExpandToSum(Symbol('Qx'), x))**(_q_)), x), x, (g_ + (_h_ * x))))),
        module_name='1.3.4 P(x) Q(x)^p',
        rule_number=3,
    ),
    # Rule 4: SKIPPED - ValueError: Non-string function head ['Coeff', 'u', 'x', '1'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 5
    RubiRulePattern(
        pattern=Int(Pn_**_p_*Qn_**_q_*Rn_**_r_*(x*_h_ + g_)**_m_, x),
        constraints=(FreeQ([g_, _h_, _m_, _p_, _q_, _r_], x), PolyQ(Pn_, x), PolyQ(Qn_, x), PolyQ(Rn_, x), EqQ(Expon(Pn_, x), Expon(Qn_, x)), EqQ(Expon(Pn_, x), Expon(Rn_, x)), BinomialQ(ReplaceAll(Pn_, Rule(x, (x - g_)/_h_)), x), BinomialQ(ReplaceAll(Qn_, Rule(x, (x - g_)/_h_)), x), BinomialQ(ReplaceAll(Rn_, Rule(x, (x - g_)/_h_)), x),),
        replacement=With(List(Set(Symbol('Px'), ReplaceAll(Pn_, Rule(x, ((x + (Integer(-1) * g_)) * (_h_)**(Integer(-1)))))), Set(Symbol('Qx'), ReplaceAll(Qn_, Rule(x, ((x + (Integer(-1) * g_)) * (_h_)**(Integer(-1)))))), Set(Symbol('Rx'), ReplaceAll(Rn_, Rule(x, ((x + (Integer(-1) * g_)) * (_h_)**(Integer(-1))))))), ((sympy.Function('h')(Symbol('Star')))**(Integer(-1)) * Subst(Int(((x)**(_m_) * (ExpandToSum(Symbol('Px'), x))**(_p_) * (ExpandToSum(Symbol('Qx'), x))**(_q_) * (ExpandToSum(Symbol('Rx'), x))**(_r_)), x), x, (g_ + (_h_ * x))))),
        module_name='1.3.4 P(x) Q(x)^p',
        rule_number=5,
    ),
    # Rule 6: SKIPPED - ValueError: Non-string function head ['Coeff', 'u', 'x', '1'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 7
    RubiRulePattern(
        pattern=Int(Pn_**_p_*(x*_h_ + g_)**_m_, x),
        constraints=(FreeQ([g_, _h_, _m_, _p_], x), PolyQ(Pn_, x), BinomialQ(ReplaceAll(Pn_, Rule(x, (x - g_)/_h_)), x),),
        replacement=With(List(Set(Symbol('Px'), ReplaceAll(Pn_, Rule(x, ((x + (Integer(-1) * g_)) * (_h_)**(Integer(-1))))))), ((sympy.Function('h')(Symbol('Star')))**(Integer(-1)) * Subst(Int(((x)**(_m_) * (ExpandToSum(Symbol('Px'), x))**(_p_)), x), x, (g_ + (_h_ * x))))),
        module_name='1.3.4 P(x) Q(x)^p',
        rule_number=7,
    ),
    # Rule 8: SKIPPED - ValueError: Non-string function head ['Coeff', 'u', 'x', '1'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 9
    RubiRulePattern(
        pattern=Int(Pn_**_p_*(x*_h_ + g_)**_m_, x),
        constraints=(FreeQ([g_, _h_, _m_, _p_], x), PolyQ(Pn_, x), TrinomialQ(ReplaceAll(Pn_, Rule(x, (x - g_)/_h_)), x),),
        replacement=With(List(Set(Symbol('Px'), ReplaceAll(Pn_, Rule(x, ((x + (Integer(-1) * g_)) * (_h_)**(Integer(-1))))))), ((sympy.Function('h')(Symbol('Star')))**(Integer(-1)) * Subst(Int(((x)**(_m_) * (ExpandToSum(Symbol('Px'), x))**(_p_)), x), x, (g_ + (_h_ * x))))),
        module_name='1.3.4 P(x) Q(x)^p',
        rule_number=9,
    ),
    # Rule 10: SKIPPED - ValueError: Non-string function head ['Coeff', 'u', 'x', '1'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 11
    RubiRulePattern(
        pattern=Int(sqrt(v_)/(x**4*_e_ + d_), x),
        constraints=(FreeQ([d_, _e_], x), PolyQ(v_, x**2, 2), EqQ(d_*Coeff(v_, x, 4) + _e_*Coeff(v_, x, 0), 0), PosQ(Coeff(v_, x, 0)*Coeff(v_, x, 4)),),
        replacement=With(List(Set(Symbol('a'), Coeff(v_, x, Integer(0))), Set(Symbol('b'), Coeff(v_, x, Integer(2))), Set(Symbol('c'), Coeff(v_, x, Integer(4)))), (Symbol('a') * (sympy.Function('d')(Symbol('Star')))**(Integer(-1)) * Subst(Int(((Integer(1) + (Integer(-1) * (Integer(2) * Symbol('b') * (x)**(Integer(2)))) + (((Symbol('b'))**(Integer(2)) + (Integer(-1) * (Integer(4) * Symbol('a') * Symbol('c')))) * (x)**(Integer(4)))))**(Integer(-1)), x), x, (x * (sympy.sqrt(v_))**(Integer(-1)))))),
        module_name='1.3.4 P(x) Q(x)^p',
        rule_number=11,
    ),
    # Rule 12
    RubiRulePattern(
        pattern=Int(sqrt(x**4*_c_ + x**2*_b_ + a_)/(x**4*_e_ + d_), x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _e_], x), EqQ(a_*_e_ + _c_*d_, 0), NegQ(a_*_c_),),
        replacement=With(List(Set(Symbol('q'), sympy.sqrt(((_b_)**(Integer(2)) + (Integer(-1) * (Integer(4) * a_ * _c_)))))), (((Integer(-1) * a_) * sympy.sqrt((_b_ + Symbol('q'))) * ((Integer(2) * sympy.sqrt(Integer(2)) * sympy.root(((Integer(-1) * a_) * _c_), Integer(2)) * d_))**(Integer(-1)) * sympy.atan((sympy.sqrt((_b_ + Symbol('q'))) * x * (_b_ + (Integer(-1) * Symbol('q')) + (Integer(2) * _c_ * (x)**(Integer(2)))) * ((Integer(2) * sympy.sqrt(Integer(2)) * sympy.root(((Integer(-1) * a_) * _c_), Integer(2)) * sympy.sqrt((a_ + (_b_ * (x)**(Integer(2))) + (_c_ * (x)**(Integer(4)))))))**(Integer(-1))))) + (a_ * sympy.sqrt(((Integer(-1) * _b_) + Symbol('q'))) * ((Integer(2) * sympy.sqrt(Integer(2)) * sympy.root(((Integer(-1) * a_) * _c_), Integer(2)) * d_))**(Integer(-1)) * sympy.atanh((sympy.sqrt(((Integer(-1) * _b_) + Symbol('q'))) * x * (_b_ + Symbol('q') + (Integer(2) * _c_ * (x)**(Integer(2)))) * ((Integer(2) * sympy.sqrt(Integer(2)) * sympy.root(((Integer(-1) * a_) * _c_), Integer(2)) * sympy.sqrt((a_ + (_b_ * (x)**(Integer(2))) + (_c_ * (x)**(Integer(4)))))))**(Integer(-1))))))),
        module_name='1.3.4 P(x) Q(x)^p',
        rule_number=12,
    ),
    # Rule 13: SKIPPED - ValueError: Non-string function head ['Plus', 'n', '-1'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 14: SKIPPED - ValueError: Non-string function head ['Plus', 'm', '1'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 15
    RubiRulePattern(
        pattern=Int((x**4*_c_ + x**2*_b_ + a_)/(x**6*_g_ + x**4*_f_ + x**2*_e_ + d_), x),
        constraints=(FreeQ([a_, _b_, _c_, d_, _e_, _f_, _g_], x), EqQ(-12*a_**3*_g_**2 + a_**2*_c_*_f_**2 + 2*a_*_b_*_g_*(a_*_f_ + 3*_c_*d_) + 9*_c_**3*d_**2 - _c_*d_*_f_*(6*a_*_c_ + _b_**2), 0), EqQ(a_**3*_c_*_f_**2*_g_ + 2*a_**3*_g_**2*(-6*a_*_g_ + _b_*_f_) - 3*a_**2*_c_**2*d_*_f_*_g_ + 3*_c_**4*d_**2*_e_ - _c_**3*d_*(-12*a_*d_*_g_ + a_*_e_*_f_ + 2*_b_*d_*_f_), 0), NeQ(-a_*_f_ + 3*_c_*d_, 0), NeQ(-2*a_**2*_g_ + _b_*_c_*d_, 0), NeQ(4*a_**2*_g_ - a_*_b_*_f_ + _b_*_c_*d_, 0), PosQ((12*a_**2*_g_**2 - a_*_c_*_f_**2 + _f_*(-2*a_*_b_*_g_ + 3*_c_**2*d_))/(_c_*_g_*(-a_*_f_ + 3*_c_*d_))),),
        replacement=With(List(Set(Symbol('q'), sympy.root(((((Integer(-1) * a_) * _c_ * (_f_)**(Integer(2))) + (Integer(12) * (a_)**(Integer(2)) * (_g_)**(Integer(2))) + (_f_ * ((Integer(3) * (_c_)**(Integer(2)) * d_) + (Integer(-1) * (Integer(2) * a_ * _b_ * _g_))))) * ((_c_ * _g_ * ((Integer(3) * _c_ * d_) + (Integer(-1) * (a_ * _f_)))))**(Integer(-1))), Integer(2))), Set(Symbol('r'), sympy.root((((a_ * _c_ * (_f_)**(Integer(2))) + (Integer(4) * _g_ * ((_b_ * _c_ * d_) + ((a_)**(Integer(2)) * _g_))) + (Integer(-1) * (_f_ * ((Integer(3) * (_c_)**(Integer(2)) * d_) + (Integer(2) * a_ * _b_ * _g_))))) * ((_c_ * _g_ * ((Integer(3) * _c_ * d_) + (Integer(-1) * (a_ * _f_)))))**(Integer(-1))), Integer(2)))), ((_c_ * ((_g_ * Symbol('q')))**(Integer(-1)) * sympy.atan(((Symbol('r') + (Integer(2) * x)) * (Symbol('q'))**(Integer(-1))))) + (Integer(-1) * (_c_ * ((_g_ * Symbol('q')))**(Integer(-1)) * sympy.atan(((Symbol('r') + (Integer(-1) * (Integer(2) * x))) * (Symbol('q'))**(Integer(-1)))))) + (Integer(-1) * (_c_ * ((_g_ * Symbol('q')))**(Integer(-1)) * sympy.atan((((Integer(3) * _c_ * d_) + (Integer(-1) * (a_ * _f_))) * x * ((_g_ * Symbol('q') * ((_b_ * _c_ * d_) + (Integer(-1) * (Integer(2) * (a_)**(Integer(2)) * _g_))) * ((_b_ * _c_ * d_) + (Integer(-1) * (a_ * _b_ * _f_)) + (Integer(4) * (a_)**(Integer(2)) * _g_))))**(Integer(-1)) * ((_b_ * (_c_)**(Integer(2)) * d_ * _f_) + (Integer(-1) * (a_ * (_b_)**(Integer(2)) * _f_ * _g_)) + (Integer(-1) * (Integer(2) * (a_)**(Integer(2)) * _c_ * _f_ * _g_)) + (Integer(6) * (a_)**(Integer(2)) * _b_ * (_g_)**(Integer(2))) + (_c_ * ((Integer(3) * (_c_)**(Integer(2)) * d_ * _f_) + (Integer(-1) * (a_ * _c_ * (_f_)**(Integer(2)))) + (Integer(-1) * (_b_ * _c_ * d_ * _g_)) + (Integer(2) * (a_)**(Integer(2)) * (_g_)**(Integer(2)))) * (x)**(Integer(2))) + ((_c_)**(Integer(2)) * _g_ * ((Integer(3) * _c_ * d_) + (Integer(-1) * (a_ * _f_))) * (x)**(Integer(4)))))))))),
        module_name='1.3.4 P(x) Q(x)^p',
        rule_number=15,
    ),
    # Rule 16
    RubiRulePattern(
        pattern=Int((x**4*_c_ + a_)/(x**6*_g_ + x**4*_f_ + x**2*_e_ + d_), x),
        constraints=(FreeQ([a_, _c_, d_, _e_, _f_, _g_], x), EqQ(-12*a_**3*_g_**2 + a_**2*_c_*_f_**2 - 6*a_*_c_**2*d_*_f_ + 9*_c_**3*d_**2, 0), EqQ(-12*a_**4*_g_**3 + a_**3*_c_*_f_**2*_g_ - 3*a_**2*_c_**2*d_*_f_*_g_ - a_*_c_**3*d_*(-12*d_*_g_ + _e_*_f_) + 3*_c_**4*d_**2*_e_, 0), NeQ(-a_*_f_ + 3*_c_*d_, 0), PosQ((12*a_**2*_g_**2 - a_*_c_*_f_**2 + 3*_c_**2*d_*_f_)/(_c_*_g_*(-a_*_f_ + 3*_c_*d_))),),
        replacement=With(List(Set(Symbol('q'), sympy.root(((((Integer(-1) * a_) * _c_ * (_f_)**(Integer(2))) + (Integer(12) * (a_)**(Integer(2)) * (_g_)**(Integer(2))) + (Integer(3) * _f_ * (_c_)**(Integer(2)) * d_)) * ((_c_ * _g_ * ((Integer(3) * _c_ * d_) + (Integer(-1) * (a_ * _f_)))))**(Integer(-1))), Integer(2))), Set(Symbol('r'), sympy.root((((a_ * _c_ * (_f_)**(Integer(2))) + (Integer(4) * (a_)**(Integer(2)) * (_g_)**(Integer(2))) + (Integer(-1) * (Integer(3) * (_c_)**(Integer(2)) * d_ * _f_))) * ((_c_ * _g_ * ((Integer(3) * _c_ * d_) + (Integer(-1) * (a_ * _f_)))))**(Integer(-1))), Integer(2)))), ((_c_ * ((_g_ * Symbol('q')))**(Integer(-1)) * sympy.atan(((Symbol('r') + (Integer(2) * x)) * (Symbol('q'))**(Integer(-1))))) + (Integer(-1) * (_c_ * ((_g_ * Symbol('q')))**(Integer(-1)) * sympy.atan(((Symbol('r') + (Integer(-1) * (Integer(2) * x))) * (Symbol('q'))**(Integer(-1)))))) + (Integer(-1) * (_c_ * ((_g_ * Symbol('q')))**(Integer(-1)) * sympy.atan(((_c_ * ((Integer(3) * _c_ * d_) + (Integer(-1) * (a_ * _f_))) * x * ((Integer(2) * (a_)**(Integer(2)) * _f_ * _g_) + (Integer(-1) * (((Integer(3) * (_c_)**(Integer(2)) * d_ * _f_) + (Integer(-1) * (a_ * _c_ * (_f_)**(Integer(2)))) + (Integer(2) * (a_)**(Integer(2)) * (_g_)**(Integer(2)))) * (x)**(Integer(2)))) + (Integer(-1) * (_c_ * ((Integer(3) * _c_ * d_) + (Integer(-1) * (a_ * _f_))) * _g_ * (x)**(Integer(4)))))) * ((Integer(8) * (a_)**(Integer(4)) * (_g_)**(Integer(3)) * Symbol('q')))**(Integer(-1)))))))),
        module_name='1.3.4 P(x) Q(x)^p',
        rule_number=16,
    ),
    # Rule 17: SKIPPED - ValueError: Non-string function head ['Simplify', ['Plus', 'Pm', ['Times', '-1', ['Times', ['Coeff', 'Pm', 'x', 'm'], ['D', 'Qn', 'x'], ['Power', ['Times', 'n', ['Coeff', 'Qn', 'x', 'n']], '-1']]]]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 18: SKIPPED - ValueError: Non-string function head ['Simplify', ['Plus', 'Pm', ['Times', '-1', ['Times', ['Coeff', 'Pm', 'x', 'm'], ['D', 'Qn', 'x'], ['Power', ['Times', 'n', ['Coeff', 'Qn', 'x', 'n']], '-1']]]]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 19: SKIPPED - ValueError: Non-string function head ['Times', 'n', ['Coeff', 'Qn', 'x', 'n']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 20: SKIPPED - ValueError: Non-string function head ['Times', 'n', ['Coeff', 'Qn', 'x', 'n']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 21: SKIPPED - ValueError: Non-string function head ['Times', ['Plus', 'm', ['Times', 'n', 'p'], '1'], ['Coeff', 'Qn', 'x', 'n']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.

]

# Summary: 9 rules translated, 12 skipped
