# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_rules/codegen/generate.py
# Source: 4.1.1.3 (g tan)^p (a+b sin)^m.m
# Module: 4.1.1.3 (g tan)^p (a+b sin)^m
#
# This file contains Rubi integration rules as RubiRulePattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Integer, Integral, Lambda, Rational, Symbol, Tuple as SympyTuple, Eq, Ne, Lt, Gt, Le, Ge, log, sqrt, pi, I, oo
from rubi_rules.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (sin, cos, tan, sec, csc, cot, asin, acos, atan, atan2, asec, acsc, acot,
                   sinh, cosh, tanh, sech, csch, coth, asinh, acosh, atanh, asech, acsch, acoth,
                   exp, Abs, diff, denom, frac, floor, root, simplify,
                   elliptic_e, elliptic_f, hyper, appellf1)

from sympy_matching.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_rules.base_objects import Int, RubiRulePattern
from rubi_rules.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, OddQ, EvenQ, NumberQ, NumericQ, AtomQ, MemberQ,
    PositiveQ, NegativeQ, PolynomialQ, TrueQ, FalseQ, MatchQ, PrimeQ, UnsameQ,
    # RUBI-specific constraints
    EqQ, NeQ, IGtQ, ILtQ, IGeQ, ILeQ, GtQ, LtQ, GeQ, LeQ, PosQ, NegQ,
    IntegersQ, HalfIntegerQ, FractionQ, RationalQ, ComplexNumberQ, RealNumberQ,
    FractionOrNegativeQ, SqrtNumberQ, PowerQ, ProductQ, SumQ, NonsumQ,
    IntegerPowerQ, FractionalPowerQ, PolyQ, LinearQ, QuadraticQ, BinomialQ,
    TrinomialQ, LinearMatchQ, QuadraticMatchQ, BinomialMatchQ, TrinomialMatchQ,
    TrigQ, HyperbolicQ, InverseTrigQ, InverseHyperbolicQ, LogQ, ComplexFreeQ,
    InverseFunctionFreeQ, FractionalPowerFreeQ, TrigHyperbolicFreeQ, IntegralFreeQ,
    RationalFunctionQ, AlgebraicFunctionQ, IndependentQ, SimplerQ, SumSimplerQ,
    FunctionOfQ, PiecewiseLinearQ, ExpressionEqQ,
    IntLinearQ, IntBinomialQ, IntQuadraticQ,
    MonomialQ, LinearPairQ,
    GeneralizedBinomialQ, GeneralizedBinomialMatchQ,
    GeneralizedTrinomialQ, GeneralizedTrinomialMatchQ,
    NiceSqrtQ, SimplerSqrtQ, FractionalPowerFactorQ,
    SumBaseQ, InverseFunctionQ, InertTrigQ, InertTrigFreeQ,
    CalculusFreeQ, QuotientOfLinearsQ,
    PowerOfLinearQ, PowerOfLinearMatchQ,
    FunctionOfExponentialQ,
    KnownSineIntegrandQ, KnownSecantIntegrandQ,
    KnownTangentIntegrandQ, KnownCotangentIntegrandQ,
    EulerIntegrandQ, SubstForFractionalPowerQ,
    PerfectSquareQ, PolynomialInQ, FunctionOfTrigOfLinearQ,
    SimplerIntegrandQ, PseudoBinomialPairQ, QuadraticProductQ,
    EveryQ, TrigSimplifyQ, EqM, TryPureTanSubst,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
_f_ = WildSymbol('f', optional_value=IDENTITY_ELEMENT)
f_ = WildSymbol('f')
_g_ = WildSymbol('g', optional_value=IDENTITY_ELEMENT)
g_ = WildSymbol('g')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_p_ = WildSymbol('p', optional_value=IDENTITY_ELEMENT)
p_ = WildSymbol('p')

RULES = [
    # Rule 1
    RubiRulePattern(
        pattern=Int((_g_*tan(x*_f_ + _e_))**_p_/(a_ + _b_*sin(x*_f_ + _e_)), x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, _g_, _p_], x), EqQ(a_**2 - _b_**2, 0), NeQ(_p_, -1),),
        replacement=-Int((_g_*tan(x*_f_ + _e_))**(_p_ + 1)*sec(x*_f_ + _e_), x)/(_b_*_g_) + Int((_g_*tan(x*_f_ + _e_))**_p_*sec(x*_f_ + _e_)**2, x)/a_,
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=1,
    ),
    # Rule 2
    RubiRulePattern(
        pattern=Int((a_ + _b_*sin(x*_f_ + _e_))**_m_*tan(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, _m_], x), EqQ(a_**2 - _b_**2, 0), IntegerQ(_p_/2 + sympy.S.Half),),
        replacement=Subst(Int(x**_p_*(-x + a_)**(-_p_/2 + sympy.S(-1)/2)*(x + a_)**(_m_ - _p_/2 + sympy.S(-1)/2), x), x, _b_*sin(x*_f_ + _e_))/_f_,
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=2,
    ),
    # Rule 3
    RubiRulePattern(
        pattern=Int((a_ + _b_*sin(x*_f_ + _e_))**_m_*tan(x*_f_ + _e_)**p_, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_], x), EqQ(a_**2 - _b_**2, 0), IntegersQ(_m_, p_), EqQ(p_, 2*_m_),),
        replacement=a_**p_*Int(sin(x*_f_ + _e_)**p_/(a_ - _b_*sin(x*_f_ + _e_))**_m_, x),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=3,
    ),
    # Rule 4
    RubiRulePattern(
        pattern=Int((a_ + _b_*sin(x*_f_ + _e_))**m_*tan(x*_f_ + _e_)**p_, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_], x), EqQ(a_**2 - _b_**2, 0), IntegersQ(m_, p_/2), Or(LtQ(p_, 0), GtQ(m_ - p_/2, 0)),),
        replacement=a_**p_*Int(ExpandIntegrand((a_ + _b_*sin(x*_f_ + _e_))**(m_ - p_/2)*sin(x*_f_ + _e_)**p_/(a_ - _b_*sin(x*_f_ + _e_))**(p_/2), x), x),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=4,
    ),
    # Rule 5
    RubiRulePattern(
        pattern=Int((_g_*tan(x*_f_ + _e_))**_p_*(a_ + _b_*sin(x*_f_ + _e_))**_m_, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, _g_, _p_], x), EqQ(a_**2 - _b_**2, 0), IGtQ(_m_, 0),),
        replacement=Int(ExpandIntegrand((_g_*tan(x*_f_ + _e_))**_p_, (a_ + _b_*sin(x*_f_ + _e_))**_m_, x), x),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=5,
    ),
    # Rule 6
    RubiRulePattern(
        pattern=Int((_g_*tan(x*_f_ + _e_))**_p_*(a_ + _b_*sin(x*_f_ + _e_))**m_, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, _g_, _p_], x), EqQ(a_**2 - _b_**2, 0), ILtQ(m_, 0),),
        replacement=a_**(2*m_)*Int(ExpandIntegrand((_g_*tan(x*_f_ + _e_))**_p_/sec(x*_f_ + _e_)**m_, (a_*sec(x*_f_ + _e_) - _b_*tan(x*_f_ + _e_))**(-m_), x), x),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=6,
    ),
    # Rule 7
    RubiRulePattern(
        pattern=Int((a_ + _b_*sin(x*_f_ + _e_))**m_*tan(x*_f_ + _e_)**2, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_], x), EqQ(a_**2 - _b_**2, 0), Not(IntegerQ(m_)), LtQ(m_, 0),),
        replacement=_b_*(a_ + _b_*sin(x*_f_ + _e_))**m_/(a_*_f_*(2*m_ - 1)*cos(x*_f_ + _e_)) - Int((a_ + _b_*sin(x*_f_ + _e_))**(m_ + 1)*(a_*m_ - _b_*(2*m_ - 1)*sin(x*_f_ + _e_))/cos(x*_f_ + _e_)**2, x)/(a_**2*(2*m_ - 1)),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=7,
    ),
    # Rule 8
    RubiRulePattern(
        pattern=Int((a_ + _b_*sin(x*_f_ + _e_))**m_*tan(x*_f_ + _e_)**2, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, m_], x), EqQ(a_**2 - _b_**2, 0), Not(IntegerQ(m_)), Not(LtQ(m_, 0)),),
        replacement=Int((a_ + _b_*sin(x*_f_ + _e_))**m_*(a_*sin(x*_f_ + _e_) + _b_*(m_ + 1))/cos(x*_f_ + _e_)**2, x)/(_b_*m_) - (a_ + _b_*sin(x*_f_ + _e_))**(m_ + 1)/(_b_*_f_*m_*cos(x*_f_ + _e_)),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=8,
    ),
    # Rule 9
    RubiRulePattern(
        pattern=Int((a_ + _b_*sin(x*_f_ + _e_))**m_*tan(x*_f_ + _e_)**4, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, m_], x), EqQ(a_**2 - _b_**2, 0), IntegerQ(m_ + sympy.S(-1)/2),),
        replacement=-Int((1 - 2*sin(x*_f_ + _e_)**2)*(a_ + _b_*sin(x*_f_ + _e_))**m_/cos(x*_f_ + _e_)**4, x) + Int((a_ + _b_*sin(x*_f_ + _e_))**m_, x),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=9,
    ),
    # Rule 10
    RubiRulePattern(
        pattern=Int((a_ + _b_*sin(x*_f_ + _e_))**m_/tan(x*_f_ + _e_)**2, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_], x), EqQ(a_**2 - _b_**2, 0), IntegerQ(m_ + sympy.S(-1)/2), LtQ(m_, -1),),
        replacement=Int((a_ + _b_*sin(x*_f_ + _e_))**(m_ + 1)*(-a_*(m_ + 1)*sin(x*_f_ + _e_) + _b_*m_)/sin(x*_f_ + _e_), x)/_b_**2 - (a_ + _b_*sin(x*_f_ + _e_))**(m_ + 1)/(a_*_f_*tan(x*_f_ + _e_)),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=10,
    ),
    # Rule 11
    RubiRulePattern(
        pattern=Int((a_ + _b_*sin(x*_f_ + _e_))**_m_/tan(x*_f_ + _e_)**2, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, _m_], x), EqQ(a_**2 - _b_**2, 0), IntegerQ(_m_ + sympy.S(-1)/2), Not(LtQ(_m_, -1)),),
        replacement=-(a_ + _b_*sin(x*_f_ + _e_))**_m_/(_f_*tan(x*_f_ + _e_)) + Int((a_ + _b_*sin(x*_f_ + _e_))**_m_*(-a_*(_m_ + 1)*sin(x*_f_ + _e_) + _b_*_m_)/sin(x*_f_ + _e_), x)/a_,
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=11,
    ),
    # Rule 12
    RubiRulePattern(
        pattern=Int((a_ + _b_*sin(x*_f_ + _e_))**m_/tan(x*_f_ + _e_)**4, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_], x), EqQ(a_**2 - _b_**2, 0), IntegerQ(m_ + sympy.S(-1)/2), LtQ(m_, -1),),
        replacement=-2*Int((a_ + _b_*sin(x*_f_ + _e_))**(m_ + 2)/sin(x*_f_ + _e_)**3, x)/(a_*_b_) + Int((a_ + _b_*sin(x*_f_ + _e_))**(m_ + 2)*(sin(x*_f_ + _e_)**2 + 1)/sin(x*_f_ + _e_)**4, x)/a_**2,
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=12,
    ),
    # Rule 13
    RubiRulePattern(
        pattern=Int((a_ + _b_*sin(x*_f_ + _e_))**m_/tan(x*_f_ + _e_)**4, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, m_], x), EqQ(a_**2 - _b_**2, 0), IntegerQ(m_ + sympy.S(-1)/2), Not(LtQ(m_, -1)),),
        replacement=Int((1 - 2*sin(x*_f_ + _e_)**2)*(a_ + _b_*sin(x*_f_ + _e_))**m_/sin(x*_f_ + _e_)**4, x) + Int((a_ + _b_*sin(x*_f_ + _e_))**m_, x),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=13,
    ),
    # Rule 14
    RubiRulePattern(
        pattern=Int((a_ + _b_*sin(x*_f_ + _e_))**m_*tan(x*_f_ + _e_)**p_, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, m_], x), EqQ(a_**2 - _b_**2, 0), Not(IntegerQ(m_)), IntegerQ(p_/2),),
        replacement=sqrt(a_ - _b_*sin(x*_f_ + _e_))*sqrt(a_ + _b_*sin(x*_f_ + _e_))*Subst(Int(x**p_*(-x + a_)**(-p_/2 + sympy.S(-1)/2)*(x + a_)**(m_ - p_/2 + sympy.S(-1)/2), x), x, _b_*sin(x*_f_ + _e_))/(_b_*_f_*cos(x*_f_ + _e_)),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=14,
    ),
    # Rule 15
    RubiRulePattern(
        pattern=Int((_g_*tan(x*_f_ + _e_))**p_*(a_ + _b_*sin(x*_f_ + _e_))**m_, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, _g_, m_, p_], x), EqQ(a_**2 - _b_**2, 0), Not(IntegerQ(m_)), Not(IntegerQ(p_)),),
        replacement=(_b_*sin(x*_f_ + _e_))**(-p_ - 1)*(_g_*tan(x*_f_ + _e_))**(p_ + 1)*(a_ - _b_*sin(x*_f_ + _e_))**(p_/2 + sympy.S.Half)*(a_ + _b_*sin(x*_f_ + _e_))**(p_/2 + sympy.S.Half)*Subst(Int(x**p_*(-x + a_)**(-p_/2 + sympy.S(-1)/2)*(x + a_)**(m_ - p_/2 + sympy.S(-1)/2), x), x, _b_*sin(x*_f_ + _e_))/(_f_*_g_),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=15,
    ),
    # Rule 16
    RubiRulePattern(
        pattern=Int((a_ + _b_*sin(x*_f_ + _e_))**_m_*tan(x*_f_ + _e_)**_p_, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, _m_], x), NeQ(a_**2 - _b_**2, 0), IntegerQ(_p_/2 + sympy.S.Half),),
        replacement=Subst(Int(x**_p_*(x + a_)**_m_*(-x**2 + _b_**2)**(-_p_/2 + sympy.S(-1)/2), x), x, _b_*sin(x*_f_ + _e_))/_f_,
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=16,
    ),
    # Rule 17
    RubiRulePattern(
        pattern=Int((_g_*tan(x*_f_ + _e_))**_p_*(a_ + _b_*sin(x*_f_ + _e_))**_m_, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, _g_, _p_], x), NeQ(a_**2 - _b_**2, 0), IGtQ(_m_, 0),),
        replacement=Int(ExpandIntegrand((_g_*tan(x*_f_ + _e_))**_p_, (a_ + _b_*sin(x*_f_ + _e_))**_m_, x), x),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=17,
    ),
    # Rule 18
    RubiRulePattern(
        pattern=Int((a_ + _b_*sin(x*_f_ + _e_))**m_/tan(x*_f_ + _e_)**2, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, m_], x), NeQ(a_**2 - _b_**2, 0),),
        replacement=Int((1 - sin(x*_f_ + _e_)**2)*(a_ + _b_*sin(x*_f_ + _e_))**m_/sin(x*_f_ + _e_)**2, x),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=18,
    ),
    # Rule 19
    RubiRulePattern(
        pattern=Int((a_ + _b_*sin(x*_f_ + _e_))**m_/tan(x*_f_ + _e_)**4, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_], x), NeQ(a_**2 - _b_**2, 0), LtQ(m_, -1), IntegerQ(2*m_),),
        replacement=-(a_ + _b_*sin(x*_f_ + _e_))**(m_ + 1)*cos(x*_f_ + _e_)/(3*a_*_f_*sin(x*_f_ + _e_)**3) - Int((a_ + _b_*sin(x*_f_ + _e_))**(m_ + 1)*Simp(6*a_**2 + a_*_b_*(m_ + 1)*sin(x*_f_ + _e_) - _b_**2*(m_ - 2)*(m_ - 1) - (3*a_**2 - _b_**2*m_*(m_ - 2))*sin(x*_f_ + _e_)**2, x)/sin(x*_f_ + _e_)**3, x)/(3*a_**2*_b_*(m_ + 1)) - (a_ + _b_*sin(x*_f_ + _e_))**(m_ + 1)*(3*a_**2 + _b_**2*(m_ - 2))*cos(x*_f_ + _e_)/(3*a_**2*_b_*_f_*(m_ + 1)*sin(x*_f_ + _e_)**2),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=19,
    ),
    # Rule 20
    RubiRulePattern(
        pattern=Int((a_ + _b_*sin(x*_f_ + _e_))**m_/tan(x*_f_ + _e_)**4, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, m_], x), NeQ(a_**2 - _b_**2, 0), Not(LtQ(m_, -1)), IntegerQ(2*m_),),
        replacement=-(a_ + _b_*sin(x*_f_ + _e_))**(m_ + 1)*cos(x*_f_ + _e_)/(3*a_*_f_*sin(x*_f_ + _e_)**3) - _b_*(a_ + _b_*sin(x*_f_ + _e_))**(m_ + 1)*(m_ - 2)*cos(x*_f_ + _e_)/(6*a_**2*_f_*sin(x*_f_ + _e_)**2) - Int((a_ + _b_*sin(x*_f_ + _e_))**m_*Simp(8*a_**2 + a_*_b_*m_*sin(x*_f_ + _e_) - _b_**2*(m_ - 2)*(m_ - 1) - (6*a_**2 - _b_**2*m_*(m_ - 2))*sin(x*_f_ + _e_)**2, x)/sin(x*_f_ + _e_)**2, x)/(6*a_**2),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=20,
    ),
    # Rule 21
    RubiRulePattern(
        pattern=Int((a_ + _b_*sin(x*_f_ + _e_))**m_/tan(x*_f_ + _e_)**6, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, m_], x), NeQ(a_**2 - _b_**2, 0), NeQ(m_, 1), IntegerQ(2*m_),),
        replacement=a_*(a_ + _b_*sin(x*_f_ + _e_))**(m_ + 1)*cos(x*_f_ + _e_)/(_b_**2*_f_*m_*(m_ - 1)*sin(x*_f_ + _e_)**3) + (a_ + _b_*sin(x*_f_ + _e_))**(m_ + 1)*cos(x*_f_ + _e_)/(_b_*_f_*m_*sin(x*_f_ + _e_)**2) - (a_ + _b_*sin(x*_f_ + _e_))**(m_ + 1)*cos(x*_f_ + _e_)/(5*a_*_f_*sin(x*_f_ + _e_)**5) - _b_*(a_ + _b_*sin(x*_f_ + _e_))**(m_ + 1)*(m_ - 4)*cos(x*_f_ + _e_)/(20*a_**2*_f_*sin(x*_f_ + _e_)**4) + Int((a_ + _b_*sin(x*_f_ + _e_))**m_*Simp(60*a_**4 - 44*a_**2*_b_**2*m_*(m_ - 1) + a_*_b_*m_*(20*a_**2 - _b_**2*m_*(m_ - 1))*sin(x*_f_ + _e_) + _b_**4*m_*(m_ - 4)*(m_ - 3)*(m_ - 1) - (40*a_**4 - 20*a_**2*_b_**2*(m_ - 1)*(2*m_ + 1) + _b_**4*m_*(m_ - 4)*(m_ - 2)*(m_ - 1))*sin(x*_f_ + _e_)**2, x)/sin(x*_f_ + _e_)**4, x)/(20*a_**2*_b_**2*m_*(m_ - 1)),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=21,
    ),
    # Rule 22
    RubiRulePattern(
        pattern=Int((_g_*tan(x*_f_ + _e_))**p_/(a_ + _b_*sin(x*_f_ + _e_)), x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, _g_], x), NeQ(a_**2 - _b_**2, 0), IntegersQ(2*p_), GtQ(p_, 1),),
        replacement=-a_**2*_g_**2*Int((_g_*tan(x*_f_ + _e_))**(p_ - 2)/(a_ + _b_*sin(x*_f_ + _e_)), x)/(a_**2 - _b_**2) + a_*Int((_g_*tan(x*_f_ + _e_))**p_/sin(x*_f_ + _e_)**2, x)/(a_**2 - _b_**2) - _b_*_g_*Int((_g_*tan(x*_f_ + _e_))**(p_ - 1)/cos(x*_f_ + _e_), x)/(a_**2 - _b_**2),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=22,
    ),
    # Rule 23
    RubiRulePattern(
        pattern=Int((_g_*tan(x*_f_ + _e_))**p_/(a_ + _b_*sin(x*_f_ + _e_)), x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, _g_], x), NeQ(a_**2 - _b_**2, 0), IntegersQ(2*p_), LtQ(p_, -1),),
        replacement=Int((_g_*tan(x*_f_ + _e_))**p_/cos(x*_f_ + _e_)**2, x)/a_ - _b_*Int((_g_*tan(x*_f_ + _e_))**(p_ + 1)/cos(x*_f_ + _e_), x)/(a_**2*_g_) - (a_**2 - _b_**2)*Int((_g_*tan(x*_f_ + _e_))**(p_ + 2)/(a_ + _b_*sin(x*_f_ + _e_)), x)/(a_**2*_g_**2),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=23,
    ),
    # Rule 24
    RubiRulePattern(
        pattern=Int(sqrt(_g_*tan(x*_f_ + _e_))/(a_ + _b_*sin(x*_f_ + _e_)), x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, _g_], x), NeQ(a_**2 - _b_**2, 0),),
        replacement=sqrt(_g_*tan(x*_f_ + _e_))*Int(sqrt(sin(x*_f_ + _e_))/((a_ + _b_*sin(x*_f_ + _e_))*sqrt(cos(x*_f_ + _e_))), x)*sqrt(cos(x*_f_ + _e_))/sqrt(sin(x*_f_ + _e_)),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=24,
    ),
    # Rule 25
    RubiRulePattern(
        pattern=Int(1/(sqrt(g_*tan(x*_f_ + _e_))*(a_ + _b_*sin(x*_f_ + _e_))), x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, g_], x), NeQ(a_**2 - _b_**2, 0),),
        replacement=Int(sqrt(cos(x*_f_ + _e_))/((a_ + _b_*sin(x*_f_ + _e_))*sqrt(sin(x*_f_ + _e_))), x)*sqrt(sin(x*_f_ + _e_))/(sqrt(g_*tan(x*_f_ + _e_))*sqrt(cos(x*_f_ + _e_))),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=25,
    ),
    # Rule 26
    RubiRulePattern(
        pattern=Int((a_ + _b_*sin(x*_f_ + _e_))**m_*tan(x*_f_ + _e_)**p_, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_], x), NeQ(a_**2 - _b_**2, 0), IntegersQ(m_, p_/2),),
        replacement=Int(ExpandIntegrand((a_ + _b_*sin(x*_f_ + _e_))**m_*sin(x*_f_ + _e_)**p_/(1 - sin(x*_f_ + _e_)**2)**(p_/2), x), x),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=26,
    ),
    # Rule 27
    RubiRulePattern(
        pattern=Int((_g_*tan(x*_f_ + _e_))**_p_*(a_ + _b_*sin(x*_f_ + _e_))**_m_, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, _g_, _m_, _p_], x),),
        replacement=Unintegrable((_g_*tan(x*_f_ + _e_))**_p_*(a_ + _b_*sin(x*_f_ + _e_))**_m_, x),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=27,
    ),
    # Rule 28
    RubiRulePattern(
        pattern=Int((_g_*cot(x*_f_ + _e_))**p_*(a_ + _b_*sin(x*_f_ + _e_))**_m_, x),
        constraints=(FreeQ([a_, _b_, _e_, _f_, _g_, _m_, p_], x), Not(IntegerQ(p_)),),
        replacement=_g_**(2*IntPart(p_))*(_g_*tan(x*_f_ + _e_))**FracPart(p_)*(_g_*cot(x*_f_ + _e_))**FracPart(p_)*Int((a_ + _b_*sin(x*_f_ + _e_))**_m_/(_g_*tan(x*_f_ + _e_))**p_, x),
        module_name='4.1.1.3 (g tan)^p (a+b sin)^m',
        rule_number=28,
    ),

]

# Summary: 28 rules translated, 0 skipped
