# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_rules/codegen/generate.py
# Source: 4.3.12 (d+e x)^m tan(a+b x+c x^2)^n.m
# Module: 4.3.12 (d+e x)^m tan(a+b x+c x^2)^n
#
# This file contains Rubi integration rules as RubiRulePattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Integer, Integral, Lambda, Rational, Symbol, Tuple as SympyTuple, Eq, Ne, Lt, Gt, Le, Ge, log, sqrt, pi, I, oo
from rubi_rules.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (sin, cos, tan, sec, csc, cot, asin, acos, atan, atan2, asec, acsc, acot,
                   sinh, cosh, tanh, sech, csch, coth, asinh, acosh, atanh, asech, acsch, acoth,
                   exp, Abs, diff, denom, frac, floor, root, simplify,
                   elliptic_e, elliptic_f, hyper, appellf1)

from sympy_matching.wild import WildSymbol, WildHeadApp, WildHeadDeriv, IDENTITY_ELEMENT
from rubi_rules.base_objects import Int, RubiRulePattern
from rubi_rules.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, OddQ, EvenQ, NumberQ, NumericQ, AtomQ, MemberQ,
    PositiveQ, NegativeQ, PolynomialQ, TrueQ, FalseQ, MatchQ, PrimeQ, UnsameQ,
    # RUBI-specific constraints
    EqQ, NeQ, IGtQ, ILtQ, IGeQ, ILeQ, GtQ, LtQ, GeQ, LeQ, PosQ, NegQ,
    IntegersQ, HalfIntegerQ, FractionQ, RationalQ, ComplexNumberQ, RealNumberQ,
    FractionOrNegativeQ, SqrtNumberQ, PowerQ, ProductQ, SumQ, NonsumQ,
    IntegerPowerQ, FractionalPowerQ, PolyQ, LinearQ, QuadraticQ, BinomialQ,
    TrinomialQ, LinearMatchQ, QuadraticMatchQ, BinomialMatchQ, TrinomialMatchQ,
    TrigQ, HyperbolicQ, InverseTrigQ, InverseHyperbolicQ, LogQ, ComplexFreeQ,
    InverseFunctionFreeQ, FractionalPowerFreeQ, TrigHyperbolicFreeQ, IntegralFreeQ,
    RationalFunctionQ, AlgebraicFunctionQ, IndependentQ, SimplerQ, SumSimplerQ,
    FunctionOfQ, PiecewiseLinearQ, ExpressionEqQ,
    IntLinearQ, IntBinomialQ, IntQuadraticQ,
    MonomialQ, LinearPairQ,
    GeneralizedBinomialQ, GeneralizedBinomialMatchQ,
    GeneralizedTrinomialQ, GeneralizedTrinomialMatchQ,
    NiceSqrtQ, SimplerSqrtQ, FractionalPowerFactorQ,
    SumBaseQ, InverseFunctionQ, InertTrigQ, InertTrigFreeQ,
    CalculusFreeQ, QuotientOfLinearsQ,
    PowerOfLinearQ, PowerOfLinearMatchQ,
    FunctionOfExponentialQ,
    KnownSineIntegrandQ, KnownSecantIntegrandQ,
    KnownTangentIntegrandQ, KnownCotangentIntegrandQ,
    EulerIntegrandQ, SubstForFractionalPowerQ,
    PerfectSquareQ, PolynomialInQ, FunctionOfTrigOfLinearQ,
    SimplerIntegrandQ, PseudoBinomialPairQ, QuadraticProductQ,
    EveryQ, TrigSimplifyQ, EqM, TryPureTanSubst,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')

RULES = [
    # Rule 1
    RubiRulePattern(
        pattern=Int(tan(x**2*_c_ + x*_b_ + _a_)**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _n_], x),),
        replacement=Unintegrable(tan(x**2*_c_ + x*_b_ + _a_)**_n_, x),
        module_name='4.3.12 (d+e x)^m tan(a+b x+c x^2)^n',
        rule_number=1,
    ),
    # Rule 2
    RubiRulePattern(
        pattern=Int(cot(x**2*_c_ + x*_b_ + _a_)**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _n_], x),),
        replacement=Unintegrable(cot(x**2*_c_ + x*_b_ + _a_)**_n_, x),
        module_name='4.3.12 (d+e x)^m tan(a+b x+c x^2)^n',
        rule_number=2,
    ),
    # Rule 3
    RubiRulePattern(
        pattern=Int((x*_e_ + d_)*tan(x**2*_c_ + x*_b_ + _a_), x),
        constraints=(FreeQ([_a_, _b_, _c_, d_, _e_], x), EqQ(-_b_*_e_ + 2*_c_*d_, 0),),
        replacement=-_e_*log(cos(x**2*_c_ + x*_b_ + _a_))/(2*_c_),
        module_name='4.3.12 (d+e x)^m tan(a+b x+c x^2)^n',
        rule_number=3,
    ),
    # Rule 4
    RubiRulePattern(
        pattern=Int((x*_e_ + d_)*cot(x**2*_c_ + x*_b_ + _a_), x),
        constraints=(FreeQ([_a_, _b_, _c_, d_, _e_], x), EqQ(-_b_*_e_ + 2*_c_*d_, 0),),
        replacement=_e_*log(sin(x**2*_c_ + x*_b_ + _a_))/(2*_c_),
        module_name='4.3.12 (d+e x)^m tan(a+b x+c x^2)^n',
        rule_number=4,
    ),
    # Rule 5
    RubiRulePattern(
        pattern=Int((x*_e_ + _d_)*tan(x**2*_c_ + x*_b_ + _a_), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_], x), NeQ(-_b_*_e_ + 2*_c_*_d_, 0),),
        replacement=-_e_*log(cos(x**2*_c_ + x*_b_ + _a_))/(2*_c_) + (-_b_*_e_ + 2*_c_*_d_)*Int(tan(x**2*_c_ + x*_b_ + _a_), x)/(2*_c_),
        module_name='4.3.12 (d+e x)^m tan(a+b x+c x^2)^n',
        rule_number=5,
    ),
    # Rule 6
    RubiRulePattern(
        pattern=Int((x*_e_ + _d_)*cot(x**2*_c_ + x*_b_ + _a_), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_], x), NeQ(-_b_*_e_ + 2*_c_*_d_, 0),),
        replacement=_e_*log(sin(x**2*_c_ + x*_b_ + _a_))/(2*_c_) + (-_b_*_e_ + 2*_c_*_d_)*Int(cot(x**2*_c_ + x*_b_ + _a_), x)/(2*_c_),
        module_name='4.3.12 (d+e x)^m tan(a+b x+c x^2)^n',
        rule_number=6,
    ),
    # Rule 7
    RubiRulePattern(
        pattern=Int((x*_e_ + _d_)**_m_*tan(x**2*_c_ + x*_b_ + _a_)**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _m_, _n_], x),),
        replacement=Unintegrable((x*_e_ + _d_)**_m_*tan(x**2*_c_ + x*_b_ + _a_)**_n_, x),
        module_name='4.3.12 (d+e x)^m tan(a+b x+c x^2)^n',
        rule_number=7,
    ),
    # Rule 8
    RubiRulePattern(
        pattern=Int((x*_e_ + _d_)**_m_*cot(x**2*_c_ + x*_b_ + _a_)**_n_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _m_, _n_], x),),
        replacement=Unintegrable((x*_e_ + _d_)**_m_*cot(x**2*_c_ + x*_b_ + _a_)**_n_, x),
        module_name='4.3.12 (d+e x)^m tan(a+b x+c x^2)^n',
        rule_number=8,
    ),

]

# Summary: 8 rules translated, 0 skipped
