# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_rules/codegen/generate.py
# Source: 1.4.3 Miscellaneous algebraic functions.m
# Module: 1.4.3 Miscellaneous algebraic functions
#
# This file contains Rubi integration rules as RubiRulePattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Integer, Integral, Lambda, Rational, Symbol, Tuple as SympyTuple, Eq, Ne, Lt, Gt, Le, Ge, log, sqrt, pi, I, oo
from rubi_rules.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (sin, cos, tan, sec, csc, cot, asin, acos, atan, atan2, asec, acsc, acot,
                   sinh, cosh, tanh, sech, csch, coth, asinh, acosh, atanh, asech, acsch, acoth,
                   exp, Abs, diff, denom, frac, floor, root, simplify,
                   elliptic_e, elliptic_f, hyper, appellf1)

from sympy_matching.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_rules.base_objects import Int, RubiRulePattern
from rubi_rules.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, OddQ, EvenQ, NumberQ, NumericQ, AtomQ, MemberQ,
    PositiveQ, NegativeQ, PolynomialQ, TrueQ, FalseQ, MatchQ, PrimeQ, UnsameQ,
    # RUBI-specific constraints
    EqQ, NeQ, IGtQ, ILtQ, IGeQ, ILeQ, GtQ, LtQ, GeQ, LeQ, PosQ, NegQ,
    IntegersQ, HalfIntegerQ, FractionQ, RationalQ, ComplexNumberQ, RealNumberQ,
    FractionOrNegativeQ, SqrtNumberQ, PowerQ, ProductQ, SumQ, NonsumQ,
    IntegerPowerQ, FractionalPowerQ, PolyQ, LinearQ, QuadraticQ, BinomialQ,
    TrinomialQ, LinearMatchQ, QuadraticMatchQ, BinomialMatchQ, TrinomialMatchQ,
    TrigQ, HyperbolicQ, InverseTrigQ, InverseHyperbolicQ, LogQ, ComplexFreeQ,
    InverseFunctionFreeQ, FractionalPowerFreeQ, TrigHyperbolicFreeQ, IntegralFreeQ,
    RationalFunctionQ, AlgebraicFunctionQ, IndependentQ, SimplerQ, SumSimplerQ,
    FunctionOfQ, PiecewiseLinearQ, ExpressionEqQ,
    IntLinearQ, IntBinomialQ, IntQuadraticQ,
    MonomialQ, LinearPairQ,
    GeneralizedBinomialQ, GeneralizedBinomialMatchQ,
    GeneralizedTrinomialQ, GeneralizedTrinomialMatchQ,
    NiceSqrtQ, SimplerSqrtQ, FractionalPowerFactorQ,
    SumBaseQ, InverseFunctionQ, InertTrigQ, InertTrigFreeQ,
    CalculusFreeQ, QuotientOfLinearsQ,
    PowerOfLinearQ, PowerOfLinearMatchQ,
    FunctionOfExponentialQ,
    KnownSineIntegrandQ, KnownSecantIntegrandQ,
    KnownTangentIntegrandQ, KnownCotangentIntegrandQ,
    EulerIntegrandQ, SubstForFractionalPowerQ,
    PerfectSquareQ, PolynomialInQ, FunctionOfTrigOfLinearQ,
    SimplerIntegrandQ, PseudoBinomialPairQ, QuadraticProductQ,
    EveryQ, TrigSimplifyQ, EqM, TryPureTanSubst,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

A_ = WildSymbol('A')
_B_ = WildSymbol('B', optional_value=IDENTITY_ELEMENT)
B_ = WildSymbol('B')
_Px_ = WildSymbol('Px', optional_value=IDENTITY_ELEMENT)
Px_ = WildSymbol('Px')
_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
_f_ = WildSymbol('f', optional_value=IDENTITY_ELEMENT)
f_ = WildSymbol('f')
_g_ = WildSymbol('g', optional_value=IDENTITY_ELEMENT)
g_ = WildSymbol('g')
_h_ = WildSymbol('h', optional_value=IDENTITY_ELEMENT)
h_ = WildSymbol('h')
_i_ = WildSymbol('i', optional_value=IDENTITY_ELEMENT)
i_ = WildSymbol('i')
_j_ = WildSymbol('j', optional_value=IDENTITY_ELEMENT)
j_ = WildSymbol('j')
_k_ = WildSymbol('k', optional_value=IDENTITY_ELEMENT)
k_ = WildSymbol('k')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')
_nn_ = WildSymbol('nn', optional_value=IDENTITY_ELEMENT)
nn_ = WildSymbol('nn')
_p_ = WildSymbol('p', optional_value=IDENTITY_ELEMENT)
p_ = WildSymbol('p')
q_ = WildSymbol('q')
_u_ = WildSymbol('u', optional_value=IDENTITY_ELEMENT)
u_ = WildSymbol('u')
v_ = WildSymbol('v')
w_ = WildSymbol('w')

RULES = [
    # Rule 1: SKIPPED - ValueError: Non-string function head ['Times', 'e', ['Plus', ['Times', 'b', 'c'], ['Times', '-1', ['Times', 'a', 'd']]]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 2: SKIPPED - ValueError: Non-string function head ['Times', 'e', ['Plus', ['Times', 'b', 'c'], ['Times', '-1', ['Times', 'a', 'd']]]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 3
    RubiRulePattern(
        pattern=Int(u_/(_e_*sqrt(x*_b_ + _a_) + _f_*sqrt(x*_d_ + _c_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), NeQ(_a_*_e_**2 - _c_*_f_**2, 0), NeQ(_b_*_e_**2 - _d_*_f_**2, 0),),
        replacement=((sympy.Function('e')(Symbol('Star')) * Int(((u_ * sympy.sqrt((_a_ + (_b_ * x)))) * (((_a_ * (_e_)**(Integer(2))) + (Integer(-1) * (_c_ * (_f_)**(Integer(2)))) + (((_b_ * (_e_)**(Integer(2))) + (Integer(-1) * (_d_ * (_f_)**(Integer(2))))) * x)))**(Integer(-1))), x)) + (Integer(-1) * (sympy.Function('f')(Symbol('Star')) * Int(((u_ * sympy.sqrt((_c_ + (_d_ * x)))) * (((_a_ * (_e_)**(Integer(2))) + (Integer(-1) * (_c_ * (_f_)**(Integer(2)))) + (((_b_ * (_e_)**(Integer(2))) + (Integer(-1) * (_d_ * (_f_)**(Integer(2))))) * x)))**(Integer(-1))), x)))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=3,
    ),
    # Rule 4: SKIPPED - ValueError: Non-string function head ['Times', 'a', 'd'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 5
    RubiRulePattern(
        pattern=Int(x**_m_/(x**_n_*_d_ + _c_*sqrt(x**_p_*_b_ + _a_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _m_, _n_], x), EqQ(_p_, 2*_n_), NeQ(_b_*_c_**2 - _d_**2, 0),),
        replacement=(((Integer(-1) * sympy.Function('d')(Symbol('Star'))) * Int(((x)**((_m_ + _n_)) * (((_a_ * (_c_)**(Integer(2))) + (((_b_ * (_c_)**(Integer(2))) + (Integer(-1) * (_d_)**(Integer(2)))) * (x)**((Integer(2) * _n_)))))**(Integer(-1))), x)) + (sympy.Function('c')(Symbol('Star')) * Int((((x)**(_m_) * sympy.sqrt((_a_ + (_b_ * (x)**((Integer(2) * _n_)))))) * (((_a_ * (_c_)**(Integer(2))) + (((_b_ * (_c_)**(Integer(2))) + (Integer(-1) * (_d_)**(Integer(2)))) * (x)**((Integer(2) * _n_)))))**(Integer(-1))), x))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=5,
    ),
    # Rule 6: SKIPPED - ValueError: Non-string function head ['Times', '3', 'a'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 7: SKIPPED - ValueError: Non-string function head ['Times', '3', 'a'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 8: SKIPPED - ValueError: Non-string function head ['Times', '3', 'a'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 9: SKIPPED - ValueError: Non-string function head ['Times', '3', 'a'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 10
    RubiRulePattern(
        pattern=Int(u_*(x**4*_B_ + A_)/sqrt(v_), x),
        constraints=(FreeQ([A_, _B_], x), PolyQ(v_, x**2, 2), PolyQ(1/u_, x**2, 2), EqQ(A_*Coeff(v_, x, 4) + _B_*Coeff(v_, x, 0), 0), EqQ(Coeff(1/u_, x, 0)*Coeff(v_, x, 4) - Coeff(1/u_, x, 4)*Coeff(v_, x, 0), 0),),
        replacement=With(List(Set(Symbol('a'), Coeff(v_, x, Integer(0))), Set(Symbol('b'), Coeff(v_, x, Integer(2))), Set(Symbol('c'), Coeff(v_, x, Integer(4))), Set(Symbol('d'), Coeff((u_)**(Integer(-1)), x, Integer(0))), Set(Symbol('e'), Coeff((u_)**(Integer(-1)), x, Integer(2))), Set(Symbol('f'), Coeff((u_)**(Integer(-1)), x, Integer(4)))), (sympy.Function('A')(Symbol('Star')) * Subst(Int(((Symbol('d') + (Integer(-1) * (((Symbol('b') * Symbol('d')) + (Integer(-1) * (Symbol('a') * Symbol('e')))) * (x)**(Integer(2))))))**(Integer(-1)), x), x, (x * (sympy.sqrt(v_))**(Integer(-1)))))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=10,
    ),
    # Rule 11
    RubiRulePattern(
        pattern=Int(1/((x*_b_ + a_)*sqrt(x**2*_d_ + c_)*sqrt(x**2*_f_ + e_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, e_, _f_], x),),
        replacement=((sympy.Function('a')(Symbol('Star')) * Int(((((a_)**(Integer(2)) + (Integer(-1) * ((_b_)**(Integer(2)) * (x)**(Integer(2))))) * sympy.sqrt((c_ + (_d_ * (x)**(Integer(2))))) * sympy.sqrt((e_ + (_f_ * (x)**(Integer(2)))))))**(Integer(-1)), x)) + (Integer(-1) * (sympy.Function('b')(Symbol('Star')) * Int((x * ((((a_)**(Integer(2)) + (Integer(-1) * ((_b_)**(Integer(2)) * (x)**(Integer(2))))) * sympy.sqrt((c_ + (_d_ * (x)**(Integer(2))))) * sympy.sqrt((e_ + (_f_ * (x)**(Integer(2)))))))**(Integer(-1))), x)))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=11,
    ),
    # Rule 12
    RubiRulePattern(
        pattern=Int((x*_h_ + _g_)*sqrt(x*_e_ + _d_ + _f_*sqrt(x**2*_c_ + x*_b_ + _a_)), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _g_, _h_], x), EqQ(-_f_**2*(_a_*_h_**2 - _b_*_g_*_h_ + _c_*_g_**2) + (-_d_*_h_ + _e_*_g_)**2, 0), EqQ(-2*_d_*_e_*_h_ + 2*_e_**2*_g_ - _f_**2*(-_b_*_h_ + 2*_c_*_g_), 0),),
        replacement=sqrt(x*_e_ + _d_ + _f_*sqrt(x**2*_c_ + x*_b_ + _a_))*(6*x**3*_c_**2*_f_*_h_**2 + 18*x**2*_c_**2*_f_*_g_*_h_ + 2*x*_c_*_f_*(_a_*_h_**2 - _b_*_g_*_h_ + 10*_c_*_g_**2) + 2*_f_*(2*_a_*_b_*_h_**2 - 3*_a_*_c_*_g_*_h_ - 2*_b_**2*_g_*_h_ + 5*_b_*_c_*_g_**2) - 2*(-_d_*_h_ + _e_*_g_)*sqrt(x**2*_c_ + x*_b_ + _a_)*(x*_c_*_h_ - 2*_b_*_h_ + 5*_c_*_g_))/(15*_c_**2*_f_*(x*_h_ + _g_)),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=12,
    ),
    # Rule 13
    RubiRulePattern(
        pattern=Int((x*_h_ + _g_)**_m_*(_f_*(_j_ + _k_*sqrt(v_)) + u_)**_n_, x),
        constraints=(FreeQ([_f_, _g_, _h_, _j_, _k_, _m_, _n_], x), LinearQ(u_, x), QuadraticQ(v_, x), Not(And(LinearMatchQ(u_, x), QuadraticMatchQ(v_, x), Or(EqQ(_j_, 0), EqQ(_f_, 1)))), EqQ(-_f_**2*_k_**2*(_g_**2*Coefficient(v_, x, 2) - _g_*_h_*Coefficient(v_, x, 1) + _h_**2*Coefficient(v_, x, 0)) + (_g_*Coefficient(u_, x, 1) - _h_*(_f_*_j_ + Coefficient(u_, x, 0)))**2, 0),),
        replacement=Int((x*_h_ + _g_)**_m_*(_f_*_k_*sqrt(ExpandToSum(v_, x)) + ExpandToSum(_f_*_j_ + u_, x))**_n_, x),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=13,
    ),
    # Rule 14
    RubiRulePattern(
        pattern=Int((_g_ + _h_*(x*_e_ + _d_ + _f_*sqrt(x**2*_c_ + x*_b_ + _a_))**n_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_, _g_, _h_, n_], x), EqQ(-_c_*_f_**2 + _e_**2, 0), IntegerQ(_p_),),
        replacement=(sympy.Function('2')(Symbol('Star')) * Subst(Int((((_g_ + (_h_ * (x)**(n_))))**(_p_) * (((_d_)**(Integer(2)) * _e_) + (Integer(-1) * (((_b_ * _d_) + (Integer(-1) * (_a_ * _e_))) * (_f_)**(Integer(2)))) + (Integer(-1) * (((Integer(2) * _d_ * _e_) + (Integer(-1) * (_b_ * (_f_)**(Integer(2))))) * x)) + (_e_ * (x)**(Integer(2)))) * ((((Integer(-2) * _d_ * _e_) + (_b_ * (_f_)**(Integer(2))) + (Integer(2) * _e_ * x)))**(Integer(2)))**(Integer(-1))), x), x, (_d_ + (_e_ * x) + (_f_ * sympy.sqrt((_a_ + (_b_ * x) + (_c_ * (x)**(Integer(2))))))))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=14,
    ),
    # Rule 15: SKIPPED - ValueError: Non-string function head ['Times', '2', 'e'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 16
    RubiRulePattern(
        pattern=Int((_g_ + _h_*(_f_*sqrt(v_) + u_)**n_)**_p_, x),
        constraints=(FreeQ([_f_, _g_, _h_, n_], x), LinearQ(u_, x), QuadraticQ(v_, x), Not(And(LinearMatchQ(u_, x), QuadraticMatchQ(v_, x))), EqQ(-_f_**2*Coefficient(v_, x, 2) + Coefficient(u_, x, 1)**2, 0), IntegerQ(_p_),),
        replacement=Int((_g_ + _h_*(_f_*sqrt(ExpandToSum(v_, x)) + ExpandToSum(u_, x))**n_)**_p_, x),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=16,
    ),
    # Rule 17: SKIPPED - ValueError: Non-string function head ['Times', ['Power', '2', ['Plus', 'm', '1']], ['Power', 'e', ['Plus', 'm', '1']]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 18
    RubiRulePattern(
        pattern=Int(x**_p_*(x*_e_ + _f_*sqrt(x**2*_c_ + a_))**_n_*(x**2*_i_ + g_)**_m_, x),
        constraints=(FreeQ([a_, _c_, _e_, _f_, g_, _i_, _n_], x), EqQ(-_c_*_f_**2 + _e_**2, 0), EqQ(-a_*_i_ + _c_*g_, 0), IntegersQ(_p_, 2*_m_), Or(IntegerQ(_m_), GtQ(_i_/_c_, 0)),),
        replacement=((((Integer(2))**(((Integer(2) * _m_) + _p_ + Integer(1))) * (_e_)**((_p_ + Integer(1))) * (_f_)**((Integer(2) * _m_))))**(Integer(-1)) * ((_i_ * (_c_)**(Integer(-1))))**(sympy.Function('m')(Symbol('Star'))) * Subst(Int(((x)**((_n_ + (Integer(-1) * (Integer(2) * _m_)) + (Integer(-1) * _p_) + Integer(-2))) * ((((Integer(-1) * a_) * (_f_)**(Integer(2))) + (x)**(Integer(2))))**(_p_) * (((a_ * (_f_)**(Integer(2))) + (x)**(Integer(2))))**(((Integer(2) * _m_) + Integer(1)))), x), x, ((_e_ * x) + (_f_ * sympy.sqrt((a_ + (_c_ * (x)**(Integer(2))))))))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=18,
    ),
    # Rule 19
    RubiRulePattern(
        pattern=Int((x*_e_ + _d_ + _f_*sqrt(x**2*_c_ + x*_b_ + _a_))**_n_*(x**2*_i_ + x*_h_ + _g_)**_m_, x),
        constraints=(),
        replacement=(Integer(2) * ((_f_)**((Integer(2) * _m_)))**(Integer(-1)) * ((_i_ * (_c_)**(Integer(-1))))**(sympy.Function('m')(Symbol('Star')))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=19,
    ),
    # Rule 21
    RubiRulePattern(
        pattern=Int((x**2*_i_ + g_)**_m_*(x*_e_ + _d_ + _f_*sqrt(x**2*_c_ + a_))**_n_, x),
        constraints=(),
        replacement=((((Integer(2))**(((Integer(2) * _m_) + Integer(1))) * _e_ * (_f_)**((Integer(2) * _m_))))**(Integer(-1)) * ((_i_ * (_c_)**(Integer(-1))))**(sympy.Function('m')(Symbol('Star')))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=21,
    ),
    # Rule 23: SKIPPED - ValueError: Non-string function head ['Sqrt', ['Plus', 'a', ['Times', 'b', 'x'], ['Times', 'c', ['Power', 'x', '2']]]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 24: SKIPPED - ValueError: Non-string function head ['Sqrt', ['Plus', 'a', ['Times', 'c', ['Power', 'x', '2']]]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 25: SKIPPED - ValueError: Non-string function head ['Sqrt', ['Plus', 'g', ['Times', 'h', 'x'], ['Times', 'i', ['Power', 'x', '2']]]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 26: SKIPPED - ValueError: Non-string function head ['Sqrt', ['Plus', 'g', ['Times', 'i', ['Power', 'x', '2']]]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 27
    RubiRulePattern(
        pattern=Int(w_**_m_*(_f_*(_j_ + _k_*sqrt(v_)) + u_)**_n_, x),
        constraints=(FreeQ([_f_, _j_, _k_, _m_, _n_], x), LinearQ(u_, x), QuadraticQ([v_, w_], x), Not(And(LinearMatchQ(u_, x), QuadraticMatchQ([v_, w_], x), Or(EqQ(_j_, Integer(0)), EqQ(_f_, Integer(1))))), EqQ(-_f_**2*_k_**2*Coefficient(v_, x, 2) + Coefficient(u_, x, 1)**2, 0),),
        replacement=Int((_f_*_k_*sqrt(ExpandToSum(v_, x)) + ExpandToSum(_f_*_j_ + u_, x))**_n_*ExpandToSum(w_, x)**_m_, x),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=27,
    ),
    # Rule 28
    RubiRulePattern(
        pattern=Int(1/(sqrt(x**2*_c_ + _d_*(x**_n_*_b_ + a_)**_p_)*(x**_n_*_b_ + a_)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _n_], x), EqQ(_p_, 2/_n_),),
        replacement=((sympy.Function('a')(Symbol('Star')))**(Integer(-1)) * Subst(Int(((Integer(1) + (Integer(-1) * (_c_ * (x)**(Integer(2))))))**(Integer(-1)), x), x, (x * (sympy.sqrt(((_c_ * (x)**(Integer(2))) + (_d_ * ((a_ + (_b_ * (x)**(_n_))))**((Integer(2) * (_n_)**(Integer(-1))))))))**(Integer(-1))))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=28,
    ),
    # Rule 29
    RubiRulePattern(
        pattern=Int(sqrt(a_ + _b_*sqrt(x**2*_d_ + c_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_], x), EqQ(a_**2 - _b_**2*c_, 0),),
        replacement=2*x**3*_b_**2*_d_/(3*(a_ + _b_*sqrt(x**2*_d_ + c_))**(sympy.S(3)/2)) + 2*x*a_/sqrt(a_ + _b_*sqrt(x**2*_d_ + c_)),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=29,
    ),
    # Rule 30
    RubiRulePattern(
        pattern=Int(sqrt(x**2*_a_ + x*_b_*sqrt(x**2*_d_ + c_))/(x*sqrt(x**2*_d_ + c_)), x),
        constraints=(FreeQ([_a_, _b_, c_, _d_], x), EqQ(_a_**2 - _b_**2*_d_, 0), EqQ(_a_ + _b_**2*c_, 0),),
        replacement=(sympy.sqrt(Integer(2)) * _b_ * (sympy.Function('a')(Symbol('Star')))**(Integer(-1)) * Subst(Int((sympy.sqrt((Integer(1) + ((x)**(Integer(2)) * (_a_)**(Integer(-1))))))**(Integer(-1)), x), x, ((_a_ * x) + (_b_ * sympy.sqrt((c_ + (_d_ * (x)**(Integer(2))))))))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=30,
    ),
    # Rule 31
    RubiRulePattern(
        pattern=Int(sqrt(x*_e_*(x*_a_ + _b_*sqrt(x**2*_d_ + c_)))/(x*sqrt(x**2*_d_ + c_)), x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _e_], x), EqQ(_a_**2 - _b_**2*_d_, 0), EqQ(_a_ + _b_**2*c_*_e_, 0),),
        replacement=Int(sqrt(x**2*_a_*_e_ + x*_b_*_e_*sqrt(x**2*_d_ + c_))/(x*sqrt(x**2*_d_ + c_)), x),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=31,
    ),
    # Rule 32
    RubiRulePattern(
        pattern=Int(sqrt(x**2*_c_ + _d_*sqrt(x**4*_b_ + a_))/sqrt(x**4*_b_ + a_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_], x), EqQ(-_b_*_d_**2 + _c_**2, 0),),
        replacement=(sympy.Function('d')(Symbol('Star')) * Subst(Int(((Integer(1) + (Integer(-1) * (Integer(2) * _c_ * (x)**(Integer(2))))))**(Integer(-1)), x), x, (x * (sympy.sqrt(((_c_ * (x)**(Integer(2))) + (_d_ * sympy.sqrt((a_ + (_b_ * (x)**(Integer(4)))))))))**(Integer(-1))))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=32,
    ),
    # Rule 33
    RubiRulePattern(
        pattern=Int((x*_d_ + _c_)**_m_*sqrt(x**2*_b_ + sqrt(x**4*_e_ + a_))/sqrt(x**4*_e_ + a_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _m_], x), EqQ(_e_, _b_**2), GtQ(a_, 0),),
        replacement=(((Integer(1) + (Integer(-1) * sympy.I)) * (sympy.Function('2')(Symbol('Star')))**(Integer(-1)) * Int((((_c_ + (_d_ * x)))**(_m_) * (sympy.sqrt((sympy.sqrt(a_) + (Integer(-1) * (sympy.I * _b_ * (x)**(Integer(2)))))))**(Integer(-1))), x)) + ((Integer(1) + sympy.I) * (sympy.Function('2')(Symbol('Star')))**(Integer(-1)) * Int((((_c_ + (_d_ * x)))**(_m_) * (sympy.sqrt((sympy.sqrt(a_) + (sympy.I * _b_ * (x)**(Integer(2))))))**(Integer(-1))), x))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=33,
    ),
    # Rule 34: SKIPPED - ValueError: Non-string function head ['Times', '3', 'c'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 35: SKIPPED - ValueError: Non-string function head ['Times', 'c', ['Plus', ['Times', 'b', ['Power', 'c', '3']], ['Times', '-1', ['Times', '28', 'a', ['Power', 'd', '3']]]]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 36: SKIPPED - ValueError: Non-string function head ['Plus', ['Times', ['Plus', '1', ['Sqrt', '3']], 'd'], ['Times', '-1', ['Times', 'c', 'q']]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 37
    RubiRulePattern(
        pattern=Int((x*_f_ + e_)/((x*_d_ + c_)*sqrt(x**3*_b_ + a_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, e_, _f_], x), NeQ(-c_*_f_ + _d_*e_, 0), EqQ(-4*a_*_d_**3 + _b_*c_**3, 0), EqQ(c_*_f_ + 2*_d_*e_, 0),),
        replacement=(Integer(2) * e_ * (sympy.Function('d')(Symbol('Star')))**(Integer(-1)) * Subst(Int(((Integer(1) + (Integer(3) * a_ * (x)**(Integer(2)))))**(Integer(-1)), x), x, ((Integer(1) + (Integer(2) * _d_ * x * (c_)**(Integer(-1)))) * (sympy.sqrt((a_ + (_b_ * (x)**(Integer(3))))))**(Integer(-1))))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=37,
    ),
    # Rule 38
    RubiRulePattern(
        pattern=Int((x*_f_ + e_)/((x*_d_ + c_)*sqrt(x**3*_b_ + a_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, e_, _f_], x), NeQ(-c_*_f_ + _d_*e_, 0), EqQ(8*a_*_d_**3 + _b_*c_**3, 0), EqQ(c_*_f_ + 2*_d_*e_, 0),),
        replacement=(Integer(-2) * e_ * (sympy.Function('d')(Symbol('Star')))**(Integer(-1)) * Subst(Int(((Integer(9) + (Integer(-1) * (a_ * (x)**(Integer(2))))))**(Integer(-1)), x), x, (((Integer(1) + (_f_ * x * (e_)**(Integer(-1)))))**(Integer(2)) * (sympy.sqrt((a_ + (_b_ * (x)**(Integer(3))))))**(Integer(-1))))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=38,
    ),
    # Rule 39: SKIPPED - ValueError: Non-string function head ['Times', '3', 'c', 'd'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 40
    RubiRulePattern(
        pattern=Int((x*_f_ + e_)/((x*_d_ + c_)*sqrt(x**3*_b_ + a_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, e_, _f_], x), NeQ(-c_*_f_ + _d_*e_, 0), EqQ(-8*a_**2*_d_**6 - 20*a_*_b_*c_**3*_d_**3 + _b_**2*c_**6, 0), EqQ(6*a_*_d_**4*e_ - c_*_f_*(-22*a_*_d_**3 + _b_*c_**3), 0),),
        replacement=With(List(Set(Symbol('k'), Simplify((((_d_ * e_) + (Integer(2) * c_ * _f_)) * ((c_ * _f_))**(Integer(-1)))))), ((Integer(1) + Symbol('k')) * e_ * (sympy.Function('d')(Symbol('Star')))**(Integer(-1)) * Subst(Int(((Integer(1) + ((Integer(3) + (Integer(2) * Symbol('k'))) * a_ * (x)**(Integer(2)))))**(Integer(-1)), x), x, ((Integer(1) + ((Integer(1) + Symbol('k')) * _d_ * x * (c_)**(Integer(-1)))) * (sympy.sqrt((a_ + (_b_ * (x)**(Integer(3))))))**(Integer(-1)))))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=40,
    ),
    # Rule 41: SKIPPED - ValueError: Non-string function head ['Times', 'c', 'd', ['Plus', ['Times', 'b', ['Power', 'c', '3']], ['Times', '-1', ['Times', '28', 'a', ['Power', 'd', '3']]]]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 42: SKIPPED - ValueError: Non-string function head ['Times', 'q', ['Sqrt', ['Plus', 'a', ['Times', 'b', ['Power', 'x', '3']]]], ['Sqrt', ['Times', ['Plus', '1', ['Times', 'q', 'x']], ['Power', ['Power', ['Plus', '1', ['Sqrt', '3'], ['Times', 'q', 'x']], '2'], '-1']]]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 43: SKIPPED - ValueError: Non-string function head ['Times', 'q', ['Sqrt', ['Plus', 'a', ['Times', 'b', ['Power', 'x', '3']]]], ['Sqrt', ['Times', ['Times', '-1', ['Plus', '1', ['Times', '-1', ['Times', 'q', 'x']]]], ['Power', ['Power', ['Plus', '1', ['Times', '-1', ['Sqrt', '3']], ['Times', '-1', ['Times', 'q', 'x']]], '2'], '-1']]]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 44: SKIPPED - ValueError: Non-string function head ['Plus', ['Times', ['Plus', '1', ['Sqrt', '3']], 'd'], ['Times', '-1', ['Times', 'c', 'q']]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 45
    RubiRulePattern(
        pattern=Int((x**2*_h_ + x*_g_ + f_)/(sqrt(x**3*_b_ + a_)*(x**2*_e_ + x*_d_ + c_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_, f_, _g_, _h_], x), NeQ(-2*a_*_e_*_h_ + _b_*_d_*f_, 0), EqQ(-8*a_*_h_**3 + _b_*_g_**3, 0), EqQ(2*f_*_h_ + _g_**2, 0), EqQ(-4*a_*_e_*_h_ + _b_*c_*_g_ + _b_*_d_*f_, 0),),
        replacement=(Integer(-2) * _g_ * sympy.Function('h')(Symbol('Star')) * Subst(Int((((Integer(2) * _e_ * _h_) + (Integer(-1) * (((_b_ * _d_ * f_) + (Integer(-1) * (Integer(2) * a_ * _e_ * _h_))) * (x)**(Integer(2))))))**(Integer(-1)), x), x, ((Integer(1) + (Integer(2) * _h_ * x * (_g_)**(Integer(-1)))) * (sympy.sqrt((a_ + (_b_ * (x)**(Integer(3))))))**(Integer(-1))))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=45,
    ),
    # Rule 46
    RubiRulePattern(
        pattern=Int((x**2*_h_ + x*_g_ + f_)/((x**2*_e_ + c_)*sqrt(x**3*_b_ + a_)), x),
        constraints=(FreeQ([a_, _b_, c_, _e_, f_, _g_, _h_], x), EqQ(-8*a_*_h_**3 + _b_*_g_**3, 0), EqQ(2*f_*_h_ + _g_**2, 0), EqQ(-4*a_*_e_*_h_ + _b_*c_*_g_, 0),),
        replacement=((Integer(-1) * _g_) * (sympy.Function('e')(Symbol('Star')))**(Integer(-1)) * Subst(Int(((Integer(1) + (a_ * (x)**(Integer(2)))))**(Integer(-1)), x), x, ((Integer(1) + (Integer(2) * _h_ * x * (_g_)**(Integer(-1)))) * (sympy.sqrt((a_ + (_b_ * (x)**(Integer(3))))))**(Integer(-1))))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=46,
    ),
    # Rule 47
    RubiRulePattern(
        pattern=Int(sqrt(x**3*_b_ + a_)/(x*_d_ + c_), x),
        constraints=(FreeQ([a_, _b_, c_, _d_], x), EqQ(-a_*_d_**3 + _b_*c_**3, 0),),
        replacement=((_b_ * (sympy.Function('d')(Symbol('Star')))**(Integer(-1)) * Int(((x)**(Integer(2)) * (sympy.sqrt((a_ + (_b_ * (x)**(Integer(3))))))**(Integer(-1))), x)) + (_b_ * c_ * ((_d_)**(sympy.Function('3')(Symbol('Star'))))**(Integer(-1)) * Int(((c_ + (Integer(-1) * (_d_ * x))) * (sympy.sqrt((a_ + (_b_ * (x)**(Integer(3))))))**(Integer(-1))), x))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=47,
    ),
    # Rule 48
    RubiRulePattern(
        pattern=Int(sqrt(x**3*_b_ + a_)/(x*_d_ + c_), x),
        constraints=(FreeQ([a_, _b_, c_, _d_], x), NeQ(-a_*_d_**3 + _b_*c_**3, 0),),
        replacement=((_b_ * (sympy.Function('d')(Symbol('Star')))**(Integer(-1)) * Int(((x)**(Integer(2)) * (sympy.sqrt((a_ + (_b_ * (x)**(Integer(3))))))**(Integer(-1))), x)) + (_b_ * c_ * ((_d_)**(sympy.Function('3')(Symbol('Star'))))**(Integer(-1)) * Int(((c_ + (Integer(-1) * (_d_ * x))) * (sympy.sqrt((a_ + (_b_ * (x)**(Integer(3))))))**(Integer(-1))), x)) + (Integer(-1) * (((_b_ * (c_)**(Integer(3))) + (Integer(-1) * (a_ * (_d_)**(Integer(3))))) * ((_d_)**(sympy.Function('3')(Symbol('Star'))))**(Integer(-1)) * Int((((c_ + (_d_ * x)) * sympy.sqrt((a_ + (_b_ * (x)**(Integer(3)))))))**(Integer(-1)), x)))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=48,
    ),
    # Rule 49
    RubiRulePattern(
        pattern=Int(1/((x*_d_ + c_)*(x**3*_b_ + a_)**(sympy.S(1)/3)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_], x), EqQ(a_*_d_**3 + _b_*c_**3, 0),),
        replacement=2**(sympy.S(2)/3)*log((-x*_d_ + c_)*(x*_d_ + c_)**2)/(8*_b_**(sympy.S(1)/3)*c_) - 3*2**(sympy.S(2)/3)*log(_b_**(sympy.S(1)/3)*(-x*_d_ + c_) + 2**(sympy.S(2)/3)*_d_*(x**3*_b_ + a_)**(sympy.S(1)/3))/(8*_b_**(sympy.S(1)/3)*c_) + 2**(sympy.S(2)/3)*sqrt(3)*atan(sqrt(3)*(-2**(sympy.S(1)/3)*_b_**(sympy.S(1)/3)*(-x*_d_ + c_)/(_d_*(x**3*_b_ + a_)**(sympy.S(1)/3)) + 1)/3)/(4*_b_**(sympy.S(1)/3)*c_),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=49,
    ),
    # Rule 50: SKIPPED - ValueError: Non-string function head ['Times', '2', 'c'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 51
    RubiRulePattern(
        pattern=Int((x*_f_ + e_)/((x*_d_ + c_)*(x**3*_b_ + a_)**(sympy.S(1)/3)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, e_, _f_], x), EqQ(c_*_f_ + _d_*e_, 0), EqQ(-a_*_d_**3 + 2*_b_*c_**3, 0),),
        replacement=_f_*log(x*_d_ + c_)/(_b_**(sympy.S(1)/3)*_d_) - 3*_f_*log(_b_**(sympy.S(1)/3)*(x*_d_ + 2*c_) - _d_*(x**3*_b_ + a_)**(sympy.S(1)/3))/(2*_b_**(sympy.S(1)/3)*_d_) + sqrt(3)*_f_*atan(sqrt(3)*(2*_b_**(sympy.S(1)/3)*(x*_d_ + 2*c_)/(_d_*(x**3*_b_ + a_)**(sympy.S(1)/3)) + 1)/3)/(_b_**(sympy.S(1)/3)*_d_),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=51,
    ),
    # Rule 52
    RubiRulePattern(
        pattern=Int((x*_f_ + _e_)/((x*_d_ + _c_)*(x**3*_b_ + a_)**(sympy.S(1)/3)), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _f_], x),),
        replacement=((_f_ * (sympy.Function('d')(Symbol('Star')))**(Integer(-1)) * Int((((a_ + (_b_ * (x)**(Integer(3)))))**((Integer(3))**(Integer(-1))))**(Integer(-1)), x)) + (((_d_ * _e_) + (Integer(-1) * (_c_ * _f_))) * (sympy.Function('d')(Symbol('Star')))**(Integer(-1)) * Int((((_c_ + (_d_ * x)) * ((a_ + (_b_ * (x)**(Integer(3)))))**((Integer(3))**(Integer(-1)))))**(Integer(-1)), x))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=52,
    ),
    # Rule 53
    RubiRulePattern(
        pattern=Int((x**3*_b_ + a_)**(sympy.S(2)/3)/(x*_d_ + c_), x),
        constraints=(FreeQ([a_, _b_, c_, _d_], x),),
        replacement=((((a_ + (_b_ * (x)**(Integer(3)))))**((Integer(2) * (Integer(3))**(Integer(-1)))) * ((Integer(2) * _d_))**(Integer(-1))) + (Integer(-1) * (_b_ * c_ * ((_d_)**(sympy.Function('2')(Symbol('Star'))))**(Integer(-1)) * Int((x * (((a_ + (_b_ * (x)**(Integer(3)))))**((Integer(3))**(Integer(-1))))**(Integer(-1))), x))) + (((_d_)**(sympy.Function('2')(Symbol('Star'))))**(Integer(-1)) * Int((((a_ * (_d_)**(Integer(2))) + (_b_ * (c_)**(Integer(2)) * x)) * (((c_ + (_d_ * x)) * ((a_ + (_b_ * (x)**(Integer(3)))))**((Integer(3))**(Integer(-1)))))**(Integer(-1))), x))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=53,
    ),
    # Rule 54
    RubiRulePattern(
        pattern=Int(1/((x*_d_ + c_)*(x**3*_b_ + a_)**(sympy.S(2)/3)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_], x), EqQ(-a_*_d_**3 + 2*_b_*c_**3, 0),),
        replacement=With(List(Set(Symbol('q'), sympy.root(_b_, Integer(3)))), (((Integer(-1) * _d_) * sympy.atan(((Integer(1) + (Integer(2) * Symbol('q') * x * (((a_ + (_b_ * (x)**(Integer(3)))))**((Integer(3))**(Integer(-1))))**(Integer(-1)))) * (sympy.sqrt(Integer(3)))**(Integer(-1)))) * ((Integer(2) * sympy.sqrt(Integer(3)) * (Symbol('q'))**(Integer(2)) * (c_)**(Integer(2))))**(Integer(-1))) + (sympy.sqrt(Integer(3)) * _d_ * sympy.atan(((Integer(1) + (Integer(2) * Symbol('q') * ((Integer(2) * c_) + (_d_ * x)) * ((_d_ * ((a_ + (_b_ * (x)**(Integer(3)))))**((Integer(3))**(Integer(-1)))))**(Integer(-1)))) * (sympy.sqrt(Integer(3)))**(Integer(-1)))) * ((Integer(2) * (Symbol('q'))**(Integer(2)) * (c_)**(Integer(2))))**(Integer(-1))) + (Integer(-1) * (_d_ * sympy.log((c_ + (_d_ * x))) * ((Integer(2) * (Symbol('q'))**(Integer(2)) * (c_)**(Integer(2))))**(Integer(-1)))) + (Integer(-1) * (_d_ * sympy.log(((Symbol('q') * x) + (Integer(-1) * ((a_ + (_b_ * (x)**(Integer(3)))))**((Integer(3))**(Integer(-1)))))) * ((Integer(4) * (Symbol('q'))**(Integer(2)) * (c_)**(Integer(2))))**(Integer(-1)))) + (Integer(3) * _d_ * sympy.log(((Symbol('q') * ((Integer(2) * c_) + (_d_ * x))) + (Integer(-1) * (_d_ * ((a_ + (_b_ * (x)**(Integer(3)))))**((Integer(3))**(Integer(-1))))))) * ((Integer(4) * (Symbol('q'))**(Integer(2)) * (c_)**(Integer(2))))**(Integer(-1))))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=54,
    ),
    # Rule 55
    RubiRulePattern(
        pattern=Int(x**_m_*Px_*(x*_d_ + c_)**q_*(x**3*_b_ + a_)**_p_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _m_, _p_], x), PolyQ(Px_, x), ILtQ(q_, 0), IntegerQ(_m_), RationalQ(_p_), EqQ(Denominator(_p_), 3),),
        replacement=Int(ExpandIntegrand((x**3*_b_ + a_)**_p_*(x**3*_d_**3 + c_**3)**q_, x**_m_*Px_/(x**2*_d_**2 - x*c_*_d_ + c_**2)**q_, x), x),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=55,
    ),
    # Rule 56
    RubiRulePattern(
        pattern=Int(_Px_*(x*_d_ + c_)**q_*(x**3*_b_ + a_)**_p_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _p_], x), PolyQ(_Px_, x), ILtQ(q_, 0), RationalQ(_p_), EqQ(Denominator(_p_), 3),),
        replacement=Int(ExpandIntegrand((x**3*_b_ + a_)**_p_*(x**3*_d_**3 + c_**3)**q_, _Px_/(x**2*_d_**2 - x*c_*_d_ + c_**2)**q_, x), x),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=56,
    ),
    # Rule 57
    RubiRulePattern(
        pattern=Int(x**_m_*Px_*(x**3*_b_ + a_)**_p_*(x**2*_e_ + x*_d_ + c_)**q_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_, _m_, _p_], x), PolyQ(Px_, x), EqQ(-c_*_e_ + _d_**2, 0), ILtQ(q_, 0), IntegerQ(_m_), RationalQ(_p_), EqQ(Denominator(_p_), 3),),
        replacement=(((c_)**(sympy.Function('q')(Symbol('Star'))))**(Integer(-1)) * Int(ExpandIntegrand(((((c_)**(Integer(3)) + (Integer(-1) * ((_d_)**(Integer(3)) * (x)**(Integer(3))))))**(q_) * ((a_ + (_b_ * (x)**(Integer(3)))))**(_p_)), ((x)**(_m_) * Px_ * (((c_ + (Integer(-1) * (_d_ * x))))**(q_))**(Integer(-1))), x), x)),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=57,
    ),
    # Rule 58
    RubiRulePattern(
        pattern=Int(_Px_*(x**3*_b_ + a_)**_p_*(x**2*_e_ + x*_d_ + c_)**q_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_, _p_], x), PolyQ(_Px_, x), EqQ(-c_*_e_ + _d_**2, 0), ILtQ(q_, 0), RationalQ(_p_), EqQ(Denominator(_p_), 3),),
        replacement=(((c_)**(sympy.Function('q')(Symbol('Star'))))**(Integer(-1)) * Int(ExpandIntegrand(((((c_)**(Integer(3)) + (Integer(-1) * ((_d_)**(Integer(3)) * (x)**(Integer(3))))))**(q_) * ((a_ + (_b_ * (x)**(Integer(3)))))**(_p_)), (_Px_ * (((c_ + (Integer(-1) * (_d_ * x))))**(q_))**(Integer(-1))), x), x)),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=58,
    ),
    # Rule 59
    RubiRulePattern(
        pattern=Int((x**_n_*_d_ + c_)**q_*(x**_nn_*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _n_, _nn_, p_], x), Not(IntegerQ(p_)), ILtQ(q_, 0), IGtQ(log(2)/log(_nn_/_n_), 0),),
        replacement=Int((-x**(2*_n_)*_d_**2 + c_**2)**q_*(x**_nn_*_b_ + a_)**p_*ExpandToSum((-x**_n_*_d_ + c_)**(-q_), x), x),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=59,
    ),
    # Rule 60
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*(x**_n_*_d_ + c_)**q_*(x**_nn_*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_, _m_, _n_, _nn_, p_], x), Not(IntegerQ(p_)), ILtQ(q_, 0), IGtQ(log(2)/log(_nn_/_n_), 0),),
        replacement=(((_e_ * x))**(_m_) * ((x)**(sympy.Function('m')(Symbol('Star'))))**(Integer(-1)) * Int(((x)**(_m_) * ExpandToSum(((c_ + (Integer(-1) * (_d_ * (x)**(_n_)))))**((Integer(-1) * q_)), x) * ((a_ + (_b_ * (x)**(_nn_))))**(p_) * ((((c_)**(Integer(2)) + (Integer(-1) * ((_d_)**(Integer(2)) * (x)**((Integer(2) * _n_))))))**((Integer(-1) * q_)))**(Integer(-1))), x)),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=60,
    ),
    # Rule 61
    RubiRulePattern(
        pattern=Int(x**_m_/(x**n_*_d_ + c_ + _e_*sqrt(x**n_*_b_ + a_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_, _m_, n_], x), EqQ(-a_*_d_ + _b_*c_, 0), IntegerQ((_m_ + 1)/n_),),
        replacement=((sympy.Function('n')(Symbol('Star')))**(Integer(-1)) * Subst(Int(((x)**((((_m_ + Integer(1)) * (n_)**(Integer(-1))) + Integer(-1))) * ((c_ + (_d_ * x) + (_e_ * sympy.sqrt((a_ + (_b_ * x))))))**(Integer(-1))), x), x, (x)**(n_))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=61,
    ),
    # Rule 62
    RubiRulePattern(
        pattern=Int(_u_/(x**n_*_d_ + c_ + _e_*sqrt(x**n_*_b_ + a_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_, n_], x), EqQ(-a_*_d_ + _b_*c_, 0),),
        replacement=((sympy.Function('c')(Symbol('Star')) * Int((_u_ * (((c_)**(Integer(2)) + (Integer(-1) * (a_ * (_e_)**(Integer(2)))) + (c_ * _d_ * (x)**(n_))))**(Integer(-1))), x)) + (Integer(-1) * (a_ * sympy.Function('e')(Symbol('Star')) * Int((_u_ * ((((c_)**(Integer(2)) + (Integer(-1) * (a_ * (_e_)**(Integer(2)))) + (c_ * _d_ * (x)**(n_))) * sympy.sqrt((a_ + (_b_ * (x)**(n_))))))**(Integer(-1))), x)))),
        module_name='1.4.3 Miscellaneous algebraic functions',
        rule_number=62,
    ),

]

# Summary: 38 rules translated, 24 skipped
