# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_rules/codegen/generate.py
# Source: 6.1.11 (e x)^m (a+b x^n)^p sinh.m
# Module: 6.1.11 (e x)^m (a+b x^n)^p sinh
#
# This file contains Rubi integration rules as RubiRulePattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Symbol
from rubi_rules.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or
from sympy import (
    cosh, sinh,
)

from sympy_matching.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_rules.base_objects import Int, RubiRulePattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_rules.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, EqQ, IGtQ, ILtQ, GtQ, LtQ, RationalQ,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
n_ = WildSymbol('n')
_p_ = WildSymbol('p', optional_value=IDENTITY_ELEMENT)
p_ = WildSymbol('p')

RULES = [
    # Rule 1
    RubiRulePattern(
        pattern=Int((x**n_*_b_ + a_)**_p_*sinh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, n_], x), IGtQ(_p_, 0),),
        replacement=Int(ExpandIntegrand(sinh(x*_d_ + _c_), (x**n_*_b_ + a_)**_p_, x), x),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=1,
    ),
    # Rule 2
    RubiRulePattern(
        pattern=Int((x**n_*_b_ + a_)**_p_*cosh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, n_], x), IGtQ(_p_, 0),),
        replacement=Int(ExpandIntegrand(cosh(x*_d_ + _c_), (x**n_*_b_ + a_)**_p_, x), x),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=2,
    ),
    # Rule 3
    RubiRulePattern(
        pattern=Int((x**n_*_b_ + a_)**p_*sinh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_], x), IntegerQ(p_), IGtQ(n_, 0), LtQ(p_, -1), GtQ(n_, 2),),
        replacement=x**(1 - n_)*(x**n_*_b_ + a_)**(p_ + 1)*sinh(x*_d_ + _c_)/(_b_*n_*(p_ + 1)) - _d_*Int(x**(1 - n_)*(x**n_*_b_ + a_)**(p_ + 1)*cosh(x*_d_ + _c_), x)/(_b_*n_*(p_ + 1)) - (1 - n_)*Int((x**n_*_b_ + a_)**(p_ + 1)*sinh(x*_d_ + _c_)/x**n_, x)/(_b_*n_*(p_ + 1)),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=3,
    ),
    # Rule 4
    RubiRulePattern(
        pattern=Int((x**n_*_b_ + a_)**p_*cosh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_], x), IntegerQ(p_), IGtQ(n_, 0), LtQ(p_, -1), GtQ(n_, 2),),
        replacement=x**(1 - n_)*(x**n_*_b_ + a_)**(p_ + 1)*cosh(x*_d_ + _c_)/(_b_*n_*(p_ + 1)) - _d_*Int(x**(1 - n_)*(x**n_*_b_ + a_)**(p_ + 1)*sinh(x*_d_ + _c_), x)/(_b_*n_*(p_ + 1)) - (1 - n_)*Int((x**n_*_b_ + a_)**(p_ + 1)*cosh(x*_d_ + _c_)/x**n_, x)/(_b_*n_*(p_ + 1)),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=4,
    ),
    # Rule 5
    RubiRulePattern(
        pattern=Int((x**n_*_b_ + a_)**p_*sinh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_], x), ILtQ(p_, 0), IGtQ(n_, 0), Or(EqQ(n_, 2), EqQ(p_, -1)),),
        replacement=Int(ExpandIntegrand(sinh(x*_d_ + _c_), (x**n_*_b_ + a_)**p_, x), x),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=5,
    ),
    # Rule 6
    RubiRulePattern(
        pattern=Int((x**n_*_b_ + a_)**p_*cosh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_], x), ILtQ(p_, 0), IGtQ(n_, 0), Or(EqQ(n_, 2), EqQ(p_, -1)),),
        replacement=Int(ExpandIntegrand(cosh(x*_d_ + _c_), (x**n_*_b_ + a_)**p_, x), x),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=6,
    ),
    # Rule 7
    RubiRulePattern(
        pattern=Int((x**n_*_b_ + a_)**p_*sinh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_], x), ILtQ(p_, 0), ILtQ(n_, 0),),
        replacement=Int(x**(n_*p_)*(_b_ + a_/x**n_)**p_*sinh(x*_d_ + _c_), x),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=7,
    ),
    # Rule 8
    RubiRulePattern(
        pattern=Int((x**n_*_b_ + a_)**p_*cosh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_], x), ILtQ(p_, 0), ILtQ(n_, 0),),
        replacement=Int(x**(n_*p_)*(_b_ + a_/x**n_)**p_*cosh(x*_d_ + _c_), x),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=8,
    ),
    # Rule 9
    RubiRulePattern(
        pattern=Int((x**n_*_b_ + a_)**p_*sinh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, n_, p_], x),),
        replacement=Unintegrable((x**n_*_b_ + a_)**p_*sinh(x*_d_ + _c_), x),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=9,
    ),
    # Rule 10
    RubiRulePattern(
        pattern=Int((x**n_*_b_ + a_)**p_*cosh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, n_, p_], x),),
        replacement=Unintegrable((x**n_*_b_ + a_)**p_*cosh(x*_d_ + _c_), x),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=10,
    ),
    # Rule 11
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*(x**n_*_b_ + a_)**_p_*sinh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _m_, n_], x), IGtQ(_p_, 0),),
        replacement=Int(ExpandIntegrand(sinh(x*_d_ + _c_), (x*_e_)**_m_*(x**n_*_b_ + a_)**_p_, x), x),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=11,
    ),
    # Rule 12
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*(x**n_*_b_ + a_)**_p_*cosh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _m_, n_], x), IGtQ(_p_, 0),),
        replacement=Int(ExpandIntegrand(cosh(x*_d_ + _c_), (x*_e_)**_m_*(x**n_*_b_ + a_)**_p_, x), x),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=12,
    ),
    # Rule 13
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*(x**n_*_b_ + a_)**p_*sinh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _m_, n_], x), IntegerQ(p_), EqQ(_m_ - n_ + 1, 0), LtQ(p_, -1), Or(IntegerQ(n_), GtQ(_e_, 0)),),
        replacement=-_d_*_e_**_m_*Int((x**n_*_b_ + a_)**(p_ + 1)*cosh(x*_d_ + _c_), x)/(_b_*n_*(p_ + 1)) + _e_**_m_*(x**n_*_b_ + a_)**(p_ + 1)*sinh(x*_d_ + _c_)/(_b_*n_*(p_ + 1)),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=13,
    ),
    # Rule 14
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*(x**n_*_b_ + a_)**p_*cosh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _m_, n_], x), IntegerQ(p_), EqQ(_m_ - n_ + 1, 0), LtQ(p_, -1), Or(IntegerQ(n_), GtQ(_e_, 0)),),
        replacement=-_d_*_e_**_m_*Int((x**n_*_b_ + a_)**(p_ + 1)*sinh(x*_d_ + _c_), x)/(_b_*n_*(p_ + 1)) + _e_**_m_*(x**n_*_b_ + a_)**(p_ + 1)*cosh(x*_d_ + _c_)/(_b_*n_*(p_ + 1)),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=14,
    ),
    # Rule 15
    RubiRulePattern(
        pattern=Int(x**_m_*(x**n_*_b_ + a_)**p_*sinh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_], x), ILtQ(p_, -1), IGtQ(n_, 0), RationalQ(_m_), Or(GtQ(_m_ - n_ + 1, 0), GtQ(n_, 2)),),
        replacement=x**(_m_ - n_ + 1)*(x**n_*_b_ + a_)**(p_ + 1)*sinh(x*_d_ + _c_)/(_b_*n_*(p_ + 1)) - _d_*Int(x**(_m_ - n_ + 1)*(x**n_*_b_ + a_)**(p_ + 1)*cosh(x*_d_ + _c_), x)/(_b_*n_*(p_ + 1)) - (_m_ - n_ + 1)*Int(x**(_m_ - n_)*(x**n_*_b_ + a_)**(p_ + 1)*sinh(x*_d_ + _c_), x)/(_b_*n_*(p_ + 1)),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=15,
    ),
    # Rule 16
    RubiRulePattern(
        pattern=Int(x**_m_*(x**n_*_b_ + a_)**p_*cosh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_], x), ILtQ(p_, -1), IGtQ(n_, 0), RationalQ(_m_), Or(GtQ(_m_ - n_ + 1, 0), GtQ(n_, 2)),),
        replacement=x**(_m_ - n_ + 1)*(x**n_*_b_ + a_)**(p_ + 1)*cosh(x*_d_ + _c_)/(_b_*n_*(p_ + 1)) - _d_*Int(x**(_m_ - n_ + 1)*(x**n_*_b_ + a_)**(p_ + 1)*sinh(x*_d_ + _c_), x)/(_b_*n_*(p_ + 1)) - (_m_ - n_ + 1)*Int(x**(_m_ - n_)*(x**n_*_b_ + a_)**(p_ + 1)*cosh(x*_d_ + _c_), x)/(_b_*n_*(p_ + 1)),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=16,
    ),
    # Rule 17
    RubiRulePattern(
        pattern=Int(x**_m_*(x**n_*_b_ + a_)**p_*sinh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_], x), ILtQ(p_, 0), IntegerQ(_m_), IGtQ(n_, 0), Or(EqQ(n_, 2), EqQ(p_, -1)),),
        replacement=Int(ExpandIntegrand(sinh(x*_d_ + _c_), x**_m_*(x**n_*_b_ + a_)**p_, x), x),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=17,
    ),
    # Rule 18
    RubiRulePattern(
        pattern=Int(x**_m_*(x**n_*_b_ + a_)**p_*cosh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_], x), ILtQ(p_, 0), IntegerQ(_m_), IGtQ(n_, 0), Or(EqQ(n_, 2), EqQ(p_, -1)),),
        replacement=Int(ExpandIntegrand(cosh(x*_d_ + _c_), x**_m_*(x**n_*_b_ + a_)**p_, x), x),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=18,
    ),
    # Rule 19
    RubiRulePattern(
        pattern=Int(x**_m_*(x**n_*_b_ + a_)**p_*sinh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _m_], x), ILtQ(p_, 0), ILtQ(n_, 0),),
        replacement=Int(x**(_m_ + n_*p_)*(_b_ + a_/x**n_)**p_*sinh(x*_d_ + _c_), x),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=19,
    ),
    # Rule 20
    RubiRulePattern(
        pattern=Int(x**_m_*(x**n_*_b_ + a_)**p_*cosh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _m_], x), ILtQ(p_, 0), ILtQ(n_, 0),),
        replacement=Int(x**(_m_ + n_*p_)*(_b_ + a_/x**n_)**p_*cosh(x*_d_ + _c_), x),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=20,
    ),
    # Rule 21
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*(x**n_*_b_ + a_)**_p_*sinh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _m_, n_, _p_], x),),
        replacement=Unintegrable((x*_e_)**_m_*(x**n_*_b_ + a_)**_p_*sinh(x*_d_ + _c_), x),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=21,
    ),
    # Rule 22
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*(x**n_*_b_ + a_)**_p_*cosh(x*_d_ + _c_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _e_, _m_, n_, _p_], x),),
        replacement=Unintegrable((x*_e_)**_m_*(x**n_*_b_ + a_)**_p_*cosh(x*_d_ + _c_), x),
        module_name='6.1.11 (e x)^m (a+b x^n)^p sinh',
        rule_number=22,
    ),

]

# Summary: 22 rules translated, 0 skipped
