# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_rules/codegen/generate.py
# Source: 7.1.6 Miscellaneous inverse hyperbolic sine.m
# Module: 7.1.6 Miscellaneous inverse hyperbolic sine
#
# This file contains Rubi integration rules as RubiRulePattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Integer, Integral, Lambda, Rational, Symbol, Tuple as SympyTuple
from rubi_rules.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (
    Abs, Chi, Ci, Ei, Eq, Ge, Gt, I, Le, Lt, Ne, Shi, Si, acos, acosh, acot, acoth, acsc, acsch,
    appellf1, asec, asech, asin, asinh, atan, atan2, atanh, besselj, cos, cosh, cot, coth, csc,
    csch, denom, diff, elliptic_e, elliptic_f, erf, erfc, erfi, exp, expint, factorial, floor, frac,
    fresnelc, fresnels, hyper, li, log, loggamma, oo, pi, polygamma, polylog, root, sec, sech,
    simplify, sin, sinh, sqrt, tan, tanh, zeta,
)

from sympy_matching.wild import WildSymbol, WildHeadApp, WildHeadDeriv, HeadRef, IDENTITY_ELEMENT
from rubi_rules.base_objects import Int, RubiRulePattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_rules.utils.inert_functions import (
    InertSin, InertCos, InertTan, InertCot, InertSec, InertCsc)
from rubi_rules.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, OddQ, EvenQ, NumberQ, NumericQ, AtomQ, MemberQ,
    PositiveQ, NegativeQ, PolynomialQ, TrueQ, FalseQ, MatchQ, PrimeQ, UnsameQ,
    # RUBI-specific constraints
    EqQ, NeQ, IGtQ, ILtQ, IGeQ, ILeQ, GtQ, LtQ, GeQ, LeQ, PosQ, NegQ,
    IntegersQ, HalfIntegerQ, FractionQ, RationalQ, ComplexNumberQ, RealNumberQ,
    FractionOrNegativeQ, SqrtNumberQ, PowerQ, ProductQ, SumQ, NonsumQ,
    IntegerPowerQ, FractionalPowerQ, PolyQ, LinearQ, QuadraticQ, BinomialQ,
    TrinomialQ, LinearMatchQ, QuadraticMatchQ, BinomialMatchQ, TrinomialMatchQ,
    TrigQ, HyperbolicQ, InverseTrigQ, InverseHyperbolicQ, LogQ, ComplexFreeQ,
    InverseFunctionFreeQ, FractionalPowerFreeQ, TrigHyperbolicFreeQ, IntegralFreeQ,
    RationalFunctionQ, AlgebraicFunctionQ, IndependentQ, SimplerQ, SumSimplerQ,
    FunctionOfQ, PiecewiseLinearQ, ExpressionEqQ,
    IntLinearQ, IntBinomialQ, IntQuadraticQ,
    MonomialQ, LinearPairQ,
    GeneralizedBinomialQ, GeneralizedBinomialMatchQ,
    GeneralizedTrinomialQ, GeneralizedTrinomialMatchQ,
    NiceSqrtQ, SimplerSqrtQ, FractionalPowerFactorQ,
    SumBaseQ, InverseFunctionQ, InertTrigQ, InertTrigFreeQ,
    CalculusFreeQ, QuotientOfLinearsQ,
    PowerOfLinearQ, PowerOfLinearMatchQ,
    FunctionOfExponentialQ,
    KnownSineIntegrandQ, KnownSecantIntegrandQ,
    KnownTangentIntegrandQ, KnownCotangentIntegrandQ,
    EulerIntegrandQ, SubstForFractionalPowerQ,
    PerfectSquareQ, PolynomialInQ, FunctionOfTrigOfLinearQ,
    SimplerIntegrandQ, PseudoBinomialPairQ, QuadraticProductQ,
    EveryQ, TrigSimplifyQ, EqM, TryPureTanSubst,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

w = Symbol('w')

_A_ = WildSymbol('A', optional_value=IDENTITY_ELEMENT)
A_ = WildSymbol('A')
_B_ = WildSymbol('B', optional_value=IDENTITY_ELEMENT)
B_ = WildSymbol('B')
_C_ = WildSymbol('C', optional_value=IDENTITY_ELEMENT)
C_ = WildSymbol('C')
_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
_f_ = WildSymbol('f', optional_value=IDENTITY_ELEMENT)
f_ = WildSymbol('f')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')
_p_ = WildSymbol('p', optional_value=IDENTITY_ELEMENT)
p_ = WildSymbol('p')
_u_ = WildSymbol('u', optional_value=IDENTITY_ELEMENT)
u_ = WildSymbol('u')
v_ = WildSymbol('v')

RULES = [
    # Rule 1
    RubiRulePattern(
        pattern=Int((_a_ + _b_*asinh(x*_d_ + c_))**_n_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _n_], x),),
        replacement=Subst(Int((_a_ + _b_*asinh(x))**_n_, x), x, x*_d_ + c_)/_d_,
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=1,
    ),
    # Rule 2
    RubiRulePattern(
        pattern=Int((_a_ + _b_*asinh(x*_d_ + c_))**_n_*(x*_f_ + _e_)**_m_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _e_, _f_, _m_, _n_], x),),
        replacement=Subst(Int((_a_ + _b_*asinh(x))**_n_*(x*_f_/_d_ + (-c_*_f_ + _d_*_e_)/_d_)**_m_, x), x, x*_d_ + c_)/_d_,
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=2,
    ),
    # Rule 3
    RubiRulePattern(
        pattern=Int((_a_ + _b_*asinh(x*_d_ + c_))**_n_*(x**2*_C_ + x*_B_ + _A_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _A_, _B_, _C_, _n_, _p_], x), EqQ(-2*_A_*c_*_d_ + _B_*(c_**2 + 1), 0), EqQ(-_B_*_d_ + 2*_C_*c_, 0),),
        replacement=Subst(Int((_a_ + _b_*asinh(x))**_n_*(x**2*_C_/_d_**2 + _C_/_d_**2)**_p_, x), x, x*_d_ + c_)/_d_,
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=3,
    ),
    # Rule 4
    RubiRulePattern(
        pattern=Int((_a_ + _b_*asinh(x*_d_ + c_))**_n_*(x*_f_ + _e_)**_m_*(x**2*_C_ + x*_B_ + _A_)**_p_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _e_, _f_, _A_, _B_, _C_, _m_, _n_, _p_], x), EqQ(-2*_A_*c_*_d_ + _B_*(c_**2 + 1), 0), EqQ(-_B_*_d_ + 2*_C_*c_, 0),),
        replacement=Subst(Int((_a_ + _b_*asinh(x))**_n_*(x*_f_/_d_ + (-c_*_f_ + _d_*_e_)/_d_)**_m_*(x**2*_C_/_d_**2 + _C_/_d_**2)**_p_, x), x, x*_d_ + c_)/_d_,
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=4,
    ),
    # Rule 5
    RubiRulePattern(
        pattern=Int(sqrt(_a_ + _b_*asinh(x**2*_d_ + c_)), x),
        constraints=(FreeQ([_a_, _b_, c_, _d_], x), EqQ(c_**2, -1),),
        replacement=x*sqrt(_a_ + _b_*asinh(x**2*_d_ + c_)) - sqrt(pi)*x*(-c_*sinh(_a_/(2*_b_)) + cosh(_a_/(2*_b_)))*fresnelc(sqrt(-c_/_b_)*sqrt(_a_ + _b_*asinh(x**2*_d_ + c_))/sqrt(pi))/(sqrt(-c_/_b_)*(c_*sinh(asinh(x**2*_d_ + c_)/2) + cosh(asinh(x**2*_d_ + c_)/2))) + sqrt(pi)*x*(c_*sinh(_a_/(2*_b_)) + cosh(_a_/(2*_b_)))*fresnels(sqrt(-c_/_b_)*sqrt(_a_ + _b_*asinh(x**2*_d_ + c_))/sqrt(pi))/(sqrt(-c_/_b_)*(c_*sinh(asinh(x**2*_d_ + c_)/2) + cosh(asinh(x**2*_d_ + c_)/2))),
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=5,
    ),
    # Rule 6
    RubiRulePattern(
        pattern=Int((_a_ + _b_*asinh(x**2*_d_ + c_))**n_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_], x), EqQ(c_**2, -1), GtQ(n_, 1),),
        replacement=x*(_a_ + _b_*asinh(x**2*_d_ + c_))**n_ + 4*_b_**2*n_*(n_ - 1)*Int((_a_ + _b_*asinh(x**2*_d_ + c_))**(n_ - 2), x) - 2*_b_*n_*(_a_ + _b_*asinh(x**2*_d_ + c_))**(n_ - 1)*sqrt(x**4*_d_**2 + 2*x**2*c_*_d_)/(x*_d_),
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=6,
    ),
    # Rule 7
    RubiRulePattern(
        pattern=Int(1/(_a_ + _b_*asinh(x**2*_d_ + c_)), x),
        constraints=(FreeQ([_a_, _b_, c_, _d_], x), EqQ(c_**2, -1),),
        replacement=x*(-c_*sinh(_a_/(2*_b_)) + cosh(_a_/(2*_b_)))*Shi((_a_ + _b_*asinh(x**2*_d_ + c_))/(2*_b_))/(2*_b_*(c_*sinh(asinh(x**2*_d_ + c_)/2) + cosh(asinh(x**2*_d_ + c_)/2))) + x*(c_*cosh(_a_/(2*_b_)) - sinh(_a_/(2*_b_)))*Chi((_a_ + _b_*asinh(x**2*_d_ + c_))/(2*_b_))/(2*_b_*(c_*sinh(asinh(x**2*_d_ + c_)/2) + cosh(asinh(x**2*_d_ + c_)/2))),
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=7,
    ),
    # Rule 8
    RubiRulePattern(
        pattern=Int(1/sqrt(_a_ + _b_*asinh(x**2*_d_ + c_)), x),
        constraints=(FreeQ([_a_, _b_, c_, _d_], x), EqQ(c_**2, -1),),
        replacement=sqrt(2)*sqrt(pi)*x*(c_ - 1)*(sinh(_a_/(2*_b_)) + cosh(_a_/(2*_b_)))*erf(sqrt(2)*sqrt(_a_ + _b_*asinh(x**2*_d_ + c_))/(2*sqrt(_b_)))/(4*sqrt(_b_)*(c_*sinh(asinh(x**2*_d_ + c_)/2) + cosh(asinh(x**2*_d_ + c_)/2))) + sqrt(2)*sqrt(pi)*x*(c_ + 1)*(-sinh(_a_/(2*_b_)) + cosh(_a_/(2*_b_)))*erfi(sqrt(2)*sqrt(_a_ + _b_*asinh(x**2*_d_ + c_))/(2*sqrt(_b_)))/(4*sqrt(_b_)*(c_*sinh(asinh(x**2*_d_ + c_)/2) + cosh(asinh(x**2*_d_ + c_)/2))),
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=8,
    ),
    # Rule 9
    RubiRulePattern(
        pattern=Int((_a_ + _b_*asinh(x**2*_d_ + c_))**(sympy.S(-3)/2), x),
        constraints=(FreeQ([_a_, _b_, c_, _d_], x), EqQ(c_**2, -1),),
        replacement=-sqrt(pi)*x*(-c_/_b_)**(sympy.S(3)/2)*(-c_*sinh(_a_/(2*_b_)) + cosh(_a_/(2*_b_)))*fresnelc(sqrt(-c_/_b_)*sqrt(_a_ + _b_*asinh(x**2*_d_ + c_))/sqrt(pi))/(c_*sinh(asinh(x**2*_d_ + c_)/2) + cosh(asinh(x**2*_d_ + c_)/2)) + sqrt(pi)*x*(-c_/_b_)**(sympy.S(3)/2)*(c_*sinh(_a_/(2*_b_)) + cosh(_a_/(2*_b_)))*fresnels(sqrt(-c_/_b_)*sqrt(_a_ + _b_*asinh(x**2*_d_ + c_))/sqrt(pi))/(c_*sinh(asinh(x**2*_d_ + c_)/2) + cosh(asinh(x**2*_d_ + c_)/2)) - sqrt(x**4*_d_**2 + 2*x**2*c_*_d_)/(x*_b_*_d_*sqrt(_a_ + _b_*asinh(x**2*_d_ + c_))),
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=9,
    ),
    # Rule 10
    RubiRulePattern(
        pattern=Int((_a_ + _b_*asinh(x**2*_d_ + c_))**(-2), x),
        constraints=(FreeQ([_a_, _b_, c_, _d_], x), EqQ(c_**2, -1),),
        replacement=x*(-c_*sinh(_a_/(2*_b_)) + cosh(_a_/(2*_b_)))*Chi((_a_ + _b_*asinh(x**2*_d_ + c_))/(2*_b_))/(4*_b_**2*(c_*sinh(asinh(x**2*_d_ + c_)/2) + cosh(asinh(x**2*_d_ + c_)/2))) + x*(c_*cosh(_a_/(2*_b_)) - sinh(_a_/(2*_b_)))*Shi((_a_ + _b_*asinh(x**2*_d_ + c_))/(2*_b_))/(4*_b_**2*(c_*sinh(asinh(x**2*_d_ + c_)/2) + cosh(asinh(x**2*_d_ + c_)/2))) - sqrt(x**4*_d_**2 + 2*x**2*c_*_d_)/(2*x*_b_*_d_*(_a_ + _b_*asinh(x**2*_d_ + c_))),
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=10,
    ),
    # Rule 11
    RubiRulePattern(
        pattern=Int((_a_ + _b_*asinh(x**2*_d_ + c_))**n_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_], x), EqQ(c_**2, -1), LtQ(n_, -1), NeQ(n_, -2),),
        replacement=-x*(_a_ + _b_*asinh(x**2*_d_ + c_))**(n_ + 2)/(4*_b_**2*(n_ + 1)*(n_ + 2)) + Int((_a_ + _b_*asinh(x**2*_d_ + c_))**(n_ + 2), x)/(4*_b_**2*(n_ + 1)*(n_ + 2)) + (_a_ + _b_*asinh(x**2*_d_ + c_))**(n_ + 1)*sqrt(x**4*_d_**2 + 2*x**2*c_*_d_)/(2*x*_b_*_d_*(n_ + 1)),
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=11,
    ),
    # Rule 12
    RubiRulePattern(
        pattern=Int(asinh(x**p_*_a_)**_n_/x, x),
        constraints=(FreeQ([_a_, p_], x), IGtQ(_n_, 0),),
        replacement=Subst(Int(x**_n_*coth(x), x), x, asinh(x**p_*_a_))/p_,
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=12,
    ),
    # Rule 13
    RubiRulePattern(
        pattern=Int(_u_*asinh(_c_/(x**_n_*_b_ + _a_))**_m_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _n_, _m_], x),),
        replacement=Int(_u_*acsch(x**_n_*_b_/_c_ + _a_/_c_)**_m_, x),
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=13,
    ),
    # Rule 14
    RubiRulePattern(
        pattern=Int(asinh(sqrt(x**2*_b_ - 1))**_n_/sqrt(x**2*_b_ - 1), x),
        constraints=(FreeQ([_b_, _n_], x),),
        replacement=sqrt(x**2*_b_)*Subst(Int(asinh(x)**_n_/sqrt(x**2 + 1), x), x, sqrt(x**2*_b_ - 1))/(x*_b_),
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=14,
    ),
    # Rule 15
    RubiRulePattern(
        pattern=Int(f_**(_c_*asinh(x*_b_ + _a_)**_n_), x),
        constraints=(FreeQ([_a_, _b_, _c_, f_], x), IGtQ(_n_, 0),),
        replacement=Subst(Int(f_**(x**_n_*_c_)*cosh(x), x), x, asinh(x*_b_ + _a_))/_b_,
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=15,
    ),
    # Rule 16
    RubiRulePattern(
        pattern=Int(x**_m_*f_**(_c_*asinh(x*_b_ + _a_)**_n_), x),
        constraints=(FreeQ([_a_, _b_, _c_, f_], x), IGtQ(_m_, 0), IGtQ(_n_, 0),),
        replacement=Subst(Int(f_**(x**_n_*_c_)*(-_a_/_b_ + sinh(x)/_b_)**_m_*cosh(x), x), x, asinh(x*_b_ + _a_))/_b_,
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=16,
    ),
    # Rule 17
    RubiRulePattern(
        pattern=Int(asinh(u_), x),
        constraints=(InverseFunctionFreeQ(u_, x), Not(FunctionOfExponentialQ(u_, x)),),
        replacement=x*asinh(u_) - Int(SimplifyIntegrand(x*D(u_, x)/sqrt(u_**2 + 1), x), x),
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=17,
    ),
    # Rule 18
    RubiRulePattern(
        pattern=Int((_a_ + _b_*asinh(u_))*(x*_d_ + _c_)**_m_, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _m_], x), NeQ(_m_, -1), InverseFunctionFreeQ(u_, x), Not(FunctionOfQ((x*_d_ + _c_)**(_m_ + 1), u_, x)), Not(FunctionOfExponentialQ(u_, x)),),
        replacement=-_b_*Int(SimplifyIntegrand((x*_d_ + _c_)**(_m_ + 1)*D(u_, x)/sqrt(u_**2 + 1), x), x)/(_d_*(_m_ + 1)) + (_a_ + _b_*asinh(u_))*(x*_d_ + _c_)**(_m_ + 1)/(_d_*(_m_ + 1)),
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=18,
    ),
    # Rule 19
    RubiRulePattern(
        pattern=Int(v_*(_a_ + _b_*asinh(u_)), x),
        constraints=(FreeQ([_a_, _b_], x), InverseFunctionFreeQ(u_, x), Not(MatchQ(v_, Condition(((_c_ + (_d_ * x)))**(_m_), FreeQ([_c_, _d_, _m_], x)))), InverseFunctionFreeQ(IntHide(v_, x), x),),
        replacement=With({w: IntHide(v_, x)}, -_b_*Int(SimplifyIntegrand(w*D(u_, x)/sqrt(u_**2 + 1), x), x) + Dist(_a_ + _b_*asinh(u_), w, x)),
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=19,
    ),
    # Rule 20
    RubiRulePattern(
        pattern=Int(exp(_n_*asinh(u_)), x),
        constraints=(IntegerQ(_n_), PolyQ(u_, x),),
        replacement=Int((u_ + sqrt(u_**2 + 1))**_n_, x),
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=20,
    ),
    # Rule 21
    RubiRulePattern(
        pattern=Int(x**_m_*exp(_n_*asinh(u_)), x),
        constraints=(RationalQ(_m_), IntegerQ(_n_), PolyQ(u_, x),),
        replacement=Int(x**_m_*(u_ + sqrt(u_**2 + 1))**_n_, x),
        module_name='7.1.6 Miscellaneous inverse hyperbolic sine',
        rule_number=21,
    ),

]

# Summary: 21 rules translated, 0 skipped
