# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_rules/codegen/generate.py
# Source: 8.5 Hyperbolic integral functions.m
# Module: 8.5 Hyperbolic integral functions
#
# This file contains Rubi integration rules as RubiRulePattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Integer, Integral, Lambda, Rational, Symbol, Tuple as SympyTuple, Eq, Ne, Lt, Gt, Le, Ge, log, sqrt, pi, I, oo
from rubi_rules.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (sin, cos, tan, sec, csc, cot, asin, acos, atan, atan2, asec, acsc, acot,
                   sinh, cosh, tanh, sech, csch, coth, asinh, acosh, atanh, asech, acsch, acoth,
                   exp, Abs, diff, denom, frac, floor, root, simplify,
                   elliptic_e, elliptic_f, hyper, appellf1)

from sympy_matching.wild import WildSymbol, WildHeadApp, WildHeadDeriv, IDENTITY_ELEMENT
from rubi_rules.base_objects import Int, RubiRulePattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_rules.utils.inert_functions import (
    InertSin, InertCos, InertTan, InertCot, InertSec, InertCsc)
from rubi_rules.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, OddQ, EvenQ, NumberQ, NumericQ, AtomQ, MemberQ,
    PositiveQ, NegativeQ, PolynomialQ, TrueQ, FalseQ, MatchQ, PrimeQ, UnsameQ,
    # RUBI-specific constraints
    EqQ, NeQ, IGtQ, ILtQ, IGeQ, ILeQ, GtQ, LtQ, GeQ, LeQ, PosQ, NegQ,
    IntegersQ, HalfIntegerQ, FractionQ, RationalQ, ComplexNumberQ, RealNumberQ,
    FractionOrNegativeQ, SqrtNumberQ, PowerQ, ProductQ, SumQ, NonsumQ,
    IntegerPowerQ, FractionalPowerQ, PolyQ, LinearQ, QuadraticQ, BinomialQ,
    TrinomialQ, LinearMatchQ, QuadraticMatchQ, BinomialMatchQ, TrinomialMatchQ,
    TrigQ, HyperbolicQ, InverseTrigQ, InverseHyperbolicQ, LogQ, ComplexFreeQ,
    InverseFunctionFreeQ, FractionalPowerFreeQ, TrigHyperbolicFreeQ, IntegralFreeQ,
    RationalFunctionQ, AlgebraicFunctionQ, IndependentQ, SimplerQ, SumSimplerQ,
    FunctionOfQ, PiecewiseLinearQ, ExpressionEqQ,
    IntLinearQ, IntBinomialQ, IntQuadraticQ,
    MonomialQ, LinearPairQ,
    GeneralizedBinomialQ, GeneralizedBinomialMatchQ,
    GeneralizedTrinomialQ, GeneralizedTrinomialMatchQ,
    NiceSqrtQ, SimplerSqrtQ, FractionalPowerFactorQ,
    SumBaseQ, InverseFunctionQ, InertTrigQ, InertTrigFreeQ,
    CalculusFreeQ, QuotientOfLinearsQ,
    PowerOfLinearQ, PowerOfLinearMatchQ,
    FunctionOfExponentialQ,
    KnownSineIntegrandQ, KnownSecantIntegrandQ,
    KnownTangentIntegrandQ, KnownCotangentIntegrandQ,
    EulerIntegrandQ, SubstForFractionalPowerQ,
    PerfectSquareQ, PolynomialInQ, FunctionOfTrigOfLinearQ,
    SimplerIntegrandQ, PseudoBinomialPairQ, QuadraticProductQ,
    EveryQ, TrigSimplifyQ, EqM, TryPureTanSubst,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

F_ = WildSymbol('F')
_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
_f_ = WildSymbol('f', optional_value=IDENTITY_ELEMENT)
f_ = WildSymbol('f')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')

RULES = [
    # Rule 1
    RubiRulePattern(
        pattern=Int(sympy.Function('SinhIntegral')((_a_ + (_b_ * x))), x),
        constraints=(FreeQ([_a_, _b_], x),),
        replacement=(((_a_ + (_b_ * x)) * sympy.Shi((_a_ + (_b_ * x))) * (_b_)**(Integer(-1))) + (Integer(-1) * (sympy.cosh((_a_ + (_b_ * x))) * (_b_)**(Integer(-1))))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=1,
    ),
    # Rule 2
    RubiRulePattern(
        pattern=Int(sympy.Function('CoshIntegral')((_a_ + (_b_ * x))), x),
        constraints=(FreeQ([_a_, _b_], x),),
        replacement=(((_a_ + (_b_ * x)) * sympy.Chi((_a_ + (_b_ * x))) * (_b_)**(Integer(-1))) + (Integer(-1) * (sympy.sinh((_a_ + (_b_ * x))) * (_b_)**(Integer(-1))))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=2,
    ),
    # Rule 3
    RubiRulePattern(
        pattern=Int((sympy.Function('SinhIntegral')((_b_ * x)) * (x)**(Integer(-1))), x),
        constraints=(FreeQ(_b_, x),),
        replacement=x*_b_*hyper((1, 1, 1), (2, 2, 2), -x*_b_)/2 + x*_b_*hyper((1, 1, 1), (2, 2, 2), x*_b_)/2,
        module_name='8.5 Hyperbolic integral functions',
        rule_number=3,
    ),
    # Rule 4
    RubiRulePattern(
        pattern=Int((sympy.Function('CoshIntegral')((_b_ * x)) * (x)**(Integer(-1))), x),
        constraints=(FreeQ(_b_, x),),
        replacement=((Integer(-1) * (Integer(2))**(Integer(-1)) * _b_ * x * sympy.hyper(List(Integer(1), Integer(1), Integer(1)), List(Integer(2), Integer(2), Integer(2)), ((Integer(-1) * _b_) * x))) + ((Integer(2))**(Integer(-1)) * _b_ * x * sympy.hyper(List(Integer(1), Integer(1), Integer(1)), List(Integer(2), Integer(2), Integer(2)), (_b_ * x))) + (sympy.EulerGamma * sympy.log(x)) + ((Integer(2))**(Integer(-1)) * (sympy.log((_b_ * x)))**(Integer(2)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=4,
    ),
    # Rule 5
    RubiRulePattern(
        pattern=Int((((_c_ + (_d_ * x)))**(_m_) * sympy.Function('SinhIntegral')((_a_ + (_b_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _m_], x), NeQ(_m_, -1),),
        replacement=((((_c_ + (_d_ * x)))**((_m_ + Integer(1))) * sympy.Shi((_a_ + (_b_ * x))) * ((_d_ * (_m_ + Integer(1))))**(Integer(-1))) + (Integer(-1) * (_b_ * ((_d_ * (_m_ + Integer(1))))**(Integer(-1)) * Int((((_c_ + (_d_ * x)))**((_m_ + Integer(1))) * sympy.sinh((_a_ + (_b_ * x))) * ((_a_ + (_b_ * x)))**(Integer(-1))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=5,
    ),
    # Rule 6
    RubiRulePattern(
        pattern=Int((((_c_ + (_d_ * x)))**(_m_) * sympy.Function('CoshIntegral')((_a_ + (_b_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _m_], x), NeQ(_m_, -1),),
        replacement=((((_c_ + (_d_ * x)))**((_m_ + Integer(1))) * sympy.Chi((_a_ + (_b_ * x))) * ((_d_ * (_m_ + Integer(1))))**(Integer(-1))) + (Integer(-1) * (_b_ * ((_d_ * (_m_ + Integer(1))))**(Integer(-1)) * Int((((_c_ + (_d_ * x)))**((_m_ + Integer(1))) * sympy.cosh((_a_ + (_b_ * x))) * ((_a_ + (_b_ * x)))**(Integer(-1))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=6,
    ),
    # Rule 7
    RubiRulePattern(
        pattern=Int((sympy.Function('SinhIntegral')((_a_ + (_b_ * x))))**(Integer(2)), x),
        constraints=(FreeQ([_a_, _b_], x),),
        replacement=(((_a_ + (_b_ * x)) * (sympy.Shi((_a_ + (_b_ * x))))**(Integer(2)) * (_b_)**(Integer(-1))) + (Integer(-1) * (Integer(2) * Int((sympy.sinh((_a_ + (_b_ * x))) * sympy.Shi((_a_ + (_b_ * x)))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=7,
    ),
    # Rule 8
    RubiRulePattern(
        pattern=Int((sympy.Function('CoshIntegral')((_a_ + (_b_ * x))))**(Integer(2)), x),
        constraints=(FreeQ([_a_, _b_], x),),
        replacement=(((_a_ + (_b_ * x)) * (sympy.Chi((_a_ + (_b_ * x))))**(Integer(2)) * (_b_)**(Integer(-1))) + (Integer(-1) * (Integer(2) * Int((sympy.cosh((_a_ + (_b_ * x))) * sympy.Chi((_a_ + (_b_ * x)))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=8,
    ),
    # Rule 9
    RubiRulePattern(
        pattern=Int(((x)**(_m_) * (sympy.Function('SinhIntegral')((_b_ * x)))**(Integer(2))), x),
        constraints=(FreeQ(_b_, x), IGtQ(_m_, 0),),
        replacement=(((x)**((_m_ + Integer(1))) * (sympy.Shi((_b_ * x)))**(Integer(2)) * ((_m_ + Integer(1)))**(Integer(-1))) + (Integer(-1) * (Integer(2) * ((_m_ + Integer(1)))**(Integer(-1)) * Int(((x)**(_m_) * sympy.sinh((_b_ * x)) * sympy.Shi((_b_ * x))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=9,
    ),
    # Rule 10
    RubiRulePattern(
        pattern=Int(((x)**(_m_) * (sympy.Function('CoshIntegral')((_b_ * x)))**(Integer(2))), x),
        constraints=(FreeQ(_b_, x), IGtQ(_m_, 0),),
        replacement=(((x)**((_m_ + Integer(1))) * (sympy.Chi((_b_ * x)))**(Integer(2)) * ((_m_ + Integer(1)))**(Integer(-1))) + (Integer(-1) * (Integer(2) * ((_m_ + Integer(1)))**(Integer(-1)) * Int(((x)**(_m_) * sympy.cosh((_b_ * x)) * sympy.Chi((_b_ * x))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=10,
    ),
    # Rule 11
    RubiRulePattern(
        pattern=Int((((_c_ + (_d_ * x)))**(_m_) * (sympy.Function('SinhIntegral')((a_ + (_b_ * x))))**(Integer(2))), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_], x), IGtQ(_m_, 0),),
        replacement=(((a_ + (_b_ * x)) * ((_c_ + (_d_ * x)))**(_m_) * (sympy.Shi((a_ + (_b_ * x))))**(Integer(2)) * ((_b_ * (_m_ + Integer(1))))**(Integer(-1))) + (Integer(-1) * (Integer(2) * ((_m_ + Integer(1)))**(Integer(-1)) * Int((((_c_ + (_d_ * x)))**(_m_) * sympy.sinh((a_ + (_b_ * x))) * sympy.Shi((a_ + (_b_ * x)))), x))) + (((_b_ * _c_) + (Integer(-1) * (a_ * _d_))) * _m_ * ((_b_ * (_m_ + Integer(1))))**(Integer(-1)) * Int((((_c_ + (_d_ * x)))**((_m_ + Integer(-1))) * (sympy.Shi((a_ + (_b_ * x))))**(Integer(2))), x))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=11,
    ),
    # Rule 12
    RubiRulePattern(
        pattern=Int((((_c_ + (_d_ * x)))**(_m_) * (sympy.Function('CoshIntegral')((a_ + (_b_ * x))))**(Integer(2))), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_], x), IGtQ(_m_, 0),),
        replacement=(((a_ + (_b_ * x)) * ((_c_ + (_d_ * x)))**(_m_) * (sympy.Chi((a_ + (_b_ * x))))**(Integer(2)) * ((_b_ * (_m_ + Integer(1))))**(Integer(-1))) + (Integer(-1) * (Integer(2) * ((_m_ + Integer(1)))**(Integer(-1)) * Int((((_c_ + (_d_ * x)))**(_m_) * sympy.cosh((a_ + (_b_ * x))) * sympy.Chi((a_ + (_b_ * x)))), x))) + (((_b_ * _c_) + (Integer(-1) * (a_ * _d_))) * _m_ * ((_b_ * (_m_ + Integer(1))))**(Integer(-1)) * Int((((_c_ + (_d_ * x)))**((_m_ + Integer(-1))) * (sympy.Chi((a_ + (_b_ * x))))**(Integer(2))), x))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=12,
    ),
    # Rule 13
    RubiRulePattern(
        pattern=Int((sympy.sinh((_a_ + (_b_ * x))) * sympy.Function('SinhIntegral')((_c_ + (_d_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_], x),),
        replacement=((sympy.cosh((_a_ + (_b_ * x))) * sympy.Shi((_c_ + (_d_ * x))) * (_b_)**(Integer(-1))) + (Integer(-1) * (_d_ * (_b_)**(Integer(-1)) * Int((sympy.cosh((_a_ + (_b_ * x))) * sympy.sinh((_c_ + (_d_ * x))) * ((_c_ + (_d_ * x)))**(Integer(-1))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=13,
    ),
    # Rule 14
    RubiRulePattern(
        pattern=Int((sympy.cosh((_a_ + (_b_ * x))) * sympy.Function('CoshIntegral')((_c_ + (_d_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_], x),),
        replacement=((sympy.sinh((_a_ + (_b_ * x))) * sympy.Chi((_c_ + (_d_ * x))) * (_b_)**(Integer(-1))) + (Integer(-1) * (_d_ * (_b_)**(Integer(-1)) * Int((sympy.sinh((_a_ + (_b_ * x))) * sympy.cosh((_c_ + (_d_ * x))) * ((_c_ + (_d_ * x)))**(Integer(-1))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=14,
    ),
    # Rule 15
    RubiRulePattern(
        pattern=Int((((_e_ + (_f_ * x)))**(_m_) * sympy.sinh((_a_ + (_b_ * x))) * sympy.Function('SinhIntegral')((_c_ + (_d_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), IGtQ(_m_, 0),),
        replacement=((((_e_ + (_f_ * x)))**(_m_) * sympy.cosh((_a_ + (_b_ * x))) * sympy.Shi((_c_ + (_d_ * x))) * (_b_)**(Integer(-1))) + (Integer(-1) * (_d_ * (_b_)**(Integer(-1)) * Int((((_e_ + (_f_ * x)))**(_m_) * sympy.cosh((_a_ + (_b_ * x))) * sympy.sinh((_c_ + (_d_ * x))) * ((_c_ + (_d_ * x)))**(Integer(-1))), x))) + (Integer(-1) * (_f_ * _m_ * (_b_)**(Integer(-1)) * Int((((_e_ + (_f_ * x)))**((_m_ + Integer(-1))) * sympy.cosh((_a_ + (_b_ * x))) * sympy.Shi((_c_ + (_d_ * x)))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=15,
    ),
    # Rule 16
    RubiRulePattern(
        pattern=Int((((_e_ + (_f_ * x)))**(_m_) * sympy.cosh((_a_ + (_b_ * x))) * sympy.Function('CoshIntegral')((_c_ + (_d_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), IGtQ(_m_, 0),),
        replacement=((((_e_ + (_f_ * x)))**(_m_) * sympy.sinh((_a_ + (_b_ * x))) * sympy.Chi((_c_ + (_d_ * x))) * (_b_)**(Integer(-1))) + (Integer(-1) * (_d_ * (_b_)**(Integer(-1)) * Int((((_e_ + (_f_ * x)))**(_m_) * sympy.sinh((_a_ + (_b_ * x))) * sympy.cosh((_c_ + (_d_ * x))) * ((_c_ + (_d_ * x)))**(Integer(-1))), x))) + (Integer(-1) * (_f_ * _m_ * (_b_)**(Integer(-1)) * Int((((_e_ + (_f_ * x)))**((_m_ + Integer(-1))) * sympy.sinh((_a_ + (_b_ * x))) * sympy.Chi((_c_ + (_d_ * x)))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=16,
    ),
    # Rule 17
    RubiRulePattern(
        pattern=Int((((_e_ + (_f_ * x)))**(m_) * sympy.sinh((_a_ + (_b_ * x))) * sympy.Function('SinhIntegral')((_c_ + (_d_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), ILtQ(m_, -1),),
        replacement=((((_e_ + (_f_ * x)))**((m_ + Integer(1))) * sympy.sinh((_a_ + (_b_ * x))) * sympy.Shi((_c_ + (_d_ * x))) * ((_f_ * (m_ + Integer(1))))**(Integer(-1))) + (Integer(-1) * (_d_ * ((_f_ * (m_ + Integer(1))))**(Integer(-1)) * Int((((_e_ + (_f_ * x)))**((m_ + Integer(1))) * sympy.sinh((_a_ + (_b_ * x))) * sympy.sinh((_c_ + (_d_ * x))) * ((_c_ + (_d_ * x)))**(Integer(-1))), x))) + (Integer(-1) * (_b_ * ((_f_ * (m_ + Integer(1))))**(Integer(-1)) * Int((((_e_ + (_f_ * x)))**((m_ + Integer(1))) * sympy.cosh((_a_ + (_b_ * x))) * sympy.Shi((_c_ + (_d_ * x)))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=17,
    ),
    # Rule 18
    RubiRulePattern(
        pattern=Int((((_e_ + (_f_ * x)))**(_m_) * sympy.cosh((_a_ + (_b_ * x))) * sympy.Function('CoshIntegral')((_c_ + (_d_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), ILtQ(_m_, -1),),
        replacement=((((_e_ + (_f_ * x)))**((_m_ + Integer(1))) * sympy.cosh((_a_ + (_b_ * x))) * sympy.Chi((_c_ + (_d_ * x))) * ((_f_ * (_m_ + Integer(1))))**(Integer(-1))) + (Integer(-1) * (_d_ * ((_f_ * (_m_ + Integer(1))))**(Integer(-1)) * Int((((_e_ + (_f_ * x)))**((_m_ + Integer(1))) * sympy.cosh((_a_ + (_b_ * x))) * sympy.cosh((_c_ + (_d_ * x))) * ((_c_ + (_d_ * x)))**(Integer(-1))), x))) + (Integer(-1) * (_b_ * ((_f_ * (_m_ + Integer(1))))**(Integer(-1)) * Int((((_e_ + (_f_ * x)))**((_m_ + Integer(1))) * sympy.sinh((_a_ + (_b_ * x))) * sympy.Chi((_c_ + (_d_ * x)))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=18,
    ),
    # Rule 19
    RubiRulePattern(
        pattern=Int((sympy.cosh((_a_ + (_b_ * x))) * sympy.Function('SinhIntegral')((_c_ + (_d_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_], x),),
        replacement=((sympy.sinh((_a_ + (_b_ * x))) * sympy.Shi((_c_ + (_d_ * x))) * (_b_)**(Integer(-1))) + (Integer(-1) * (_d_ * (_b_)**(Integer(-1)) * Int((sympy.sinh((_a_ + (_b_ * x))) * sympy.sinh((_c_ + (_d_ * x))) * ((_c_ + (_d_ * x)))**(Integer(-1))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=19,
    ),
    # Rule 20
    RubiRulePattern(
        pattern=Int((sympy.sinh((_a_ + (_b_ * x))) * sympy.Function('CoshIntegral')((_c_ + (_d_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_], x),),
        replacement=((sympy.cosh((_a_ + (_b_ * x))) * sympy.Chi((_c_ + (_d_ * x))) * (_b_)**(Integer(-1))) + (Integer(-1) * (_d_ * (_b_)**(Integer(-1)) * Int((sympy.cosh((_a_ + (_b_ * x))) * sympy.cosh((_c_ + (_d_ * x))) * ((_c_ + (_d_ * x)))**(Integer(-1))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=20,
    ),
    # Rule 21
    RubiRulePattern(
        pattern=Int((((_e_ + (_f_ * x)))**(_m_) * sympy.cosh((_a_ + (_b_ * x))) * sympy.Function('SinhIntegral')((_c_ + (_d_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), IGtQ(_m_, 0),),
        replacement=((((_e_ + (_f_ * x)))**(_m_) * sympy.sinh((_a_ + (_b_ * x))) * sympy.Shi((_c_ + (_d_ * x))) * (_b_)**(Integer(-1))) + (Integer(-1) * (_d_ * (_b_)**(Integer(-1)) * Int((((_e_ + (_f_ * x)))**(_m_) * sympy.sinh((_a_ + (_b_ * x))) * sympy.sinh((_c_ + (_d_ * x))) * ((_c_ + (_d_ * x)))**(Integer(-1))), x))) + (Integer(-1) * (_f_ * _m_ * (_b_)**(Integer(-1)) * Int((((_e_ + (_f_ * x)))**((_m_ + Integer(-1))) * sympy.sinh((_a_ + (_b_ * x))) * sympy.Shi((_c_ + (_d_ * x)))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=21,
    ),
    # Rule 22
    RubiRulePattern(
        pattern=Int((((_e_ + (_f_ * x)))**(_m_) * sympy.sinh((_a_ + (_b_ * x))) * sympy.Function('CoshIntegral')((_c_ + (_d_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), IGtQ(_m_, 0),),
        replacement=((((_e_ + (_f_ * x)))**(_m_) * sympy.cosh((_a_ + (_b_ * x))) * sympy.Chi((_c_ + (_d_ * x))) * (_b_)**(Integer(-1))) + (Integer(-1) * (_d_ * (_b_)**(Integer(-1)) * Int((((_e_ + (_f_ * x)))**(_m_) * sympy.cosh((_a_ + (_b_ * x))) * sympy.cosh((_c_ + (_d_ * x))) * ((_c_ + (_d_ * x)))**(Integer(-1))), x))) + (Integer(-1) * (_f_ * _m_ * (_b_)**(Integer(-1)) * Int((((_e_ + (_f_ * x)))**((_m_ + Integer(-1))) * sympy.cosh((_a_ + (_b_ * x))) * sympy.Chi((_c_ + (_d_ * x)))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=22,
    ),
    # Rule 23
    RubiRulePattern(
        pattern=Int((((_e_ + (_f_ * x)))**(_m_) * sympy.cosh((_a_ + (_b_ * x))) * sympy.Function('SinhIntegral')((_c_ + (_d_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), ILtQ(_m_, -1),),
        replacement=((((_e_ + (_f_ * x)))**((_m_ + Integer(1))) * sympy.cosh((_a_ + (_b_ * x))) * sympy.Shi((_c_ + (_d_ * x))) * ((_f_ * (_m_ + Integer(1))))**(Integer(-1))) + (Integer(-1) * (_d_ * ((_f_ * (_m_ + Integer(1))))**(Integer(-1)) * Int((((_e_ + (_f_ * x)))**((_m_ + Integer(1))) * sympy.cosh((_a_ + (_b_ * x))) * sympy.sinh((_c_ + (_d_ * x))) * ((_c_ + (_d_ * x)))**(Integer(-1))), x))) + (Integer(-1) * (_b_ * ((_f_ * (_m_ + Integer(1))))**(Integer(-1)) * Int((((_e_ + (_f_ * x)))**((_m_ + Integer(1))) * sympy.sinh((_a_ + (_b_ * x))) * sympy.Shi((_c_ + (_d_ * x)))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=23,
    ),
    # Rule 24
    RubiRulePattern(
        pattern=Int((((_e_ + (_f_ * x)))**(m_) * sympy.sinh((_a_ + (_b_ * x))) * sympy.Function('CoshIntegral')((_c_ + (_d_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _f_], x), ILtQ(m_, -1),),
        replacement=((((_e_ + (_f_ * x)))**((m_ + Integer(1))) * sympy.sinh((_a_ + (_b_ * x))) * sympy.Chi((_c_ + (_d_ * x))) * ((_f_ * (m_ + Integer(1))))**(Integer(-1))) + (Integer(-1) * (_d_ * ((_f_ * (m_ + Integer(1))))**(Integer(-1)) * Int((((_e_ + (_f_ * x)))**((m_ + Integer(1))) * sympy.sinh((_a_ + (_b_ * x))) * sympy.cosh((_c_ + (_d_ * x))) * ((_c_ + (_d_ * x)))**(Integer(-1))), x))) + (Integer(-1) * (_b_ * ((_f_ * (m_ + Integer(1))))**(Integer(-1)) * Int((((_e_ + (_f_ * x)))**((m_ + Integer(1))) * sympy.cosh((_a_ + (_b_ * x))) * sympy.Chi((_c_ + (_d_ * x)))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=24,
    ),
    # Rule 25
    RubiRulePattern(
        pattern=Int(sympy.Function('SinhIntegral')((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_))))))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _n_], x),),
        replacement=((x * sympy.Shi((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_)))))))) + (Integer(-1) * (_b_ * _d_ * _n_ * Int((sympy.sinh((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_))))))) * ((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_)))))))**(Integer(-1))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=25,
    ),
    # Rule 26
    RubiRulePattern(
        pattern=Int(sympy.Function('CoshIntegral')((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_))))))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _n_], x),),
        replacement=((x * sympy.Chi((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_)))))))) + (Integer(-1) * (_b_ * _d_ * _n_ * Int((sympy.cosh((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_))))))) * ((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_)))))))**(Integer(-1))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=26,
    ),
    # Rule 27
    RubiRulePattern(
        pattern=Int(WildHeadApp(F_, _d_*(_a_ + _b_*log(x**_n_*_c_)))/x, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _n_], x), MemberQ([Symbol('SinhIntegral'), Symbol('CoshIntegral')], x),),
        replacement=Subst(WFApply(F_, _d_*(x*_b_ + _a_)), x, log(x**_n_*_c_))/_n_,
        module_name='8.5 Hyperbolic integral functions',
        rule_number=27,
    ),
    # Rule 28
    RubiRulePattern(
        pattern=Int((((_e_ * x))**(_m_) * sympy.Function('SinhIntegral')((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_)))))))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _m_, _n_], x), NeQ(_m_, -1),),
        replacement=((((_e_ * x))**((_m_ + Integer(1))) * sympy.Shi((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_))))))) * ((_e_ * (_m_ + Integer(1))))**(Integer(-1))) + (Integer(-1) * (_b_ * _d_ * _n_ * ((_m_ + Integer(1)))**(Integer(-1)) * Int((((_e_ * x))**(_m_) * sympy.sinh((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_))))))) * ((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_)))))))**(Integer(-1))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=28,
    ),
    # Rule 29
    RubiRulePattern(
        pattern=Int((((_e_ * x))**(_m_) * sympy.Function('CoshIntegral')((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_)))))))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _m_, _n_], x), NeQ(_m_, -1),),
        replacement=((((_e_ * x))**((_m_ + Integer(1))) * sympy.Chi((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_))))))) * ((_e_ * (_m_ + Integer(1))))**(Integer(-1))) + (Integer(-1) * (_b_ * _d_ * _n_ * ((_m_ + Integer(1)))**(Integer(-1)) * Int((((_e_ * x))**(_m_) * sympy.cosh((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_))))))) * ((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_)))))))**(Integer(-1))), x)))),
        module_name='8.5 Hyperbolic integral functions',
        rule_number=29,
    ),

]

# Summary: 29 rules translated, 0 skipped
