# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_rules/codegen/generate.py
# Source: 8.6 Gamma functions.m
# Module: 8.6 Gamma functions
#
# This file contains Rubi integration rules as RubiRulePattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Integer, Symbol
from rubi_rules.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not
from sympy import (
    exp, factorial,
    hyper, log, loggamma, polygamma,
)

from sympy_matching.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_rules.base_objects import Int, RubiRulePattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_rules.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, EqQ, NeQ, IGtQ, ILtQ, GtQ, LtQ, IntegersQ,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
_f_ = WildSymbol('f', optional_value=IDENTITY_ELEMENT)
f_ = WildSymbol('f')
g_ = WildSymbol('g')
_h_ = WildSymbol('h', optional_value=IDENTITY_ELEMENT)
h_ = WildSymbol('h')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')
p_ = WildSymbol('p')

RULES = [
    # Rule 1
    RubiRulePattern(
        pattern=Int(Gamma(n_, x*_b_ + _a_), x),
        constraints=(FreeQ([_a_, _b_, n_], x),),
        replacement=(x*_b_ + _a_)*Gamma(n_, x*_b_ + _a_)/_b_ - Gamma(n_ + 1, x*_b_ + _a_)/_b_,
        module_name='8.6 Gamma functions',
        rule_number=1,
    ),
    # Rule 2
    RubiRulePattern(
        pattern=Int(Gamma(0, x*_b_)/x, x),
        constraints=(FreeQ(_b_, x),),
        replacement=((_b_ * x * sympy.hyper(List(Integer(1), Integer(1), Integer(1)), List(Integer(2), Integer(2), Integer(2)), ((Integer(-1) * _b_) * x))) + (Integer(-1) * (sympy.EulerGamma * sympy.log(x))) + (Integer(-1) * ((Integer(2))**(Integer(-1)) * (sympy.log((_b_ * x)))**(Integer(2))))),
        module_name='8.6 Gamma functions',
        rule_number=2,
    ),
    # Rule 3
    RubiRulePattern(
        pattern=Int(Gamma(n_, x*_b_)/x, x),
        constraints=(FreeQ(_b_, x), IGtQ(n_, 1),),
        replacement=(n_ - 1)*Int(Gamma(n_ - 1, x*_b_)/x, x) - Gamma(n_ - 1, x*_b_),
        module_name='8.6 Gamma functions',
        rule_number=3,
    ),
    # Rule 4
    RubiRulePattern(
        pattern=Int(Gamma(n_, x*_b_)/x, x),
        constraints=(FreeQ(_b_, x), ILtQ(n_, 0),),
        replacement=Gamma(n_, x*_b_)/n_ + Int(Gamma(n_ + 1, x*_b_)/x, x)/n_,
        module_name='8.6 Gamma functions',
        rule_number=4,
    ),
    # Rule 5
    RubiRulePattern(
        pattern=Int(Gamma(n_, x*_b_)/x, x),
        constraints=(FreeQ([_b_, n_], x), Not(IntegerQ(n_)),),
        replacement=Gamma(n_)*log(x) - (x*_b_)**n_*hyper((n_, n_), (n_ + 1, n_ + 1), -x*_b_)/n_**2,
        module_name='8.6 Gamma functions',
        rule_number=5,
    ),
    # Rule 6
    RubiRulePattern(
        pattern=Int((x*_d_)**_m_*Gamma(n_, x*_b_), x),
        constraints=(FreeQ([_b_, _d_, _m_, n_], x), NeQ(_m_, -1),),
        replacement=(x*_d_)**(_m_ + 1)*Gamma(n_, x*_b_)/(_d_*(_m_ + 1)) - (x*_d_)**_m_*Gamma(_m_ + n_ + 1, x*_b_)/(_b_*(x*_b_)**_m_*(_m_ + 1)),
        module_name='8.6 Gamma functions',
        rule_number=6,
    ),
    # Rule 7
    RubiRulePattern(
        pattern=Int((x*_d_ + c_)**_m_*Gamma(n_, x*_b_ + a_), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _m_, n_], x), EqQ(-a_*_d_ + _b_*c_, 0),),
        replacement=Subst(Int((x*_d_/_b_)**_m_*Gamma(n_, x), x), x, x*_b_ + a_)/_b_,
        module_name='8.6 Gamma functions',
        rule_number=7,
    ),
    # Rule 8
    RubiRulePattern(
        pattern=Int(Gamma(n_, x*_b_ + _a_)/(x*_d_ + _c_), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_], x), IGtQ(n_, 1),),
        replacement=(n_ - 1)*Int(Gamma(n_ - 1, x*_b_ + _a_)/(x*_d_ + _c_), x) + Int((x*_b_ + _a_)**(n_ - 1)*exp(-x*_b_ - _a_)/(x*_d_ + _c_), x),
        module_name='8.6 Gamma functions',
        rule_number=8,
    ),
    # Rule 9
    RubiRulePattern(
        pattern=Int((x*_d_ + _c_)**_m_*Gamma(n_, x*_b_ + _a_), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _m_, n_], x), Or(IGtQ(_m_, 0), IGtQ(n_, 0), IntegersQ(_m_, n_)), NeQ(_m_, -1),),
        replacement=Block({UseGamma: True}, _b_*Int((x*_b_ + _a_)**(n_ - 1)*(x*_d_ + _c_)**(_m_ + 1)*exp(-x*_b_ - _a_), x)/(_d_*(_m_ + 1)) + (x*_d_ + _c_)**(_m_ + 1)*Gamma(n_, x*_b_ + _a_)/(_d_*(_m_ + 1))),
        module_name='8.6 Gamma functions',
        rule_number=9,
    ),
    # Rule 10
    RubiRulePattern(
        pattern=Int((x*_d_ + _c_)**_m_*Gamma(n_, x*_b_ + _a_), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _m_, n_], x),),
        replacement=Unintegrable((x*_d_ + _c_)**_m_*Gamma(n_, x*_b_ + _a_), x),
        module_name='8.6 Gamma functions',
        rule_number=10,
    ),
    # Rule 11
    RubiRulePattern(
        pattern=Int(loggamma(x*_b_ + _a_), x),
        constraints=(FreeQ([_a_, _b_], x),),
        replacement=polygamma(-2, x*_b_ + _a_)/_b_,
        module_name='8.6 Gamma functions',
        rule_number=11,
    ),
    # Rule 12
    RubiRulePattern(
        pattern=Int((x*_d_ + _c_)**_m_*loggamma(x*_b_ + _a_), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_], x), IGtQ(_m_, 0),),
        replacement=-_d_*_m_*Int((x*_d_ + _c_)**(_m_ - 1)*polygamma(-2, x*_b_ + _a_), x)/_b_ + (x*_d_ + _c_)**_m_*polygamma(-2, x*_b_ + _a_)/_b_,
        module_name='8.6 Gamma functions',
        rule_number=12,
    ),
    # Rule 13
    RubiRulePattern(
        pattern=Int((x*_d_ + _c_)**_m_*loggamma(x*_b_ + _a_), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _m_], x),),
        replacement=Unintegrable((x*_d_ + _c_)**_m_*loggamma(x*_b_ + _a_), x),
        module_name='8.6 Gamma functions',
        rule_number=13,
    ),
    # Rule 14
    RubiRulePattern(
        pattern=Int(polygamma(n_, x*_b_ + _a_), x),
        constraints=(FreeQ([_a_, _b_, n_], x),),
        replacement=polygamma(n_ - 1, x*_b_ + _a_)/_b_,
        module_name='8.6 Gamma functions',
        rule_number=14,
    ),
    # Rule 15
    RubiRulePattern(
        pattern=Int((x*_d_ + _c_)**_m_*polygamma(n_, x*_b_ + _a_), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, n_], x), GtQ(_m_, 0),),
        replacement=-_d_*_m_*Int((x*_d_ + _c_)**(_m_ - 1)*polygamma(n_ - 1, x*_b_ + _a_), x)/_b_ + (x*_d_ + _c_)**_m_*polygamma(n_ - 1, x*_b_ + _a_)/_b_,
        module_name='8.6 Gamma functions',
        rule_number=15,
    ),
    # Rule 16
    RubiRulePattern(
        pattern=Int((x*_d_ + _c_)**_m_*polygamma(n_, x*_b_ + _a_), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, n_], x), LtQ(_m_, -1),),
        replacement=-_b_*Int((x*_d_ + _c_)**(_m_ + 1)*polygamma(n_ + 1, x*_b_ + _a_), x)/(_d_*(_m_ + 1)) + (x*_d_ + _c_)**(_m_ + 1)*polygamma(n_, x*_b_ + _a_)/(_d_*(_m_ + 1)),
        module_name='8.6 Gamma functions',
        rule_number=16,
    ),
    # Rule 17
    RubiRulePattern(
        pattern=Int((x*_d_ + _c_)**_m_*polygamma(n_, x*_b_ + _a_), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _m_, n_], x),),
        replacement=Unintegrable((x*_d_ + _c_)**_m_*polygamma(n_, x*_b_ + _a_), x),
        module_name='8.6 Gamma functions',
        rule_number=17,
    ),
    # Rule 18
    RubiRulePattern(
        pattern=Int(polygamma(0, x*_b_ + _a_)*Gamma(x*_b_ + _a_)**_n_, x),
        constraints=(FreeQ([_a_, _b_, _n_], x),),
        replacement=Gamma(x*_b_ + _a_)**_n_/(_b_*_n_),
        module_name='8.6 Gamma functions',
        rule_number=18,
    ),
    # Rule 19
    RubiRulePattern(
        pattern=Int(factorial(x*_b_ + _a_)**_n_*polygamma(0, x*_b_ + _c_), x),
        constraints=(FreeQ([_a_, _b_, _c_, _n_], x), EqQ(_c_, _a_ + 1),),
        replacement=factorial(x*_b_ + _a_)**_n_/(_b_*_n_),
        module_name='8.6 Gamma functions',
        rule_number=19,
    ),
    # Rule 20
    RubiRulePattern(
        pattern=Int(Gamma(p_, _d_*(_a_ + _b_*log(x**_n_*_c_))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _n_, p_], x),),
        replacement=x*Gamma(p_, _d_*(_a_ + _b_*log(x**_n_*_c_))) + _b_*_d_*_n_*Int((_d_*(_a_ + _b_*log(x**_n_*_c_)))**(p_ - 1)/(x**_n_*_c_)**(_b_*_d_), x)*exp(-_a_*_d_),
        module_name='8.6 Gamma functions',
        rule_number=20,
    ),
    # Rule 21
    RubiRulePattern(
        pattern=Int(Gamma(p_, _d_*(_a_ + _b_*log(x**_n_*_c_)))/x, x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _n_, p_], x),),
        replacement=Subst(Gamma(p_, _d_*(x*_b_ + _a_)), x, log(x**_n_*_c_))/_n_,
        module_name='8.6 Gamma functions',
        rule_number=21,
    ),
    # Rule 22
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*Gamma(p_, _d_*(_a_ + _b_*log(x**_n_*_c_))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _m_, _n_, p_], x), NeQ(_m_, -1),),
        replacement=_b_*_d_*_n_*(x*_e_)**(_b_*_d_*_n_)*Int((x*_e_)**(-_b_*_d_*_n_ + _m_)*(_d_*(_a_ + _b_*log(x**_n_*_c_)))**(p_ - 1), x)*exp(-_a_*_d_)/((x**_n_*_c_)**(_b_*_d_)*(_m_ + 1)) + (x*_e_)**(_m_ + 1)*Gamma(p_, _d_*(_a_ + _b_*log(x**_n_*_c_)))/(_e_*(_m_ + 1)),
        module_name='8.6 Gamma functions',
        rule_number=22,
    ),
    # Rule 23
    RubiRulePattern(
        pattern=Int(Gamma(p_, _f_*(_a_ + _b_*log(_c_*(x*_e_ + d_)**_n_))), x),
        constraints=(FreeQ([_a_, _b_, _c_, d_, _e_, _f_, _n_, p_], x),),
        replacement=Subst(Int(Gamma(p_, _f_*(_a_ + _b_*log(x**_n_*_c_))), x), x, x*_e_ + d_)/_e_,
        module_name='8.6 Gamma functions',
        rule_number=23,
    ),
    # Rule 24
    RubiRulePattern(
        pattern=Int((x*_h_ + g_)**_m_*Gamma(p_, _f_*(_a_ + _b_*log(_c_*(x*_e_ + d_)**_n_))), x),
        constraints=(FreeQ([_a_, _b_, _c_, d_, _e_, _f_, g_, _h_, _m_, _n_, p_], x), EqQ(-d_*_h_ + _e_*g_, 0),),
        replacement=Subst(Int((x*g_/d_)**_m_*Gamma(p_, _f_*(_a_ + _b_*log(x**_n_*_c_))), x), x, x*_e_ + d_)/_e_,
        module_name='8.6 Gamma functions',
        rule_number=24,
    ),

]

# Summary: 24 rules translated, 0 skipped
