# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_rules/codegen/generate.py
# Source: 8.3 Exponential integral functions.m
# Module: 8.3 Exponential integral functions
#
# This file contains Rubi integration rules as RubiRulePattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Integer, Symbol
from rubi_rules.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (
    expint, hyper, log,
)

from sympy_matching.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_rules.base_objects import Int, RubiRulePattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_rules.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, EqQ, NeQ, IGtQ, ILtQ, GtQ, LtQ,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')

RULES = [
    # Rule 1
    RubiRulePattern(
        pattern=Int(expint(n_, x*_b_ + _a_), x),
        constraints=(FreeQ([_a_, _b_, n_], x),),
        replacement=-expint(n_ + 1, x*_b_ + _a_)/_b_,
        module_name='8.3 Exponential integral functions',
        rule_number=1,
    ),
    # Rule 2
    RubiRulePattern(
        pattern=Int(x**_m_*expint(n_, x*_b_), x),
        constraints=(FreeQ(_b_, x), EqQ(_m_ + n_, 0), IGtQ(_m_, 0),),
        replacement=-x**_m_*expint(n_ + 1, x*_b_)/_b_ + _m_*Int(x**(_m_ - 1)*expint(n_ + 1, x*_b_), x)/_b_,
        module_name='8.3 Exponential integral functions',
        rule_number=2,
    ),
    # Rule 3
    RubiRulePattern(
        pattern=Int(expint(1, x*_b_)/x, x),
        constraints=(FreeQ(_b_, x),),
        replacement=((_b_ * x * sympy.hyper(List(Integer(1), Integer(1), Integer(1)), List(Integer(2), Integer(2), Integer(2)), ((Integer(-1) * _b_) * x))) + (Integer(-1) * (sympy.EulerGamma * sympy.log(x))) + (Integer(-1) * ((Integer(2))**(Integer(-1)) * (sympy.log((_b_ * x)))**(Integer(2))))),
        module_name='8.3 Exponential integral functions',
        rule_number=3,
    ),
    # Rule 4
    RubiRulePattern(
        pattern=Int(x**m_*expint(n_, x*_b_), x),
        constraints=(FreeQ(_b_, x), EqQ(m_ + n_, 0), ILtQ(m_, -1),),
        replacement=x**(m_ + 1)*expint(n_, x*_b_)/(m_ + 1) + _b_*Int(x**(m_ + 1)*expint(n_ - 1, x*_b_), x)/(m_ + 1),
        module_name='8.3 Exponential integral functions',
        rule_number=4,
    ),
    # Rule 5
    RubiRulePattern(
        pattern=Int((x*_d_)**m_*expint(n_, x*_b_), x),
        constraints=(FreeQ([_b_, _d_, m_, n_], x), EqQ(m_ + n_, 0), Not(IntegerQ(m_)),),
        replacement=-(x*_d_)**(m_ + 1)*hyper((m_ + 1, m_ + 1), (m_ + 2, m_ + 2), -x*_b_)/(_d_*(m_ + 1)**2) + (x*_d_)**m_*Gamma(m_ + 1)*log(x)/(_b_*(x*_b_)**m_),
        module_name='8.3 Exponential integral functions',
        rule_number=5,
    ),
    # Rule 6
    RubiRulePattern(
        pattern=Int((x*_d_)**_m_*expint(n_, x*_b_), x),
        constraints=(FreeQ([_b_, _d_, _m_, n_], x), NeQ(_m_ + n_, 0),),
        replacement=-(x*_d_)**(_m_ + 1)*expint(-_m_, x*_b_)/(_d_*(_m_ + n_)) + (x*_d_)**(_m_ + 1)*expint(n_, x*_b_)/(_d_*(_m_ + n_)),
        module_name='8.3 Exponential integral functions',
        rule_number=6,
    ),
    # Rule 7
    RubiRulePattern(
        pattern=Int((x*_d_ + _c_)**_m_*expint(n_, x*_b_ + a_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _m_, n_], x), Or(IGtQ(_m_, 0), ILtQ(n_, 0), And(GtQ(_m_, 0), LtQ(n_, -1))),),
        replacement=_d_*_m_*Int((x*_d_ + _c_)**(_m_ - 1)*expint(n_ + 1, x*_b_ + a_), x)/_b_ - (x*_d_ + _c_)**_m_*expint(n_ + 1, x*_b_ + a_)/_b_,
        module_name='8.3 Exponential integral functions',
        rule_number=7,
    ),
    # Rule 8
    RubiRulePattern(
        pattern=Int((x*_d_ + _c_)**_m_*expint(n_, x*_b_ + a_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _m_, n_], x), Or(IGtQ(n_, 0), And(LtQ(_m_, -1), GtQ(n_, 0))), NeQ(_m_, -1),),
        replacement=_b_*Int((x*_d_ + _c_)**(_m_ + 1)*expint(n_ - 1, x*_b_ + a_), x)/(_d_*(_m_ + 1)) + (x*_d_ + _c_)**(_m_ + 1)*expint(n_, x*_b_ + a_)/(_d_*(_m_ + 1)),
        module_name='8.3 Exponential integral functions',
        rule_number=8,
    ),
    # Rule 9
    RubiRulePattern(
        pattern=Int((x*_d_ + _c_)**_m_*expint(n_, x*_b_ + a_), x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _m_, n_], x),),
        replacement=Unintegrable((x*_d_ + _c_)**_m_*expint(n_, x*_b_ + a_), x),
        module_name='8.3 Exponential integral functions',
        rule_number=9,
    ),
    # Rule 10
    RubiRulePattern(
        pattern=Int(ExpIntegralEi((_a_ + (_b_ * x))), x),
        constraints=(FreeQ([_a_, _b_], x),),
        replacement=(((_a_ + (_b_ * x)) * ExpIntegralEi((_a_ + (_b_ * x))) * (_b_)**(Integer(-1))) + (Integer(-1) * ((sympy.E)**((_a_ + (_b_ * x))) * (_b_)**(Integer(-1))))),
        module_name='8.3 Exponential integral functions',
        rule_number=10,
    ),
    # Rule 11
    RubiRulePattern(
        pattern=Int((ExpIntegralEi((_b_ * x)) * (x)**(Integer(-1))), x),
        constraints=(FreeQ(_b_, x),),
        replacement=((sympy.log(x) * (ExpIntegralEi((_b_ * x)) + sympy.expint(Integer(1), ((Integer(-1) * _b_) * x)))) + (Integer(-1) * Int((sympy.expint(Integer(1), ((Integer(-1) * _b_) * x)) * (x)**(Integer(-1))), x))),
        module_name='8.3 Exponential integral functions',
        rule_number=11,
    ),
    # Rule 12
    RubiRulePattern(
        pattern=Int((ExpIntegralEi((_a_ + (_b_ * x))) * ((_c_ + (_d_ * x)))**(Integer(-1))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_], x),),
        replacement=Unintegrable((ExpIntegralEi((_a_ + (_b_ * x))) * ((_c_ + (_d_ * x)))**(Integer(-1))), x),
        module_name='8.3 Exponential integral functions',
        rule_number=12,
    ),
    # Rule 13
    RubiRulePattern(
        pattern=Int((((_c_ + (_d_ * x)))**(_m_) * ExpIntegralEi((_a_ + (_b_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _m_], x), NeQ(_m_, -1),),
        replacement=((((_c_ + (_d_ * x)))**((_m_ + Integer(1))) * ExpIntegralEi((_a_ + (_b_ * x))) * ((_d_ * (_m_ + Integer(1))))**(Integer(-1))) + (Integer(-1) * (_b_ * ((_d_ * (_m_ + Integer(1))))**(Integer(-1)) * Int((((_c_ + (_d_ * x)))**((_m_ + Integer(1))) * (sympy.E)**((_a_ + (_b_ * x))) * ((_a_ + (_b_ * x)))**(Integer(-1))), x)))),
        module_name='8.3 Exponential integral functions',
        rule_number=13,
    ),
    # Rule 14
    RubiRulePattern(
        pattern=Int((ExpIntegralEi((_a_ + (_b_ * x))))**(Integer(2)), x),
        constraints=(FreeQ([_a_, _b_], x),),
        replacement=(((_a_ + (_b_ * x)) * (ExpIntegralEi((_a_ + (_b_ * x))))**(Integer(2)) * (_b_)**(Integer(-1))) + (Integer(-1) * (Integer(2) * Int(((sympy.E)**((_a_ + (_b_ * x))) * ExpIntegralEi((_a_ + (_b_ * x)))), x)))),
        module_name='8.3 Exponential integral functions',
        rule_number=14,
    ),
    # Rule 15
    RubiRulePattern(
        pattern=Int(((x)**(_m_) * (ExpIntegralEi((_b_ * x)))**(Integer(2))), x),
        constraints=(FreeQ(_b_, x), IGtQ(_m_, 0),),
        replacement=(((x)**((_m_ + Integer(1))) * (ExpIntegralEi((_b_ * x)))**(Integer(2)) * ((_m_ + Integer(1)))**(Integer(-1))) + (Integer(-1) * (Integer(2) * ((_m_ + Integer(1)))**(Integer(-1)) * Int(((x)**(_m_) * (sympy.E)**((_b_ * x)) * ExpIntegralEi((_b_ * x))), x)))),
        module_name='8.3 Exponential integral functions',
        rule_number=15,
    ),
    # Rule 16
    RubiRulePattern(
        pattern=Int(((x)**(_m_) * (ExpIntegralEi((a_ + (_b_ * x))))**(Integer(2))), x),
        constraints=(FreeQ([a_, _b_], x), IGtQ(_m_, 0),),
        replacement=(((x)**((_m_ + Integer(1))) * (ExpIntegralEi((a_ + (_b_ * x))))**(Integer(2)) * ((_m_ + Integer(1)))**(Integer(-1))) + (a_ * (x)**(_m_) * (ExpIntegralEi((a_ + (_b_ * x))))**(Integer(2)) * ((_b_ * (_m_ + Integer(1))))**(Integer(-1))) + (Integer(-1) * (Integer(2) * ((_m_ + Integer(1)))**(Integer(-1)) * Int(((x)**(_m_) * (sympy.E)**((a_ + (_b_ * x))) * ExpIntegralEi((a_ + (_b_ * x)))), x))) + (Integer(-1) * (a_ * _m_ * ((_b_ * (_m_ + Integer(1))))**(Integer(-1)) * Int(((x)**((_m_ + Integer(-1))) * (ExpIntegralEi((a_ + (_b_ * x))))**(Integer(2))), x)))),
        module_name='8.3 Exponential integral functions',
        rule_number=16,
    ),
    # Rule 17
    RubiRulePattern(
        pattern=Int(((sympy.E)**((_a_ + (_b_ * x))) * ExpIntegralEi((_c_ + (_d_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_], x),),
        replacement=(((sympy.E)**((_a_ + (_b_ * x))) * ExpIntegralEi((_c_ + (_d_ * x))) * (_b_)**(Integer(-1))) + (Integer(-1) * (_d_ * (_b_)**(Integer(-1)) * Int(((sympy.E)**((_a_ + _c_ + ((_b_ + _d_) * x))) * ((_c_ + (_d_ * x)))**(Integer(-1))), x)))),
        module_name='8.3 Exponential integral functions',
        rule_number=17,
    ),
    # Rule 18
    RubiRulePattern(
        pattern=Int(((x)**(_m_) * (sympy.E)**((_a_ + (_b_ * x))) * ExpIntegralEi((_c_ + (_d_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_], x), IGtQ(_m_, 0),),
        replacement=(((x)**(_m_) * (sympy.E)**((_a_ + (_b_ * x))) * ExpIntegralEi((_c_ + (_d_ * x))) * (_b_)**(Integer(-1))) + (Integer(-1) * (_d_ * (_b_)**(Integer(-1)) * Int(((x)**(_m_) * (sympy.E)**((_a_ + _c_ + ((_b_ + _d_) * x))) * ((_c_ + (_d_ * x)))**(Integer(-1))), x))) + (Integer(-1) * (_m_ * (_b_)**(Integer(-1)) * Int(((x)**((_m_ + Integer(-1))) * (sympy.E)**((_a_ + (_b_ * x))) * ExpIntegralEi((_c_ + (_d_ * x)))), x)))),
        module_name='8.3 Exponential integral functions',
        rule_number=18,
    ),
    # Rule 19
    RubiRulePattern(
        pattern=Int(((x)**(m_) * (sympy.E)**((_a_ + (_b_ * x))) * ExpIntegralEi((_c_ + (_d_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_], x), ILtQ(m_, -1),),
        replacement=(((x)**((m_ + Integer(1))) * (sympy.E)**((_a_ + (_b_ * x))) * ExpIntegralEi((_c_ + (_d_ * x))) * ((m_ + Integer(1)))**(Integer(-1))) + (Integer(-1) * (_d_ * ((m_ + Integer(1)))**(Integer(-1)) * Int(((x)**((m_ + Integer(1))) * (sympy.E)**((_a_ + _c_ + ((_b_ + _d_) * x))) * ((_c_ + (_d_ * x)))**(Integer(-1))), x))) + (Integer(-1) * (_b_ * ((m_ + Integer(1)))**(Integer(-1)) * Int(((x)**((m_ + Integer(1))) * (sympy.E)**((_a_ + (_b_ * x))) * ExpIntegralEi((_c_ + (_d_ * x)))), x)))),
        module_name='8.3 Exponential integral functions',
        rule_number=19,
    ),
    # Rule 20
    RubiRulePattern(
        pattern=Int(ExpIntegralEi((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_))))))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _n_], x),),
        replacement=((x * ExpIntegralEi((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_)))))))) + (Integer(-1) * (_b_ * _n_ * (sympy.E)**((_a_ * _d_)) * Int((((_c_ * (x)**(_n_)))**((_b_ * _d_)) * ((_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_))))))**(Integer(-1))), x)))),
        module_name='8.3 Exponential integral functions',
        rule_number=20,
    ),
    # Rule 21
    RubiRulePattern(
        pattern=Int((ExpIntegralEi((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_))))))) * (x)**(Integer(-1))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _n_], x),),
        replacement=((_n_)**(Integer(-1)) * Subst(ExpIntegralEi((_d_ * (_a_ + (_b_ * x)))), x, sympy.log((_c_ * (x)**(_n_))))),
        module_name='8.3 Exponential integral functions',
        rule_number=21,
    ),
    # Rule 22
    RubiRulePattern(
        pattern=Int((((_e_ * x))**(_m_) * ExpIntegralEi((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_)))))))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _e_, _m_, _n_], x), NeQ(_m_, -1),),
        replacement=((((_e_ * x))**((_m_ + Integer(1))) * ExpIntegralEi((_d_ * (_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_))))))) * ((_e_ * (_m_ + Integer(1))))**(Integer(-1))) + (Integer(-1) * (_b_ * _n_ * (sympy.E)**((_a_ * _d_)) * ((_c_ * (x)**(_n_)))**((_b_ * _d_)) * (((_m_ + Integer(1)) * ((_e_ * x))**((_b_ * _d_ * _n_))))**(Integer(-1)) * Int((((_e_ * x))**((_m_ + (_b_ * _d_ * _n_))) * ((_a_ + (_b_ * sympy.log((_c_ * (x)**(_n_))))))**(Integer(-1))), x)))),
        module_name='8.3 Exponential integral functions',
        rule_number=22,
    ),
    # Rule 23
    RubiRulePattern(
        pattern=Int(LogIntegral((_a_ + (_b_ * x))), x),
        constraints=(FreeQ([_a_, _b_], x),),
        replacement=(((_a_ + (_b_ * x)) * LogIntegral((_a_ + (_b_ * x))) * (_b_)**(Integer(-1))) + (Integer(-1) * (ExpIntegralEi((Integer(2) * sympy.log((_a_ + (_b_ * x))))) * (_b_)**(Integer(-1))))),
        module_name='8.3 Exponential integral functions',
        rule_number=23,
    ),
    # Rule 24
    RubiRulePattern(
        pattern=Int((LogIntegral((_b_ * x)) * (x)**(Integer(-1))), x),
        constraints=(FreeQ(_b_, x),),
        replacement=(((Integer(-1) * _b_) * x) + (sympy.log((_b_ * x)) * LogIntegral((_b_ * x)))),
        module_name='8.3 Exponential integral functions',
        rule_number=24,
    ),
    # Rule 25
    RubiRulePattern(
        pattern=Int((LogIntegral((_a_ + (_b_ * x))) * ((_c_ + (_d_ * x)))**(Integer(-1))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_], x),),
        replacement=Unintegrable((LogIntegral((_a_ + (_b_ * x))) * ((_c_ + (_d_ * x)))**(Integer(-1))), x),
        module_name='8.3 Exponential integral functions',
        rule_number=25,
    ),
    # Rule 26
    RubiRulePattern(
        pattern=Int((((_c_ + (_d_ * x)))**(_m_) * LogIntegral((_a_ + (_b_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, _m_], x), NeQ(_m_, -1),),
        replacement=((((_c_ + (_d_ * x)))**((_m_ + Integer(1))) * LogIntegral((_a_ + (_b_ * x))) * ((_d_ * (_m_ + Integer(1))))**(Integer(-1))) + (Integer(-1) * (_b_ * ((_d_ * (_m_ + Integer(1))))**(Integer(-1)) * Int((((_c_ + (_d_ * x)))**((_m_ + Integer(1))) * (sympy.log((_a_ + (_b_ * x))))**(Integer(-1))), x)))),
        module_name='8.3 Exponential integral functions',
        rule_number=26,
    ),

]

# Summary: 26 rules translated, 0 skipped
