# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_rules/codegen/generate.py
# Source: 8.7 Zeta function.m
# Module: 8.7 Zeta function
#
# This file contains Rubi integration rules as RubiRulePattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Integer, Integral, Lambda, Rational, Symbol, Tuple as SympyTuple
from rubi_rules.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (
    Abs, Chi, Ci, Ei, Eq, Ge, Gt, I, Le, Lt, Ne, Shi, Si, acos, acosh, acot, acoth, acsc, acsch,
    appellf1, asec, asech, asin, asinh, atan, atan2, atanh, cos, cosh, cot, coth, csc, csch, denom,
    diff, elliptic_e, elliptic_f, erf, erfc, erfi, exp, floor, frac, fresnelc, fresnels, hyper, li,
    log, loggamma, oo, pi, polylog, root, sec, sech, simplify, sin, sinh, sqrt, tan, tanh,
)

from sympy_matching.wild import WildSymbol, WildHeadApp, WildHeadDeriv, HeadRef, IDENTITY_ELEMENT
from rubi_rules.base_objects import Int, RubiRulePattern
# Inert trig markers (Rubi's lowercase sin/cos/... patterns). Distinct opaque heads,
# NOT subclasses of sympy.sin -- see rubi-trig-deactivation-dispatch project note.
from rubi_rules.utils.inert_functions import (
    InertSin, InertCos, InertTan, InertCot, InertSec, InertCsc)
from rubi_rules.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, OddQ, EvenQ, NumberQ, NumericQ, AtomQ, MemberQ,
    PositiveQ, NegativeQ, PolynomialQ, TrueQ, FalseQ, MatchQ, PrimeQ, UnsameQ,
    # RUBI-specific constraints
    EqQ, NeQ, IGtQ, ILtQ, IGeQ, ILeQ, GtQ, LtQ, GeQ, LeQ, PosQ, NegQ,
    IntegersQ, HalfIntegerQ, FractionQ, RationalQ, ComplexNumberQ, RealNumberQ,
    FractionOrNegativeQ, SqrtNumberQ, PowerQ, ProductQ, SumQ, NonsumQ,
    IntegerPowerQ, FractionalPowerQ, PolyQ, LinearQ, QuadraticQ, BinomialQ,
    TrinomialQ, LinearMatchQ, QuadraticMatchQ, BinomialMatchQ, TrinomialMatchQ,
    TrigQ, HyperbolicQ, InverseTrigQ, InverseHyperbolicQ, LogQ, ComplexFreeQ,
    InverseFunctionFreeQ, FractionalPowerFreeQ, TrigHyperbolicFreeQ, IntegralFreeQ,
    RationalFunctionQ, AlgebraicFunctionQ, IndependentQ, SimplerQ, SumSimplerQ,
    FunctionOfQ, PiecewiseLinearQ, ExpressionEqQ,
    IntLinearQ, IntBinomialQ, IntQuadraticQ,
    MonomialQ, LinearPairQ,
    GeneralizedBinomialQ, GeneralizedBinomialMatchQ,
    GeneralizedTrinomialQ, GeneralizedTrinomialMatchQ,
    NiceSqrtQ, SimplerSqrtQ, FractionalPowerFactorQ,
    SumBaseQ, InverseFunctionQ, InertTrigQ, InertTrigFreeQ,
    CalculusFreeQ, QuotientOfLinearsQ,
    PowerOfLinearQ, PowerOfLinearMatchQ,
    FunctionOfExponentialQ,
    KnownSineIntegrandQ, KnownSecantIntegrandQ,
    KnownTangentIntegrandQ, KnownCotangentIntegrandQ,
    EulerIntegrandQ, SubstForFractionalPowerQ,
    PerfectSquareQ, PolynomialInQ, FunctionOfTrigOfLinearQ,
    SimplerIntegrandQ, PseudoBinomialPairQ, QuadraticProductQ,
    EveryQ, TrigSimplifyQ, EqM, TryPureTanSubst,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Rubi selector symbols ---
# Rubi passes Min/Max as bare SYMBOLS, not calls: Expon[Px, x, Min] selects the
# minimum exponent. The code emitter round-trips through SymPy's printer, which
# renders Symbol('Min') as the bare name `Min`, so the name must exist here.
# (A genuine Min[a, b] call is emitted qualified, as sympy.Min(...), so these
# bindings cannot shadow it.)
Min = Symbol('Min')
Max = Symbol('Max')

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
s_ = WildSymbol('s')

RULES = [
    # Rule 1
    RubiRulePattern(
        pattern=Int(sympy.Function('Zeta')(Integer(2), (_a_ + (_b_ * x))), x),
        constraints=(FreeQ([_a_, _b_], x),),
        replacement=Int(sympy.polygamma(Integer(1), (_a_ + (_b_ * x))), x),
        module_name='8.7 Zeta function',
        rule_number=1,
    ),
    # Rule 2
    RubiRulePattern(
        pattern=Int(sympy.Function('Zeta')(s_, (_a_ + (_b_ * x))), x),
        constraints=(FreeQ([_a_, _b_, s_], x), NeQ(s_, 1), NeQ(s_, 2),),
        replacement=((Integer(-1) * sympy.zeta((s_ + Integer(-1)), (_a_ + (_b_ * x)))) * ((_b_ * (s_ + Integer(-1))))**(Integer(-1))),
        module_name='8.7 Zeta function',
        rule_number=2,
    ),
    # Rule 3
    RubiRulePattern(
        pattern=Int((((_c_ + (_d_ * x)))**(_m_) * sympy.Function('Zeta')(Integer(2), (_a_ + (_b_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_], x), RationalQ(_m_),),
        replacement=Int((((_c_ + (_d_ * x)))**(_m_) * sympy.polygamma(Integer(1), (_a_ + (_b_ * x)))), x),
        module_name='8.7 Zeta function',
        rule_number=3,
    ),
    # Rule 4
    RubiRulePattern(
        pattern=Int((((_c_ + (_d_ * x)))**(_m_) * sympy.Function('Zeta')(s_, (_a_ + (_b_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, s_], x), NeQ(s_, 1), NeQ(s_, 2), GtQ(_m_, 0),),
        replacement=(((Integer(-1) * ((_c_ + (_d_ * x)))**(_m_)) * sympy.zeta((s_ + Integer(-1)), (_a_ + (_b_ * x))) * ((_b_ * (s_ + Integer(-1))))**(Integer(-1))) + (_d_ * _m_ * ((_b_ * (s_ + Integer(-1))))**(Integer(-1)) * Int((((_c_ + (_d_ * x)))**((_m_ + Integer(-1))) * sympy.zeta((s_ + Integer(-1)), (_a_ + (_b_ * x)))), x))),
        module_name='8.7 Zeta function',
        rule_number=4,
    ),
    # Rule 5
    RubiRulePattern(
        pattern=Int((((_c_ + (_d_ * x)))**(_m_) * sympy.Function('Zeta')(s_, (_a_ + (_b_ * x)))), x),
        constraints=(FreeQ([_a_, _b_, _c_, _d_, s_], x), NeQ(s_, 1), NeQ(s_, 2), LtQ(_m_, -1),),
        replacement=((((_c_ + (_d_ * x)))**((_m_ + Integer(1))) * sympy.zeta(s_, (_a_ + (_b_ * x))) * ((_d_ * (_m_ + Integer(1))))**(Integer(-1))) + (_b_ * s_ * ((_d_ * (_m_ + Integer(1))))**(Integer(-1)) * Int((((_c_ + (_d_ * x)))**((_m_ + Integer(1))) * sympy.zeta((s_ + Integer(1)), (_a_ + (_b_ * x)))), x))),
        module_name='8.7 Zeta function',
        rule_number=5,
    ),

]

# Summary: 5 rules translated, 0 skipped
