# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_rules/codegen/generate.py
# Source: 1.2.2.6 P(x) (d x)^m (a+b x^2+c x^4)^p.m
# Module: 1.2.2.6 P(x) (d x)^m (a+b x^2+c x^4)^p
#
# This file contains Rubi integration rules as RubiRulePattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Integer, Integral, Lambda, Rational, Symbol, Tuple as SympyTuple, Eq, Ne, Lt, Gt, Le, Ge, log, sqrt, pi, I, oo
from rubi_rules.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (sin, cos, tan, sec, csc, cot, asin, acos, atan, atan2, asec, acsc, acot,
                   sinh, cosh, tanh, sech, csch, coth, asinh, acosh, atanh, asech, acsch, acoth,
                   exp, Abs, diff, denom, frac, floor, root, simplify,
                   elliptic_e, elliptic_f, hyper, appellf1)

from sympy_objects.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_rules.base_objects import Int, RubiRulePattern
from rubi_rules.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, OddQ, EvenQ, NumberQ, NumericQ, AtomQ, MemberQ,
    PositiveQ, NegativeQ, PolynomialQ, TrueQ, FalseQ, MatchQ, PrimeQ, UnsameQ,
    # RUBI-specific constraints
    EqQ, NeQ, IGtQ, ILtQ, IGeQ, ILeQ, GtQ, LtQ, GeQ, LeQ, PosQ, NegQ,
    IntegersQ, HalfIntegerQ, FractionQ, RationalQ, ComplexNumberQ, RealNumberQ,
    FractionOrNegativeQ, SqrtNumberQ, PowerQ, ProductQ, SumQ, NonsumQ,
    IntegerPowerQ, FractionalPowerQ, PolyQ, LinearQ, QuadraticQ, BinomialQ,
    TrinomialQ, LinearMatchQ, QuadraticMatchQ, BinomialMatchQ, TrinomialMatchQ,
    TrigQ, HyperbolicQ, InverseTrigQ, InverseHyperbolicQ, LogQ, ComplexFreeQ,
    InverseFunctionFreeQ, FractionalPowerFreeQ, TrigHyperbolicFreeQ, IntegralFreeQ,
    RationalFunctionQ, AlgebraicFunctionQ, IndependentQ, SimplerQ, SumSimplerQ,
    FunctionOfQ, PiecewiseLinearQ, ExpressionEqQ,
    IntLinearQ, IntBinomialQ, IntQuadraticQ,
    MonomialQ, LinearPairQ,
    GeneralizedBinomialQ, GeneralizedBinomialMatchQ,
    GeneralizedTrinomialQ, GeneralizedTrinomialMatchQ,
    NiceSqrtQ, SimplerSqrtQ, FractionalPowerFactorQ,
    SumBaseQ, InverseFunctionQ, InertTrigQ, InertTrigFreeQ,
    CalculusFreeQ, QuotientOfLinearsQ,
    PowerOfLinearQ, PowerOfLinearMatchQ,
    FunctionOfExponentialQ,
    KnownSineIntegrandQ, KnownSecantIntegrandQ,
    KnownTangentIntegrandQ, KnownCotangentIntegrandQ,
    EulerIntegrandQ, SubstForFractionalPowerQ,
    PerfectSquareQ, PolynomialInQ, FunctionOfTrigOfLinearQ,
    SimplerIntegrandQ, PseudoBinomialPairQ, QuadraticProductQ,
    EveryQ, TrigSimplifyQ, EqM, TryPureTanSubst,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

Pq_ = WildSymbol('Pq')
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_p_ = WildSymbol('p', optional_value=IDENTITY_ELEMENT)
p_ = WildSymbol('p')

RULES = [
    # Rule 1
    RubiRulePattern(
        pattern=Int(Pq_*(x*_d_)**_m_*(x**4*_c_ + x**2*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _m_, p_], x), PolyQ(Pq_, x), Not(PolyQ(Pq_, x**2)),),
        replacement=Module(List(Set(Symbol('q'), Expon(Pq_, x)), Symbol('k')), (Int((((_d_ * x))**(_m_) * Sum((Coeff(Pq_, x, (Integer(2) * Symbol('k'))) * (x)**((Integer(2) * Symbol('k')))), List(Symbol('k'), Integer(0), ((Symbol('q') * (Integer(2))**(Integer(-1))) + Integer(1)))) * ((a_ + (_b_ * (x)**(Integer(2))) + (_c_ * (x)**(Integer(4)))))**(p_)), x) + ((_d_)**(Integer(-1)) * Int((((_d_ * x))**((_m_ + Integer(1))) * Sum((Coeff(Pq_, x, ((Integer(2) * Symbol('k')) + Integer(1))) * (x)**((Integer(2) * Symbol('k')))), List(Symbol('k'), Integer(0), (((Symbol('q') + Integer(-1)) * (Integer(2))**(Integer(-1))) + Integer(1)))) * ((a_ + (_b_ * (x)**(Integer(2))) + (_c_ * (x)**(Integer(4)))))**(p_)), x)))),
        module_name='1.2.2.6 P(x) (d x)^m (a+b x^2+c x^4)^p',
        rule_number=1,
    ),
    # Rule 2
    RubiRulePattern(
        pattern=Int(x**_m_*Pq_*(x**4*_c_ + x**2*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, p_], x), PolyQ(Pq_, x**2), IntegerQ(_m_/2 + sympy.S(-1)/2),),
        replacement=Subst(Int(x**(_m_/2 + sympy.S(-1)/2)*(x**2*_c_ + x*_b_ + a_)**p_*SubstFor(x**2, Pq_, x), x), x, x**2)/2,
        module_name='1.2.2.6 P(x) (d x)^m (a+b x^2+c x^4)^p',
        rule_number=2,
    ),
    # Rule 3
    RubiRulePattern(
        pattern=Int(Pq_*(x*_d_)**_m_*(x**4*_c_ + x**2*_b_ + a_)**_p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _m_], x), PolyQ(Pq_, x**2), IGtQ(_p_, -2),),
        replacement=Int(ExpandIntegrand(Pq_*(x*_d_)**_m_*(x**4*_c_ + x**2*_b_ + a_)**_p_, x), x),
        module_name='1.2.2.6 P(x) (d x)^m (a+b x^2+c x^4)^p',
        rule_number=3,
    ),
    # Rule 4
    RubiRulePattern(
        pattern=Int(Pq_*(x*_d_)**_m_*(x**4*_c_ + x**2*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _m_, p_], x), PolyQ(Pq_, x**2), EqQ(Coeff(Pq_, x, 0), 0),),
        replacement=Int((x*_d_)**(_m_ + 2)*(x**4*_c_ + x**2*_b_ + a_)**p_*ExpandToSum(Pq_/x**2, x), x)/_d_**2,
        module_name='1.2.2.6 P(x) (d x)^m (a+b x^2+c x^4)^p',
        rule_number=4,
    ),
    # Rule 5
    RubiRulePattern(
        pattern=Int(Pq_*(x*_d_)**_m_*(x**4*_c_ + x**2*_b_ + a_)**_p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _m_, _p_], x), PolyQ(Pq_, x**2), EqQ(Expon(Pq_, x), 4),),
        replacement=With(List(Set(Symbol('e'), Coeff(Pq_, x, Integer(0))), Set(Symbol('f'), Coeff(Pq_, x, Integer(2))), Set(Symbol('g'), Coeff(Pq_, x, Integer(4)))), Condition((Symbol('e') * ((_d_ * x))**((_m_ + Integer(1))) * ((a_ + (_b_ * (x)**(Integer(2))) + (_c_ * (x)**(Integer(4)))))**((_p_ + Integer(1))) * ((a_ * _d_ * (_m_ + Integer(1))))**(Integer(-1))), And(EqQ(((a_ * Symbol('f') * (_m_ + Integer(1))) + (Integer(-1) * (_b_ * Symbol('e') * (_m_ + (Integer(2) * _p_) + Integer(3))))), Integer(0)), EqQ(((a_ * Symbol('g') * (_m_ + Integer(1))) + (Integer(-1) * (_c_ * Symbol('e') * (_m_ + (Integer(4) * _p_) + Integer(5))))), Integer(0)), NeQ(_m_, Integer(-1))))),
        module_name='1.2.2.6 P(x) (d x)^m (a+b x^2+c x^4)^p',
        rule_number=5,
    ),
    # Rule 6
    RubiRulePattern(
        pattern=Int(Pq_*(x*_d_)**_m_*(x**4*_c_ + x**2*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _m_, p_], x), PolyQ(Pq_, x**2), GtQ(Expon(Pq_, x**2), 1), EqQ(-4*a_*_c_ + _b_**2, 0),),
        replacement=(x**4*_c_ + x**2*_b_ + a_)**FracPart(p_)*Int(Pq_*(x*_d_)**_m_*(2*x**2*_c_ + _b_)**(2*p_), x)/((4*_c_)**IntPart(p_)*(2*x**2*_c_ + _b_)**(2*FracPart(p_))),
        module_name='1.2.2.6 P(x) (d x)^m (a+b x^2+c x^4)^p',
        rule_number=6,
    ),
    # Rule 7
    RubiRulePattern(
        pattern=Int(x**m_*Pq_*(x**4*_c_ + x**2*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_], x), PolyQ(Pq_, x**2), GtQ(Expon(Pq_, x**2), 1), NeQ(-4*a_*_c_ + _b_**2, 0), LtQ(p_, -1), IGtQ(m_/2, 0),),
        replacement=With(List(Set(Symbol('d'), Coeff(PolynomialRemainder(((x)**(m_) * Pq_), (a_ + (_b_ * (x)**(Integer(2))) + (_c_ * (x)**(Integer(4)))), x), x, Integer(0))), Set(Symbol('e'), Coeff(PolynomialRemainder(((x)**(m_) * Pq_), (a_ + (_b_ * (x)**(Integer(2))) + (_c_ * (x)**(Integer(4)))), x), x, Integer(2)))), ((x * ((a_ + (_b_ * (x)**(Integer(2))) + (_c_ * (x)**(Integer(4)))))**((p_ + Integer(1))) * ((a_ * _b_ * Symbol('e')) + (Integer(-1) * (Symbol('d') * ((_b_)**(Integer(2)) + (Integer(-1) * (Integer(2) * a_ * _c_))))) + (Integer(-1) * (_c_ * ((_b_ * Symbol('d')) + (Integer(-1) * (Integer(2) * a_ * Symbol('e')))) * (x)**(Integer(2))))) * ((Integer(2) * a_ * (p_ + Integer(1)) * ((_b_)**(Integer(2)) + (Integer(-1) * (Integer(4) * a_ * _c_)))))**(Integer(-1))) + (((Integer(2) * a_ * (p_ + Integer(1)) * ((_b_)**(Integer(2)) + (Integer(-1) * (Integer(4) * a_ * _c_)))))**(Integer(-1)) * Int((((a_ + (_b_ * (x)**(Integer(2))) + (_c_ * (x)**(Integer(4)))))**((p_ + Integer(1))) * ExpandToSum(((Integer(2) * a_ * (p_ + Integer(1)) * ((_b_)**(Integer(2)) + (Integer(-1) * (Integer(4) * a_ * _c_))) * PolynomialQuotient(((x)**(m_) * Pq_), (a_ + (_b_ * (x)**(Integer(2))) + (_c_ * (x)**(Integer(4)))), x)) + ((_b_)**(Integer(2)) * Symbol('d') * ((Integer(2) * p_) + Integer(3))) + (Integer(-1) * (Integer(2) * a_ * _c_ * Symbol('d') * ((Integer(4) * p_) + Integer(5)))) + (Integer(-1) * (a_ * _b_ * Symbol('e'))) + (_c_ * ((Integer(4) * p_) + Integer(7)) * ((_b_ * Symbol('d')) + (Integer(-1) * (Integer(2) * a_ * Symbol('e')))) * (x)**(Integer(2)))), x)), x)))),
        module_name='1.2.2.6 P(x) (d x)^m (a+b x^2+c x^4)^p',
        rule_number=7,
    ),
    # Rule 8
    RubiRulePattern(
        pattern=Int(x**m_*Pq_*(x**4*_c_ + x**2*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_], x), PolyQ(Pq_, x**2), GtQ(Expon(Pq_, x**2), 1), NeQ(-4*a_*_c_ + _b_**2, 0), LtQ(p_, -1), ILtQ(m_/2, 0),),
        replacement=With(List(Set(Symbol('d'), Coeff(PolynomialRemainder(((x)**(m_) * Pq_), (a_ + (_b_ * (x)**(Integer(2))) + (_c_ * (x)**(Integer(4)))), x), x, Integer(0))), Set(Symbol('e'), Coeff(PolynomialRemainder(((x)**(m_) * Pq_), (a_ + (_b_ * (x)**(Integer(2))) + (_c_ * (x)**(Integer(4)))), x), x, Integer(2)))), ((x * ((a_ + (_b_ * (x)**(Integer(2))) + (_c_ * (x)**(Integer(4)))))**((p_ + Integer(1))) * ((a_ * _b_ * Symbol('e')) + (Integer(-1) * (Symbol('d') * ((_b_)**(Integer(2)) + (Integer(-1) * (Integer(2) * a_ * _c_))))) + (Integer(-1) * (_c_ * ((_b_ * Symbol('d')) + (Integer(-1) * (Integer(2) * a_ * Symbol('e')))) * (x)**(Integer(2))))) * ((Integer(2) * a_ * (p_ + Integer(1)) * ((_b_)**(Integer(2)) + (Integer(-1) * (Integer(4) * a_ * _c_)))))**(Integer(-1))) + (((Integer(2) * a_ * (p_ + Integer(1)) * ((_b_)**(Integer(2)) + (Integer(-1) * (Integer(4) * a_ * _c_)))))**(Integer(-1)) * Int(((x)**(m_) * ((a_ + (_b_ * (x)**(Integer(2))) + (_c_ * (x)**(Integer(4)))))**((p_ + Integer(1))) * ExpandToSum(((Integer(2) * a_ * (p_ + Integer(1)) * ((_b_)**(Integer(2)) + (Integer(-1) * (Integer(4) * a_ * _c_))) * (x)**((Integer(-1) * m_)) * PolynomialQuotient(((x)**(m_) * Pq_), (a_ + (_b_ * (x)**(Integer(2))) + (_c_ * (x)**(Integer(4)))), x)) + ((((_b_)**(Integer(2)) * Symbol('d') * ((Integer(2) * p_) + Integer(3))) + (Integer(-1) * (Integer(2) * a_ * _c_ * Symbol('d') * ((Integer(4) * p_) + Integer(5)))) + (Integer(-1) * (a_ * _b_ * Symbol('e')))) * (x)**((Integer(-1) * m_))) + (_c_ * ((Integer(4) * p_) + Integer(7)) * ((_b_ * Symbol('d')) + (Integer(-1) * (Integer(2) * a_ * Symbol('e')))) * (x)**((Integer(2) + (Integer(-1) * m_))))), x)), x)))),
        module_name='1.2.2.6 P(x) (d x)^m (a+b x^2+c x^4)^p',
        rule_number=8,
    ),
    # Rule 9
    RubiRulePattern(
        pattern=Int(Pq_*(x*_d_)**_m_*(x**4*_c_ + x**2*_b_ + a_)**_p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _d_, _m_, _p_], x), PolyQ(Pq_, x),),
        replacement=Unintegrable(Pq_*(x*_d_)**_m_*(x**4*_c_ + x**2*_b_ + a_)**_p_, x),
        module_name='1.2.2.6 P(x) (d x)^m (a+b x^2+c x^4)^p',
        rule_number=9,
    ),

]

# Summary: 9 rules translated, 0 skipped
