# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_rules/codegen/generate.py
# Source: 1.1.4.3 (e x)^m (a x^j+b x^k)^p (c+d x^n)^q.m
# Module: 1.1.4.3 (e x)^m (a x^j+b x^k)^p (c+d x^n)^q
#
# This file contains Rubi integration rules as RubiRulePattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Integer, Integral, Lambda, Rational, Symbol, Tuple as SympyTuple, Eq, Ne, Lt, Gt, Le, Ge, log, sqrt, pi, I, oo
from rubi_rules.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (sin, cos, tan, sec, csc, cot, asin, acos, atan, atan2, asec, acsc, acot,
                   sinh, cosh, tanh, sech, csch, coth, asinh, acosh, atanh, asech, acsch, acoth,
                   exp, Abs, diff, denom, frac, floor, root, simplify,
                   elliptic_e, elliptic_f, hyper, appellf1)

from sympy_objects.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_rules.base_objects import Int, RubiRulePattern
from rubi_rules.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, OddQ, EvenQ, NumberQ, NumericQ, AtomQ, MemberQ,
    PositiveQ, NegativeQ, PolynomialQ, TrueQ, FalseQ, MatchQ, PrimeQ, UnsameQ,
    # RUBI-specific constraints
    EqQ, NeQ, IGtQ, ILtQ, IGeQ, ILeQ, GtQ, LtQ, GeQ, LeQ, PosQ, NegQ,
    IntegersQ, HalfIntegerQ, FractionQ, RationalQ, ComplexNumberQ, RealNumberQ,
    FractionOrNegativeQ, SqrtNumberQ, PowerQ, ProductQ, SumQ, NonsumQ,
    IntegerPowerQ, FractionalPowerQ, PolyQ, LinearQ, QuadraticQ, BinomialQ,
    TrinomialQ, LinearMatchQ, QuadraticMatchQ, BinomialMatchQ, TrinomialMatchQ,
    TrigQ, HyperbolicQ, InverseTrigQ, InverseHyperbolicQ, LogQ, ComplexFreeQ,
    InverseFunctionFreeQ, FractionalPowerFreeQ, TrigHyperbolicFreeQ, IntegralFreeQ,
    RationalFunctionQ, AlgebraicFunctionQ, IndependentQ, SimplerQ, SumSimplerQ,
    FunctionOfQ, PiecewiseLinearQ, ExpressionEqQ,
    IntLinearQ, IntBinomialQ, IntQuadraticQ,
    MonomialQ, LinearPairQ,
    GeneralizedBinomialQ, GeneralizedBinomialMatchQ,
    GeneralizedTrinomialQ, GeneralizedTrinomialMatchQ,
    NiceSqrtQ, SimplerSqrtQ, FractionalPowerFactorQ,
    SumBaseQ, InverseFunctionQ, InertTrigQ, InertTrigFreeQ,
    CalculusFreeQ, QuotientOfLinearsQ,
    PowerOfLinearQ, PowerOfLinearMatchQ,
    FunctionOfExponentialQ,
    KnownSineIntegrandQ, KnownSecantIntegrandQ,
    KnownTangentIntegrandQ, KnownCotangentIntegrandQ,
    EulerIntegrandQ, SubstForFractionalPowerQ,
    PerfectSquareQ, PolynomialInQ, FunctionOfTrigOfLinearQ,
    SimplerIntegrandQ, PseudoBinomialPairQ, QuadraticProductQ,
    EveryQ, TrigSimplifyQ, EqM, TryPureTanSubst,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

_a_ = WildSymbol('a', optional_value=IDENTITY_ELEMENT)
a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
_j_ = WildSymbol('j', optional_value=IDENTITY_ELEMENT)
j_ = WildSymbol('j')
_jn_ = WildSymbol('jn', optional_value=IDENTITY_ELEMENT)
jn_ = WildSymbol('jn')
_k_ = WildSymbol('k', optional_value=IDENTITY_ELEMENT)
k_ = WildSymbol('k')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')
p_ = WildSymbol('p')
_q_ = WildSymbol('q', optional_value=IDENTITY_ELEMENT)
q_ = WildSymbol('q')

RULES = [
    # Rule 1
    RubiRulePattern(
        pattern=Int(x**_m_*(x**j_*_a_ + x**_k_*_b_)**p_*(x**n_*_d_ + c_)**_q_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, j_, _k_, _m_, n_, p_, _q_], x), Not(IntegerQ(p_)), NeQ(_k_, j_), IntegerQ(j_/n_), IntegerQ(_k_/n_), IntegerQ((_m_ + 1)/n_), NeQ(n_**2, 1),),
        replacement=Subst(Int(x**(-1 + (_m_ + 1)/n_)*(x*_d_ + c_)**_q_*(x**(j_/n_)*_a_ + x**(_k_/n_)*_b_)**p_, x), x, x**n_)/n_,
        module_name='1.1.4.3 (e x)^m (a x^j+b x^k)^p (c+d x^n)^q',
        rule_number=1,
    ),
    # Rule 2
    RubiRulePattern(
        pattern=Int((x*e_)**_m_*(x**j_*_a_ + x**_k_*_b_)**p_*(x**_n_*_d_ + c_)**_q_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, e_, j_, _k_, _m_, _n_, p_, _q_], x), Not(IntegerQ(p_)), NeQ(_k_, j_), IntegerQ(j_/_n_), IntegerQ(_k_/_n_), IntegerQ((_m_ + 1)/_n_), NeQ(_n_**2, 1),),
        replacement=e_**IntPart(_m_)*(x*e_)**FracPart(_m_)*Int(x**_m_*(x**j_*_a_ + x**_k_*_b_)**p_*(x**_n_*_d_ + c_)**_q_, x)/x**FracPart(_m_),
        module_name='1.1.4.3 (e x)^m (a x^j+b x^k)^p (c+d x^n)^q',
        rule_number=2,
    ),
    # Rule 3
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*(x**_j_*_a_ + x**_jn_*_b_)**p_*(x**_n_*_d_ + c_), x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _e_, _j_, _m_, _n_, p_], x), EqQ(_jn_, _j_ + _n_), Not(IntegerQ(p_)), NeQ(-_a_*_d_ + _b_*c_, 0), EqQ(_a_*_d_*(_j_*p_ + _m_ + 1) - _b_*c_*(_m_ + _n_ + p_*(_j_ + _n_) + 1), 0), Or(GtQ(_e_, 0), IntegersQ(_j_)), NeQ(_j_*p_ + _m_ + 1, 0),),
        replacement=c_*_e_**(_j_ - 1)*(x*_e_)**(-_j_ + _m_ + 1)*(x**_j_*_a_ + x**(_j_ + _n_)*_b_)**(p_ + 1)/(_a_*(_j_*p_ + _m_ + 1)),
        module_name='1.1.4.3 (e x)^m (a x^j+b x^k)^p (c+d x^n)^q',
        rule_number=3,
    ),
    # Rule 4
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*(x**_j_*_a_ + x**_jn_*_b_)**p_*(x**_n_*_d_ + c_), x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _e_, _j_, _m_, _n_], x), EqQ(_jn_, _j_ + _n_), Not(IntegerQ(p_)), NeQ(-_a_*_d_ + _b_*c_, 0), LtQ(p_, -1), GtQ(_j_, 0), LeQ(_j_, _m_), Or(GtQ(_e_, 0), IntegerQ(_j_)),),
        replacement=-_e_**_j_*(_a_*_d_*(_j_*p_ + _m_ + 1) - _b_*c_*(_m_ + _n_ + p_*(_j_ + _n_) + 1))*Int((x*_e_)**(-_j_ + _m_)*(x**_j_*_a_ + x**(_j_ + _n_)*_b_)**(p_ + 1), x)/(_a_*_b_*_n_*(p_ + 1)) - _e_**(_j_ - 1)*(x*_e_)**(-_j_ + _m_ + 1)*(x**_j_*_a_ + x**(_j_ + _n_)*_b_)**(p_ + 1)*(-_a_*_d_ + _b_*c_)/(_a_*_b_*_n_*(p_ + 1)),
        module_name='1.1.4.3 (e x)^m (a x^j+b x^k)^p (c+d x^n)^q',
        rule_number=4,
    ),
    # Rule 5
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*(x**_j_*_a_ + x**_jn_*_b_)**p_*(x**_n_*_d_ + c_), x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _e_, _j_, p_], x), EqQ(_jn_, _j_ + _n_), Not(IntegerQ(p_)), NeQ(-_a_*_d_ + _b_*c_, 0), GtQ(_n_, 0), Or(LtQ(_j_*p_ + _m_, -1), And(IntegersQ(_m_ + sympy.S(-1)/2, p_ + sympy.S(-1)/2), LtQ(p_, 0), LtQ(_m_, -_n_*p_ - 1))), Or(GtQ(_e_, 0), IntegersQ(_j_, _n_)), NeQ(_j_*p_ + _m_ + 1, 0), NeQ(_j_*p_ + _m_ - _n_ + 1, 0),),
        replacement=c_*_e_**(_j_ - 1)*(x*_e_)**(-_j_ + _m_ + 1)*(x**_j_*_a_ + x**(_j_ + _n_)*_b_)**(p_ + 1)/(_a_*(_j_*p_ + _m_ + 1)) + (_a_*_d_*(_j_*p_ + _m_ + 1) - _b_*c_*(_m_ + _n_ + p_*(_j_ + _n_) + 1))*Int((x*_e_)**(_m_ + _n_)*(x**_j_*_a_ + x**(_j_ + _n_)*_b_)**p_, x)/(_a_*_e_**_n_*(_j_*p_ + _m_ + 1)),
        module_name='1.1.4.3 (e x)^m (a x^j+b x^k)^p (c+d x^n)^q',
        rule_number=5,
    ),
    # Rule 6
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*(x**_j_*_a_ + x**_jn_*_b_)**p_*(x**_n_*_d_ + c_), x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _e_, _j_, _m_, _n_, p_], x), EqQ(_jn_, _j_ + _n_), Not(IntegerQ(p_)), NeQ(-_a_*_d_ + _b_*c_, 0), NeQ(_m_ + _n_ + p_*(_j_ + _n_) + 1, 0), Or(GtQ(_e_, 0), IntegerQ(_j_)),),
        replacement=_d_*_e_**(_j_ - 1)*(x*_e_)**(-_j_ + _m_ + 1)*(x**_j_*_a_ + x**(_j_ + _n_)*_b_)**(p_ + 1)/(_b_*(_m_ + _n_ + p_*(_j_ + _n_) + 1)) - (_a_*_d_*(_j_*p_ + _m_ + 1) - _b_*c_*(_m_ + _n_ + p_*(_j_ + _n_) + 1))*Int((x*_e_)**_m_*(x**_j_*_a_ + x**(_j_ + _n_)*_b_)**p_, x)/(_b_*(_m_ + _n_ + p_*(_j_ + _n_) + 1)),
        module_name='1.1.4.3 (e x)^m (a x^j+b x^k)^p (c+d x^n)^q',
        rule_number=6,
    ),
    # Rule 7
    RubiRulePattern(
        pattern=Int(x**_m_*(x**j_*_a_ + x**_k_*_b_)**p_*(x**_n_*_d_ + c_)**_q_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, j_, _k_, _m_, _n_, p_, _q_], x), Not(IntegerQ(p_)), NeQ(_k_, j_), IntegerQ(j_/_n_), IntegerQ(_k_/_n_), NeQ(_m_, -1), IntegerQ(_n_/(_m_ + 1)), Not(IntegerQ(_n_)),),
        replacement=Subst(Int((x**(j_/(_m_ + 1))*_a_ + x**(_k_/(_m_ + 1))*_b_)**p_*(x**(_n_/(_m_ + 1))*_d_ + c_)**_q_, x), x, x**(_m_ + 1))/(_m_ + 1),
        module_name='1.1.4.3 (e x)^m (a x^j+b x^k)^p (c+d x^n)^q',
        rule_number=7,
    ),
    # Rule 8
    RubiRulePattern(
        pattern=Int((x*e_)**_m_*(x**j_*_a_ + x**_k_*_b_)**p_*(x**_n_*_d_ + c_)**_q_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, e_, j_, _k_, _m_, _n_, p_, _q_], x), Not(IntegerQ(p_)), NeQ(_k_, j_), IntegerQ(j_/_n_), IntegerQ(_k_/_n_), NeQ(_m_, -1), IntegerQ(_n_/(_m_ + 1)), Not(IntegerQ(_n_)),),
        replacement=e_**IntPart(_m_)*(x*e_)**FracPart(_m_)*Int(x**_m_*(x**j_*_a_ + x**_k_*_b_)**p_*(x**_n_*_d_ + c_)**_q_, x)/x**FracPart(_m_),
        module_name='1.1.4.3 (e x)^m (a x^j+b x^k)^p (c+d x^n)^q',
        rule_number=8,
    ),
    # Rule 9
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*(x**_j_*_a_ + x**_jn_*_b_)**p_*(x**_n_*_d_ + c_)**_q_, x),
        constraints=(FreeQ([_a_, _b_, c_, _d_, _e_, _j_, _m_, _n_, p_, _q_], x), EqQ(_jn_, _j_ + _n_), Not(IntegerQ(p_)), NeQ(-_a_*_d_ + _b_*c_, 0), Not(And(EqQ(_n_, 1), EqQ(_j_, 1))),),
        replacement=x**(-_j_*FracPart(p_) - FracPart(_m_))*_e_**IntPart(_m_)*(x*_e_)**FracPart(_m_)*(x**_j_*_a_ + x**(_j_ + _n_)*_b_)**FracPart(p_)*Int(x**(_j_*p_ + _m_)*(x**_n_*_b_ + _a_)**p_*(x**_n_*_d_ + c_)**_q_, x)/(x**_n_*_b_ + _a_)**FracPart(p_),
        module_name='1.1.4.3 (e x)^m (a x^j+b x^k)^p (c+d x^n)^q',
        rule_number=9,
    ),

]

# Summary: 9 rules translated, 0 skipped
