# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_rules/codegen/generate.py
# Source: 1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q.m
# Module: 1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q
#
# This file contains Rubi integration rules as RubiRulePattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Integer, Integral, Lambda, Rational, Symbol, Tuple as SympyTuple, Eq, Ne, Lt, Gt, Le, Ge, log, sqrt, pi, I, oo
from rubi_rules.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (sin, cos, tan, sec, csc, cot, asin, acos, atan, atan2, asec, acsc, acot,
                   sinh, cosh, tanh, sech, csch, coth, asinh, acosh, atanh, asech, acsch, acoth,
                   exp, Abs, diff, denom, frac, floor, root, simplify,
                   elliptic_e, elliptic_f, hyper, appellf1)

from sympy_objects.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_rules.base_objects import Int, RubiRulePattern
from rubi_rules.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, OddQ, EvenQ, NumberQ, NumericQ, AtomQ, MemberQ,
    PositiveQ, NegativeQ, PolynomialQ, TrueQ, FalseQ, MatchQ, PrimeQ, UnsameQ,
    # RUBI-specific constraints
    EqQ, NeQ, IGtQ, ILtQ, IGeQ, ILeQ, GtQ, LtQ, GeQ, LeQ, PosQ, NegQ,
    IntegersQ, HalfIntegerQ, FractionQ, RationalQ, ComplexNumberQ, RealNumberQ,
    FractionOrNegativeQ, SqrtNumberQ, PowerQ, ProductQ, SumQ, NonsumQ,
    IntegerPowerQ, FractionalPowerQ, PolyQ, LinearQ, QuadraticQ, BinomialQ,
    TrinomialQ, LinearMatchQ, QuadraticMatchQ, BinomialMatchQ, TrinomialMatchQ,
    TrigQ, HyperbolicQ, InverseTrigQ, InverseHyperbolicQ, LogQ, ComplexFreeQ,
    InverseFunctionFreeQ, FractionalPowerFreeQ, TrigHyperbolicFreeQ, IntegralFreeQ,
    RationalFunctionQ, AlgebraicFunctionQ, IndependentQ, SimplerQ, SumSimplerQ,
    FunctionOfQ, PiecewiseLinearQ, ExpressionEqQ,
    IntLinearQ, IntBinomialQ, IntQuadraticQ,
    MonomialQ, LinearPairQ,
    GeneralizedBinomialQ, GeneralizedBinomialMatchQ,
    GeneralizedTrinomialQ, GeneralizedTrinomialMatchQ,
    NiceSqrtQ, SimplerSqrtQ, FractionalPowerFactorQ,
    SumBaseQ, InverseFunctionQ, InertTrigQ, InertTrigFreeQ,
    CalculusFreeQ, QuotientOfLinearsQ,
    PowerOfLinearQ, PowerOfLinearMatchQ,
    FunctionOfExponentialQ,
    KnownSineIntegrandQ, KnownSecantIntegrandQ,
    KnownTangentIntegrandQ, KnownCotangentIntegrandQ,
    EulerIntegrandQ, SubstForFractionalPowerQ,
    PerfectSquareQ, PolynomialInQ, FunctionOfTrigOfLinearQ,
    SimplerIntegrandQ, PseudoBinomialPairQ, QuadraticProductQ,
    EveryQ, TrigSimplifyQ, EqM, TryPureTanSubst,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

a_ = WildSymbol('a')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
_e_ = WildSymbol('e', optional_value=IDENTITY_ELEMENT)
e_ = WildSymbol('e')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_p_ = WildSymbol('p', optional_value=IDENTITY_ELEMENT)
p_ = WildSymbol('p')
_q_ = WildSymbol('q', optional_value=IDENTITY_ELEMENT)
q_ = WildSymbol('q')

RULES = [
    # Rule 1
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*(x**2*_b_ + a_)**_p_*(x**2*_d_ + c_)**_p_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_, _m_, _p_], x), EqQ(a_*_d_ + _b_*c_, 0), Or(IntegerQ(_p_), And(GtQ(a_, 0), GtQ(c_, 0))),),
        replacement=Int((x*_e_)**_m_*(x**4*_b_*_d_ + a_*c_)**_p_, x),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=1,
    ),
    # Rule 2
    RubiRulePattern(
        pattern=Int(x**3*(x**2*_b_ + a_)**p_*(x**2*_d_ + c_)**p_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, p_], x), EqQ(a_*_d_ + _b_*c_, 0),),
        replacement=(x**2*_b_ + a_)**(p_ + 1)*(x**2*_d_ + c_)**(p_ + 1)/(4*_b_*_d_*(p_ + 1)),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=2,
    ),
    # Rule 3
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*(x**2*_b_ + a_)**p_*(x**2*_d_ + c_)**p_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_, _m_, p_], x), EqQ(a_*_d_ + _b_*c_, 0), EqQ(_m_ + 4*p_ + 5, 0),),
        replacement=-(x*_e_)**(_m_ + 1)*(x**2*_b_ + a_)**(p_ + 1)*(x**2*_d_ + c_)**(p_ + 1)/(4*a_*c_*_e_*(p_ + 1)),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=3,
    ),
    # Rule 4
    RubiRulePattern(
        pattern=Int(x**_m_*(x**2*_b_ + a_)**p_*(x**2*_d_ + c_)**p_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, p_], x), EqQ(a_*_d_ + _b_*c_, 0), IntegerQ(_m_/2 + sympy.S(-1)/2),),
        replacement=((sympy.Function('2')(Symbol('Star')))**(Integer(-1)) * Subst(Int(((x)**(((_m_ + Integer(-1)) * (Integer(2))**(Integer(-1)))) * ((a_ + (_b_ * x)))**(p_) * ((c_ + (_d_ * x)))**(p_)), x), x, (x)**(Integer(2)))),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=4,
    ),
    # Rule 5: SKIPPED - ValueError: Non-string function head ['Times', ['Power', 'e', '4'], ['Plus', 'm', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 6: SKIPPED - ValueError: Non-string function head ['Plus', 'm', ['Times', '4', 'p'], '1'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 7: SKIPPED - ValueError: Non-string function head ['Times', '4', 'b', 'd', ['Plus', 'p', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 8: SKIPPED - ValueError: Non-string function head ['Times', '4', 'a', 'c', ['Plus', 'p', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 9: SKIPPED - ValueError: Non-string function head ['Times', 'a', 'c', ['Power', 'e', '4'], ['Plus', 'm', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 10: SKIPPED - ValueError: Non-string function head ['FracPart', 'p'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 11: SKIPPED - ValueError: Non-string function head ['Times', '2', ['Power', 'b', ['Times', ['Plus', 'm', '-1'], ['Power', '2', '-1']]]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 12: SKIPPED - ValueError: Non-string function head ['Times', '2', ['FracPart', 'p']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 13: SKIPPED - ValueError: Non-string function head ['FracPart', 'm'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 14
    RubiRulePattern(
        pattern=Int(x/((x**2*_b_ + a_)**(sympy.S(1)/4)*(x**2*_d_ + c_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_], x), EqQ(-2*a_*_d_ + _b_*c_, 0), PosQ(a_),),
        replacement=-sqrt(2)*atan(sqrt(2)*(sqrt(a_) - sqrt(x**2*_b_ + a_))/(2*a_**(sympy.S(1)/4)*(x**2*_b_ + a_)**(sympy.S(1)/4)))/(2*a_**(sympy.S(1)/4)*_d_) - sqrt(2)*atanh(sqrt(2)*(sqrt(a_) + sqrt(x**2*_b_ + a_))/(2*a_**(sympy.S(1)/4)*(x**2*_b_ + a_)**(sympy.S(1)/4)))/(2*a_**(sympy.S(1)/4)*_d_),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=14,
    ),
    # Rule 15
    RubiRulePattern(
        pattern=Int(x**m_/((x**2*_b_ + a_)**(sympy.S(1)/4)*(x**2*_d_ + c_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_], x), EqQ(-2*a_*_d_ + _b_*c_, 0), IntegerQ(m_), Or(PosQ(a_), IntegerQ(m_/2)),),
        replacement=Int(ExpandIntegrand(x**m_/((x**2*_b_ + a_)**(sympy.S(1)/4)*(x**2*_d_ + c_)), x), x),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=15,
    ),
    # Rule 16
    RubiRulePattern(
        pattern=Int(x**2/((x**2*_b_ + a_)**(sympy.S(3)/4)*(x**2*_d_ + c_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_], x), EqQ(-2*a_*_d_ + _b_*c_, 0), PosQ(_b_**2/a_),),
        replacement=-_b_*atan((_b_ + sqrt(_b_**2/a_)*sqrt(x**2*_b_ + a_))/(x*(_b_**2/a_)**(sympy.S(3)/4)*(x**2*_b_ + a_)**(sympy.S(1)/4)))/(a_*_d_*(_b_**2/a_)**(sympy.S(3)/4)) + _b_*atanh((_b_ - sqrt(_b_**2/a_)*sqrt(x**2*_b_ + a_))/(x*(_b_**2/a_)**(sympy.S(3)/4)*(x**2*_b_ + a_)**(sympy.S(1)/4)))/(a_*_d_*(_b_**2/a_)**(sympy.S(3)/4)),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=16,
    ),
    # Rule 17
    RubiRulePattern(
        pattern=Int(x**2/((x**2*_b_ + a_)**(sympy.S(3)/4)*(x**2*_d_ + c_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_], x), EqQ(-2*a_*_d_ + _b_*c_, 0), NegQ(_b_**2/a_),),
        replacement=-sqrt(2)*_b_*atan(sqrt(2)*x*(-_b_**2/a_)**(sympy.S(1)/4)/(2*(x**2*_b_ + a_)**(sympy.S(1)/4)))/(2*a_*_d_*(-_b_**2/a_)**(sympy.S(3)/4)) + sqrt(2)*_b_*atanh(sqrt(2)*x*(-_b_**2/a_)**(sympy.S(1)/4)/(2*(x**2*_b_ + a_)**(sympy.S(1)/4)))/(2*a_*_d_*(-_b_**2/a_)**(sympy.S(3)/4)),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=17,
    ),
    # Rule 18
    RubiRulePattern(
        pattern=Int(x**m_/((x**2*_b_ + a_)**(sympy.S(3)/4)*(x**2*_d_ + c_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_], x), EqQ(-2*a_*_d_ + _b_*c_, 0), IntegerQ(m_), Or(PosQ(a_), IntegerQ(m_/2)),),
        replacement=Int(ExpandIntegrand(x**m_/((x**2*_b_ + a_)**(sympy.S(3)/4)*(x**2*_d_ + c_)), x), x),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=18,
    ),
    # Rule 19
    RubiRulePattern(
        pattern=Int(x*(x**2*_b_ + a_)**_p_*(x**2*_d_ + c_)**_q_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _p_, _q_], x), NeQ(-a_*_d_ + _b_*c_, 0),),
        replacement=((sympy.Function('2')(Symbol('Star')))**(Integer(-1)) * Subst(Int((((a_ + (_b_ * x)))**(_p_) * ((c_ + (_d_ * x)))**(_q_)), x), x, (x)**(Integer(2)))),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=19,
    ),
    # Rule 20
    RubiRulePattern(
        pattern=Int(x**_m_*(x**2*_b_ + a_)**_p_*(x**2*_d_ + c_)**_q_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _p_, _q_], x), NeQ(-a_*_d_ + _b_*c_, 0), IntegerQ(_m_/2 + sympy.S(-1)/2),),
        replacement=((sympy.Function('2')(Symbol('Star')))**(Integer(-1)) * Subst(Int(((x)**(((_m_ + Integer(-1)) * (Integer(2))**(Integer(-1)))) * ((a_ + (_b_ * x)))**(_p_) * ((c_ + (_d_ * x)))**(_q_)), x), x, (x)**(Integer(2)))),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=20,
    ),
    # Rule 21
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*(x**2*_b_ + a_)**_p_*(x**2*_d_ + c_)**_q_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_, _m_], x), NeQ(-a_*_d_ + _b_*c_, 0), IGtQ(_p_, 0), IGtQ(_q_, 0),),
        replacement=Int(ExpandIntegrand((x*_e_)**_m_*(x**2*_b_ + a_)**_p_*(x**2*_d_ + c_)**_q_, x), x),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=21,
    ),
    # Rule 22
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*(x**2*_b_ + a_)**_p_*(x**2*_d_ + c_), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_, _m_, _p_], x), NeQ(-a_*_d_ + _b_*c_, 0), EqQ(a_*_d_*(_m_ + 1) - _b_*c_*(_m_ + 2*_p_ + 3), 0), NeQ(_m_, -1),),
        replacement=c_*(x*_e_)**(_m_ + 1)*(x**2*_b_ + a_)**(_p_ + 1)/(a_*_e_*(_m_ + 1)),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=22,
    ),
    # Rule 23
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*(x**2*_b_ + a_)**p_*(x**2*_d_ + c_), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_], x), NeQ(-a_*_d_ + _b_*c_, 0), EqQ(_m_ + 2*p_ + 3, 0), LtQ(p_, -1),),
        replacement=((((_b_ * c_) + (Integer(-1) * (a_ * _d_))) * ((_e_ * x))**((_m_ + Integer(1))) * ((a_ + (_b_ * (x)**(Integer(2)))))**((p_ + Integer(1))) * ((a_ * _b_ * _e_ * (_m_ + Integer(1))))**(Integer(-1))) + (_d_ * (sympy.Function('b')(Symbol('Star')))**(Integer(-1)) * Int((((_e_ * x))**(_m_) * ((a_ + (_b_ * (x)**(Integer(2)))))**((p_ + Integer(1)))), x))),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=23,
    ),
    # Rule 24
    RubiRulePattern(
        pattern=Int((x*_e_)**m_*(x**2*_b_ + a_)**_p_*(x**2*_d_ + c_), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_, m_, _p_], x), NeQ(-a_*_d_ + _b_*c_, 0), EqQ(m_ + 2*_p_ + 3, 0), NeQ(m_, -1),),
        replacement=((c_ * ((_e_ * x))**((m_ + Integer(1))) * ((a_ + (_b_ * (x)**(Integer(2)))))**((_p_ + Integer(1))) * ((a_ * _e_ * (m_ + Integer(1))))**(Integer(-1))) + (_d_ * ((_e_)**(sympy.Function('2')(Symbol('Star'))))**(Integer(-1)) * Int((((_e_ * x))**((m_ + Integer(2))) * ((a_ + (_b_ * (x)**(Integer(2)))))**(_p_)), x))),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=24,
    ),
    # Rule 25: SKIPPED - ValueError: Non-string function head ['Times', 'a', ['Power', 'e', '2'], ['Plus', 'm', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 26: SKIPPED - ValueError: Non-string function head ['Times', '2', ['Power', 'b', ['Plus', ['Times', 'm', ['Power', '2', '-1']], '1']], ['Plus', 'p', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 27: SKIPPED - ValueError: Non-string function head ['Times', '2', ['Power', 'b', ['Plus', ['Times', 'm', ['Power', '2', '-1']], '1']], ['Plus', 'p', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 28: SKIPPED - ValueError: Non-string function head ['Times', '2', 'a', 'b', ['Plus', 'p', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 29: SKIPPED - ValueError: Non-string function head ['Times', 'b', ['Plus', 'm', ['Times', '2', 'p'], '3']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 30
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*(x**2*_b_ + a_)**p_/(x**2*_d_ + c_), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_, _m_], x), NeQ(-a_*_d_ + _b_*c_, 0), IGtQ(p_, 0), Or(IntegerQ(_m_), IGtQ(2*_m_ + 2, 0), Not(RationalQ(_m_))),),
        replacement=Int(ExpandIntegrand((x*_e_)**_m_*(x**2*_b_ + a_)**p_/(x**2*_d_ + c_), x), x),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=30,
    ),
    # Rule 31: SKIPPED - ValueError: Non-string function head ['Times', 'a', ['Power', 'e', '2'], ['Plus', 'm', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 32: SKIPPED - ValueError: Non-string function head ['Times', '2', 'a', ['Power', 'b', '2'], ['Plus', 'p', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 33: SKIPPED - ValueError: Non-string function head ['Times', 'b', ['Plus', 'm', ['Times', '2', 'p'], '5']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 34
    RubiRulePattern(
        pattern=Int((x*_e_)**m_*(x**2*_b_ + a_)**p_*(x**2*_d_ + c_)**q_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_, p_, q_], x), NeQ(-a_*_d_ + _b_*c_, 0), FractionQ(m_), IntegerQ(p_),),
        replacement=With(List(Set(Symbol('k'), Denominator(m_))), (Symbol('k') * (sympy.Function('e')(Symbol('Star')))**(Integer(-1)) * Subst(Int(((x)**(((Symbol('k') * (m_ + Integer(1))) + Integer(-1))) * ((a_ + (_b_ * (x)**((Symbol('k') * Integer(2))) * ((_e_)**(Integer(2)))**(Integer(-1)))))**(p_) * ((c_ + (_d_ * (x)**((Symbol('k') * Integer(2))) * ((_e_)**(Integer(2)))**(Integer(-1)))))**(q_)), x), x, ((_e_ * x))**((Symbol('k'))**(Integer(-1)))))),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=34,
    ),
    # Rule 35: SKIPPED - ValueError: Non-string function head ['Times', '2', 'b', ['Plus', 'p', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 36: SKIPPED - ValueError: Non-string function head ['Times', '2', 'a', 'b', ['Plus', 'p', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 37: SKIPPED - ValueError: Non-string function head ['Times', '2', 'a', ['Plus', 'p', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 38: SKIPPED - ValueError: Non-string function head ['Times', '2', 'b', ['Plus', ['Times', 'b', 'c'], ['Times', '-1', ['Times', 'a', 'd']]], ['Plus', 'p', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 39: SKIPPED - ValueError: Non-string function head ['Times', '2', ['Plus', ['Times', 'b', 'c'], ['Times', '-1', ['Times', 'a', 'd']]], ['Plus', 'p', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 40: SKIPPED - ValueError: Non-string function head ['Times', '2', 'a', ['Plus', ['Times', 'b', 'c'], ['Times', '-1', ['Times', 'a', 'd']]], ['Plus', 'p', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 42: SKIPPED - ValueError: Non-string function head ['Times', ['Power', 'e', '2'], ['Plus', 'm', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 43: SKIPPED - ValueError: Non-string function head ['Times', 'a', ['Power', 'e', '2'], ['Plus', 'm', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 44: SKIPPED - ValueError: Non-string function head ['Times', 'a', ['Power', 'e', '2'], ['Plus', 'm', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 45: SKIPPED - ValueError: Non-string function head ['Plus', 'm', ['Times', '2', ['Plus', 'p', 'q']], '1'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 46: SKIPPED - ValueError: Non-string function head ['Times', 'b', ['Plus', 'm', ['Times', '2', ['Plus', 'p', 'q']], '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 47: SKIPPED - ValueError: Non-string function head ['Times', 'b', ['Plus', 'm', ['Times', '2', ['Plus', 'p', 'q']], '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 49: SKIPPED - ValueError: Non-string function head ['Times', 'b', 'd', ['Plus', 'm', ['Times', '2', ['Plus', 'p', 'q']], '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 51: SKIPPED - ValueError: Non-string function head ['Times', 'a', 'c', ['Power', 'e', '2'], ['Plus', 'm', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 53: SKIPPED - ValueError: Non-string function head ['Plus', ['Times', 'b', 'c'], ['Times', '-1', ['Times', 'a', 'd']]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 54: SKIPPED - ValueError: Non-string function head ['Plus', ['Times', 'b', 'c'], ['Times', '-1', ['Times', 'a', 'd']]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 55
    RubiRulePattern(
        pattern=Int((x*_e_)**m_*(x**2*_d_ + c_)**_q_/(x**2*_b_ + a_), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_, m_, _q_], x), NeQ(-a_*_d_ + _b_*c_, 0), LeQ(2, m_, 3), IntBinomialQ(a_, _b_, c_, _d_, _e_, m_, 2, -1, _q_, x),),
        replacement=(((_e_)**(Integer(2)) * (sympy.Function('b')(Symbol('Star')))**(Integer(-1)) * Int((((_e_ * x))**((m_ + Integer(-2))) * ((c_ + (_d_ * (x)**(Integer(2)))))**(_q_)), x)) + (Integer(-1) * (a_ * (_e_)**(Integer(2)) * (sympy.Function('b')(Symbol('Star')))**(Integer(-1)) * Int((((_e_ * x))**((m_ + Integer(-2))) * ((c_ + (_d_ * (x)**(Integer(2)))))**(_q_) * ((a_ + (_b_ * (x)**(Integer(2)))))**(Integer(-1))), x)))),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=55,
    ),
    # Rule 56
    RubiRulePattern(
        pattern=Int(x*(x**2*_b_ + a_)**p_/(x**2*_d_ + c_), x),
        constraints=(FreeQ([a_, _b_, c_, _d_], x), NeQ(-a_*_d_ + _b_*c_, 0), GtQ(p_, 0), IntBinomialQ(a_, _b_, c_, _d_, 1, 1, 2, p_, -1, x),),
        replacement=((_b_ * (sympy.Function('d')(Symbol('Star')))**(Integer(-1)) * Int((x * ((a_ + (_b_ * (x)**(Integer(2)))))**((p_ + Integer(-1)))), x)) + (Integer(-1) * (((_b_ * c_) + (Integer(-1) * (a_ * _d_))) * (sympy.Function('d')(Symbol('Star')))**(Integer(-1)) * Int((x * ((a_ + (_b_ * (x)**(Integer(2)))))**((p_ + Integer(-1))) * ((c_ + (_d_ * (x)**(Integer(2)))))**(Integer(-1))), x)))),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=56,
    ),
    # Rule 57: SKIPPED - ValueError: Non-string function head ['Plus', ['Times', 'b', 'c'], ['Times', '-1', ['Times', 'a', 'd']]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 58
    RubiRulePattern(
        pattern=Int(x**2/(sqrt(x**2*_b_ + a_)*sqrt(x**2*_d_ + c_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_], x), NeQ(-a_*_d_ + _b_*c_, 0), PosQ(_b_/a_), PosQ(_d_/c_), Not(SimplerSqrtQ(_b_/a_, _d_/c_)),),
        replacement=((x * sympy.sqrt((a_ + (_b_ * (x)**(Integer(2))))) * ((_b_ * sympy.sqrt((c_ + (_d_ * (x)**(Integer(2)))))))**(Integer(-1))) + (Integer(-1) * (c_ * (sympy.Function('b')(Symbol('Star')))**(Integer(-1)) * Int((sympy.sqrt((a_ + (_b_ * (x)**(Integer(2))))) * (((c_ + (_d_ * (x)**(Integer(2)))))**((Integer(3) * (Integer(2))**(Integer(-1)))))**(Integer(-1))), x)))),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=58,
    ),
    # Rule 59
    RubiRulePattern(
        pattern=Int(x**2/(sqrt(x**2*_b_ + a_)*sqrt(x**2*_d_ + c_)), x),
        constraints=(FreeQ([a_, _b_, c_, _d_], x), NeQ(-a_*_d_ + _b_*c_, 0), Not(SimplerSqrtQ(-_b_/a_, -_d_/c_)),),
        replacement=(((sympy.Function('b')(Symbol('Star')))**(Integer(-1)) * Int((sympy.sqrt((a_ + (_b_ * (x)**(Integer(2))))) * (sympy.sqrt((c_ + (_d_ * (x)**(Integer(2))))))**(Integer(-1))), x)) + (Integer(-1) * (a_ * (sympy.Function('b')(Symbol('Star')))**(Integer(-1)) * Int(((sympy.sqrt((a_ + (_b_ * (x)**(Integer(2))))) * sympy.sqrt((c_ + (_d_ * (x)**(Integer(2)))))))**(Integer(-1)), x)))),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=59,
    ),
    # Rule 60
    RubiRulePattern(
        pattern=Int(x**_m_*(x**2*_b_ + a_)**p_*(x**2*_d_ + c_)**_q_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_], x), RationalQ(_m_, p_), IntegersQ(_m_/2 + p_ + sympy.S.Half, _q_), LtQ(-1, p_, 0),),
        replacement=With(List(Set(Symbol('k'), Denominator(p_))), (Symbol('k') * (a_)**((p_ + ((_m_ + Integer(1)) * (Integer(2))**(Integer(-1))))) * (sympy.Function('2')(Symbol('Star')))**(Integer(-1)) * Subst(Int(((x)**(((Symbol('k') * (_m_ + Integer(1)) * (Integer(2))**(Integer(-1))) + Integer(-1))) * ((c_ + (Integer(-1) * (((_b_ * c_) + (Integer(-1) * (a_ * _d_))) * (x)**(Symbol('k'))))))**(_q_) * (((Integer(1) + (Integer(-1) * (_b_ * (x)**(Symbol('k'))))))**((p_ + _q_ + ((_m_ + Integer(1)) * (Integer(2))**(Integer(-1))) + Integer(1))))**(Integer(-1))), x), x, ((x)**((Integer(2) * (Symbol('k'))**(Integer(-1)))) * (((a_ + (_b_ * (x)**(Integer(2)))))**((Symbol('k'))**(Integer(-1))))**(Integer(-1)))))),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=60,
    ),
    # Rule 61: SKIPPED - ValueError: Non-string function head ['Times', 'a', 'b', '2', ['Plus', 'p', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 62: SKIPPED - ValueError: Non-string function head ['Times', 'a', '2', ['Plus', 'p', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 63: SKIPPED - ValueError: Non-string function head ['Times', 'a', '2', ['Plus', ['Times', 'b', 'c'], ['Times', '-1', ['Times', 'a', 'd']]], ['Plus', 'p', '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 65: SKIPPED - ValueError: Non-string function head ['Plus', 'm', ['Times', '2', ['Plus', 'p', 'q']], '1'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 66: SKIPPED - ValueError: Non-string function head ['Times', 'b', ['Plus', 'm', ['Times', '2', ['Plus', 'p', 'q']], '1']] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 67: SKIPPED - ValueError: Non-string function head ['Plus', ['Times', 'b', 'c'], ['Times', '-1', ['Times', 'a', 'd']]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 68: SKIPPED - ValueError: Non-string function head ['Plus', ['Times', 'b', 'c'], ['Times', '-1', ['Times', 'a', 'd']]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 69
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*(x**2*_b_ + a_)**p_*(x**2*_d_ + c_)**q_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_, _m_], x), NeQ(-a_*_d_ + _b_*c_, 0), IGtQ(p_, -2), Or(IGtQ(q_, -2), And(EqQ(q_, -3), IntegerQ(_m_/2 + sympy.S(-1)/2))),),
        replacement=Int(ExpandIntegrand((x*_e_)**_m_*(x**2*_b_ + a_)**p_*(x**2*_d_ + c_)**q_, x), x),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=69,
    ),
    # Rule 70: SKIPPED - ValueError: Non-string function head ['Times', '2', 'x', ['Power', ['Power', 'x', '2'], ['Plus', ['Simplify', ['Times', ['Plus', 'm', '1'], ['Power', '2', '-1']]], '-1']]] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.
    # Rule 71
    RubiRulePattern(
        pattern=Int((x*_e_)**_m_*(x**2*_b_ + a_)**p_*(x**2*_d_ + c_)**q_, x),
        constraints=(FreeQ([a_, _b_, c_, _d_, _e_, _m_, p_, q_], x), NeQ(-a_*_d_ + _b_*c_, 0), NeQ(_m_, -1), NeQ(_m_, 1), Or(IntegerQ(p_), GtQ(a_, 0)), Or(IntegerQ(q_), GtQ(c_, 0)),),
        replacement=a_**p_*c_**q_*(x*_e_)**(_m_ + 1)*appellf1(_m_/2 + sympy.S.Half, -p_, -q_, _m_/2 + sympy.S(3)/2, -x**2*_b_/a_, -x**2*_d_/c_)/(_e_*(_m_ + 1)),
        module_name='1.1.2.4 (e x)^m (a+b x^2)^p (c+d x^2)^q',
        rule_number=71,
    ),
    # Rule 72: SKIPPED - ValueError: Non-string function head ['FracPart', 'p'] -- function-head wildcard patterns (e.g., F_[x_]) are not yet supported.

]

# Summary: 24 rules translated, 48 skipped
