# -*- coding: utf-8 -*-
# =============================================================================
# !! AUTO-GENERATED FILE -- DO NOT EDIT !!
#
# Generated by: rubi_rules/codegen/generate.py
# Source: 1.1.3.8 P(x) (c x)^m (a+b x^n)^p.m
# Module: 1.1.3.8 P(x) (c x)^m (a+b x^n)^p
#
# This file contains Rubi integration rules as RubiRulePattern objects.
# Re-run the generator to update.
# =============================================================================
import sympy
from sympy import Integer, Integral, Lambda, Rational, Symbol, Tuple as SympyTuple, Eq, Ne, Lt, Gt, Le, Ge, log, sqrt, pi, I, oo
from rubi_rules.utils.rubi_utils import *  # bare-name access; sympy imports below override any conflicts (e.g. Not)
from sympy.logic.boolalg import Or, Not, And
from sympy import (sin, cos, tan, sec, csc, cot, asin, acos, atan, atan2, asec, acsc, acot,
                   sinh, cosh, tanh, sech, csch, coth, asinh, acosh, atanh, asech, acsch, acoth,
                   exp, Abs, diff, denom, frac, floor, root, simplify,
                   elliptic_e, elliptic_f, hyper, appellf1)

from sympy_objects.wild import WildSymbol, IDENTITY_ELEMENT
from rubi_rules.base_objects import Int, RubiRulePattern
from rubi_rules.utils import (
    # Wolfram standard constraints
    FreeQ, IntegerQ, OddQ, EvenQ, NumberQ, NumericQ, AtomQ, MemberQ,
    PositiveQ, NegativeQ, PolynomialQ, TrueQ, FalseQ, MatchQ, PrimeQ, UnsameQ,
    # RUBI-specific constraints
    EqQ, NeQ, IGtQ, ILtQ, IGeQ, ILeQ, GtQ, LtQ, GeQ, LeQ, PosQ, NegQ,
    IntegersQ, HalfIntegerQ, FractionQ, RationalQ, ComplexNumberQ, RealNumberQ,
    FractionOrNegativeQ, SqrtNumberQ, PowerQ, ProductQ, SumQ, NonsumQ,
    IntegerPowerQ, FractionalPowerQ, PolyQ, LinearQ, QuadraticQ, BinomialQ,
    TrinomialQ, LinearMatchQ, QuadraticMatchQ, BinomialMatchQ, TrinomialMatchQ,
    TrigQ, HyperbolicQ, InverseTrigQ, InverseHyperbolicQ, LogQ, ComplexFreeQ,
    InverseFunctionFreeQ, FractionalPowerFreeQ, TrigHyperbolicFreeQ, IntegralFreeQ,
    RationalFunctionQ, AlgebraicFunctionQ, IndependentQ, SimplerQ, SumSimplerQ,
    FunctionOfQ, PiecewiseLinearQ, ExpressionEqQ,
    IntLinearQ, IntBinomialQ, IntQuadraticQ,
    MonomialQ, LinearPairQ,
    GeneralizedBinomialQ, GeneralizedBinomialMatchQ,
    GeneralizedTrinomialQ, GeneralizedTrinomialMatchQ,
    NiceSqrtQ, SimplerSqrtQ, FractionalPowerFactorQ,
    SumBaseQ, InverseFunctionQ, InertTrigQ, InertTrigFreeQ,
    CalculusFreeQ, QuotientOfLinearsQ,
    PowerOfLinearQ, PowerOfLinearMatchQ,
    FunctionOfExponentialQ,
    KnownSineIntegrandQ, KnownSecantIntegrandQ,
    KnownTangentIntegrandQ, KnownCotangentIntegrandQ,
    EulerIntegrandQ, SubstForFractionalPowerQ,
    PerfectSquareQ, PolynomialInQ, FunctionOfTrigOfLinearQ,
    SimplerIntegrandQ, PseudoBinomialPairQ, QuadraticProductQ,
    EveryQ, TrigSimplifyQ, EqM, TryPureTanSubst,
)

# --- Integration variable ---
x = Symbol('x')

# --- Rubi global option stubs (default False/placeholder) ---
UseGamma = sympy.Symbol('UseGamma')  # Rubi global option; treated as False in Python
u = Symbol('u')  # Generic integrand placeholder used in some Rubi constraint calls

# --- Wildcard symbols ---
# dot wildcards (must match exactly one expression)
# optional wildcards (can match identity element if absent in commutative ops)

P4_ = WildSymbol('P4')
Pq_ = WildSymbol('Pq')
a_ = WildSymbol('a')
a1_ = WildSymbol('a1')
a2_ = WildSymbol('a2')
_b_ = WildSymbol('b', optional_value=IDENTITY_ELEMENT)
b_ = WildSymbol('b')
_b1_ = WildSymbol('b1', optional_value=IDENTITY_ELEMENT)
b1_ = WildSymbol('b1')
_b2_ = WildSymbol('b2', optional_value=IDENTITY_ELEMENT)
b2_ = WildSymbol('b2')
_c_ = WildSymbol('c', optional_value=IDENTITY_ELEMENT)
c_ = WildSymbol('c')
_d_ = WildSymbol('d', optional_value=IDENTITY_ELEMENT)
d_ = WildSymbol('d')
e_ = WildSymbol('e')
_f_ = WildSymbol('f', optional_value=IDENTITY_ELEMENT)
f_ = WildSymbol('f')
_g_ = WildSymbol('g', optional_value=IDENTITY_ELEMENT)
g_ = WildSymbol('g')
_h_ = WildSymbol('h', optional_value=IDENTITY_ELEMENT)
h_ = WildSymbol('h')
_m_ = WildSymbol('m', optional_value=IDENTITY_ELEMENT)
m_ = WildSymbol('m')
_n_ = WildSymbol('n', optional_value=IDENTITY_ELEMENT)
n_ = WildSymbol('n')
_n2_ = WildSymbol('n2', optional_value=IDENTITY_ELEMENT)
n2_ = WildSymbol('n2')
_p_ = WildSymbol('p', optional_value=IDENTITY_ELEMENT)
p_ = WildSymbol('p')
_q_ = WildSymbol('q', optional_value=IDENTITY_ELEMENT)
q_ = WildSymbol('q')
_r_ = WildSymbol('r', optional_value=IDENTITY_ELEMENT)
r_ = WildSymbol('r')
u_ = WildSymbol('u')
v_ = WildSymbol('v')

RULES = [
    # Rule 1
    RubiRulePattern(
        pattern=Int(x**_m_*(x**_n_*_h_ + x**_q_*_f_ + x**_r_*_g_ + e_)/(x**_n_*_c_ + a_)**(sympy.S(3)/2), x),
        constraints=(FreeQ([a_, _c_, e_, _f_, _g_, _h_, _m_, _n_], x), EqQ(_q_, _n_/4), EqQ(_r_, 3*_n_/4), EqQ(4*_m_ - _n_ + 4, 0), EqQ(a_*_h_ + _c_*e_, 0),),
        replacement=(-4*x**(_n_/4)*a_*_h_ + 2*x**(_n_/2)*_c_*_f_ - 2*a_*_g_)/(a_*_c_*_n_*sqrt(x**_n_*_c_ + a_)),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=1,
    ),
    # Rule 2
    RubiRulePattern(
        pattern=Int((x*d_)**_m_*(x**_n_*_h_ + x**_q_*_f_ + x**_r_*_g_ + e_)/(x**_n_*_c_ + a_)**(sympy.S(3)/2), x),
        constraints=(FreeQ([a_, _c_, d_, e_, _f_, _g_, _h_, _m_, _n_], x), EqQ(4*_m_ - _n_ + 4, 0), EqQ(_q_, _n_/4), EqQ(_r_, 3*_n_/4), EqQ(a_*_h_ + _c_*e_, 0),),
        replacement=(x*d_)**_m_*Int(x**_m_*(x**(3*_n_/4)*_g_ + x**(_n_/4)*_f_ + x**_n_*_h_ + e_)/(x**_n_*_c_ + a_)**(sympy.S(3)/2), x)/x**_m_,
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=2,
    ),
    # Rule 3
    RubiRulePattern(
        pattern=Int(Pq_*(x*_c_)**m_*(x*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, m_], x), PolyQ(Pq_, x), FractionQ(p_), ILtQ(m_, -1),),
        replacement=With(List(Set(Symbol('n'), Denominator(p_))), (Symbol('n') * (_b_)**(Integer(-1)) * Subst(Int(((x)**(((Symbol('n') * p_) + Symbol('n') + Integer(-1))) * ((((Integer(-1) * a_) * _c_ * (_b_)**(Integer(-1))) + (_c_ * (x)**(Symbol('n')) * (_b_)**(Integer(-1)))))**(m_) * ReplaceAll(Pq_, Rule(x, (((Integer(-1) * a_) * (_b_)**(Integer(-1))) + ((x)**(Symbol('n')) * (_b_)**(Integer(-1))))))), x), x, ((a_ + (_b_ * x)))**((Symbol('n'))**(Integer(-1)))))),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=3,
    ),
    # Rule 4
    RubiRulePattern(
        pattern=Int(x**_m_*Pq_*(x**n_*_b_ + a_)**_p_, x),
        constraints=(FreeQ([a_, _b_, _m_, n_, _p_], x), NeQ(_m_, -1), IGtQ(Simplify(n_/(_m_ + 1)), 0), PolyQ(Pq_, x**(_m_ + 1)),),
        replacement=Subst(Int((x**Simplify(n_/(_m_ + 1))*_b_ + a_)**_p_*SubstFor(x**(_m_ + 1), Pq_, x), x), x, x**(_m_ + 1))/(_m_ + 1),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=4,
    ),
    # Rule 5
    RubiRulePattern(
        pattern=Int(Pq_*(x*_c_)**_m_*(x**_n_*_b_ + a_)**_p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _m_, _n_], x), PolyQ(Pq_, x), Or(IGtQ(_p_, 0), EqQ(_n_, 1)),),
        replacement=Int(ExpandIntegrand(Pq_*(x*_c_)**_m_*(x**_n_*_b_ + a_)**_p_, x), x),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=5,
    ),
    # Rule 6
    RubiRulePattern(
        pattern=Int(x**_m_*Pq_*(x**n_*_b_ + a_)**_p_, x),
        constraints=(FreeQ([a_, _b_, _m_, n_, _p_], x), PolyQ(Pq_, x**n_), IntegerQ(Simplify((_m_ + 1)/n_)),),
        replacement=Subst(Int(x**(Simplify((_m_ + 1)/n_) - 1)*(x*_b_ + a_)**_p_*SubstFor(x**n_, Pq_, x), x), x, x**n_)/n_,
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=6,
    ),
    # Rule 7
    RubiRulePattern(
        pattern=Int(Pq_*(x*c_)**_m_*(x**n_*_b_ + a_)**_p_, x),
        constraints=(FreeQ([a_, _b_, c_, _m_, n_, _p_], x), PolyQ(Pq_, x**n_), IntegerQ(Simplify((_m_ + 1)/n_)),),
        replacement=c_**IntPart(_m_)*(x*c_)**FracPart(_m_)*Int(x**_m_*Pq_*(x**n_*_b_ + a_)**_p_, x)/x**FracPart(_m_),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=7,
    ),
    # Rule 8
    RubiRulePattern(
        pattern=Int(x**_m_*Pq_*(x**n_*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _m_, n_], x), PolyQ(Pq_, x), EqQ(_m_ - n_ + 1, 0), LtQ(p_, -1),),
        replacement=Pq_*(x**n_*_b_ + a_)**(p_ + 1)/(_b_*n_*(p_ + 1)) - Int((x**n_*_b_ + a_)**(p_ + 1)*D(Pq_, x), x)/(_b_*n_*(p_ + 1)),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=8,
    ),
    # Rule 9
    RubiRulePattern(
        pattern=Int(Pq_*(x*_d_)**_m_*(x**_n_*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _d_, _m_, _n_, p_], x), PolyQ(Pq_, x), EqQ(Coeff(Pq_, x, 0), 0),),
        replacement=Int((x*_d_)**(_m_ + 1)*(x**_n_*_b_ + a_)**p_*PolynomialQuotient(Pq_, x, x), x)/_d_,
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=9,
    ),
    # Rule 10
    RubiRulePattern(
        pattern=Int(x**_m_*Pq_*(x**_n_*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_], x), PolyQ(Pq_, x), IGtQ(_n_, 0), GtQ(p_, 0), LtQ(_m_ + Expon(Pq_, x) + 1, 0),),
        replacement=Module(List(Set(Symbol('u'), IntHide(((x)**(_m_) * Pq_), x))), ((Symbol('u') * ((a_ + (_b_ * (x)**(_n_))))**(p_)) + (Integer(-1) * (_b_ * _n_ * p_ * Int(((x)**((_m_ + _n_)) * ((a_ + (_b_ * (x)**(_n_))))**((p_ + Integer(-1))) * ExpandToSum((Symbol('u') * ((x)**((_m_ + Integer(1))))**(Integer(-1))), x)), x))))),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=10,
    ),
    # Rule 11
    RubiRulePattern(
        pattern=Int(Pq_*(x*_c_)**_m_*(x**_n_*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _m_], x), PolyQ(Pq_, x), IGtQ(_n_/2 + sympy.S(-1)/2, 0), GtQ(p_, 0),),
        replacement=Module(List(Set(Symbol('q'), Expon(Pq_, x)), Symbol('i')), ((((_c_ * x))**(_m_) * ((a_ + (_b_ * (x)**(_n_))))**(p_) * Sum((Coeff(Pq_, x, Symbol('i')) * (x)**((Symbol('i') + Integer(1))) * ((_m_ + (_n_ * p_) + Symbol('i') + Integer(1)))**(Integer(-1))), List(Symbol('i'), Integer(0), Symbol('q')))) + (a_ * _n_ * p_ * Int((((_c_ * x))**(_m_) * ((a_ + (_b_ * (x)**(_n_))))**((p_ + Integer(-1))) * Sum((Coeff(Pq_, x, Symbol('i')) * (x)**(Symbol('i')) * ((_m_ + (_n_ * p_) + Symbol('i') + Integer(1)))**(Integer(-1))), List(Symbol('i'), Integer(0), Symbol('q')))), x)))),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=11,
    ),
    # Rule 12
    RubiRulePattern(
        pattern=Int(x**2*P4_/(x**4*_b_ + a_)**(sympy.S(3)/2), x),
        constraints=(FreeQ([a_, _b_], x), PolyQ(P4_, x, 4), EqQ(Coeff(P4_, x, 2), 0), EqQ(Coeff(P4_, x, 3), 0), EqQ(-3*a_*Coeff(P4_, x, 4) + _b_*Coeff(P4_, x, 0), 0),),
        replacement=With(List(Set(Symbol('e'), Coeff(P4_, x, Integer(0))), Set(Symbol('f'), Coeff(P4_, x, Integer(1))), Set(Symbol('h'), Coeff(P4_, x, Integer(4)))), ((Integer(-1) * (Symbol('f') + (Integer(-1) * (Integer(2) * Symbol('h') * (x)**(Integer(3)))))) * ((Integer(2) * _b_ * sympy.sqrt((a_ + (_b_ * (x)**(Integer(4)))))))**(Integer(-1)))),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=12,
    ),
    # Rule 13
    RubiRulePattern(
        pattern=Int(x**_m_*Pq_*(x**_n_*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_], x), PolyQ(Pq_, x), IGtQ(_n_, 0), LtQ(p_, -1), IGtQ(_m_, 0), GeQ(_m_ + Expon(Pq_, x), _n_),),
        replacement=With(List(Set(Symbol('q'), (_m_ + Expon(Pq_, x)))), Module(List(Set(Symbol('Q'), PolynomialQuotient(((_b_)**((Floor(((Symbol('q') + Integer(-1)) * (_n_)**(Integer(-1)))) + Integer(1))) * (x)**(_m_) * Pq_), (a_ + (_b_ * (x)**(_n_))), x)), Set(Symbol('R'), PolynomialRemainder(((_b_)**((Floor(((Symbol('q') + Integer(-1)) * (_n_)**(Integer(-1)))) + Integer(1))) * (x)**(_m_) * Pq_), (a_ + (_b_ * (x)**(_n_))), x))), (((Integer(-1) * x) * Symbol('R') * ((a_ + (_b_ * (x)**(_n_))))**((p_ + Integer(1))) * ((a_ * _n_ * (p_ + Integer(1)) * (_b_)**((Floor(((Symbol('q') + Integer(-1)) * (_n_)**(Integer(-1)))) + Integer(1)))))**(Integer(-1))) + (((a_ * _n_ * (p_ + Integer(1)) * (_b_)**((Floor(((Symbol('q') + Integer(-1)) * (_n_)**(Integer(-1)))) + Integer(1)))))**(Integer(-1)) * Int((((a_ + (_b_ * (x)**(_n_))))**((p_ + Integer(1))) * ExpandToSum(((a_ * _n_ * (p_ + Integer(1)) * Symbol('Q')) + (_n_ * (p_ + Integer(1)) * Symbol('R')) + D((x * Symbol('R')), x)), x)), x))))),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=13,
    ),
    # Rule 14
    RubiRulePattern(
        pattern=Int(x**m_*Pq_*(x**_n_*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_], x), PolyQ(Pq_, x), IGtQ(_n_, 0), LtQ(p_, -1), ILtQ(m_, 0),),
        replacement=With(List(Set(Symbol('q'), Expon(Pq_, x))), Module(List(Set(Symbol('Q'), PolynomialQuotient((a_ * (_b_)**((Floor(((Symbol('q') + Integer(-1)) * (_n_)**(Integer(-1)))) + Integer(1))) * (x)**(m_) * Pq_), (a_ + (_b_ * (x)**(_n_))), x)), Set(Symbol('R'), PolynomialRemainder((a_ * (_b_)**((Floor(((Symbol('q') + Integer(-1)) * (_n_)**(Integer(-1)))) + Integer(1))) * (x)**(m_) * Pq_), (a_ + (_b_ * (x)**(_n_))), x)), Symbol('i')), (((Integer(-1) * x) * Symbol('R') * ((a_ + (_b_ * (x)**(_n_))))**((p_ + Integer(1))) * (((a_)**(Integer(2)) * _n_ * (p_ + Integer(1)) * (_b_)**((Floor(((Symbol('q') + Integer(-1)) * (_n_)**(Integer(-1)))) + Integer(1)))))**(Integer(-1))) + (((a_ * _n_ * (p_ + Integer(1)) * (_b_)**((Floor(((Symbol('q') + Integer(-1)) * (_n_)**(Integer(-1)))) + Integer(1)))))**(Integer(-1)) * Int(((x)**(m_) * ((a_ + (_b_ * (x)**(_n_))))**((p_ + Integer(1))) * ExpandToSum(((_n_ * (p_ + Integer(1)) * (x)**((Integer(-1) * m_)) * Symbol('Q')) + Sum((((_n_ * (p_ + Integer(1))) + Symbol('i') + Integer(1)) * (a_)**(Integer(-1)) * Coeff(Symbol('R'), x, Symbol('i')) * (x)**((Symbol('i') + (Integer(-1) * m_)))), List(Symbol('i'), Integer(0), (_n_ + Integer(-1))))), x)), x))))),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=14,
    ),
    # Rule 15
    RubiRulePattern(
        pattern=Int(x**_m_*Pq_*(x**n_*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, p_], x), PolyQ(Pq_, x**n_), IGtQ(n_, 0), IntegerQ(_m_), sympy.Ne(GCD((_m_ + Integer(1)), n_), Integer(1)),),
        replacement=With(List(Set(Symbol('g'), GCD((_m_ + Integer(1)), n_))), ((Symbol('g'))**(Integer(-1)) * Subst(Int(((x)**((((_m_ + Integer(1)) * (Symbol('g'))**(Integer(-1))) + Integer(-1))) * ReplaceAll(Pq_, Rule(x, (x)**((Symbol('g'))**(Integer(-1))))) * ((a_ + (_b_ * (x)**((n_ * (Symbol('g'))**(Integer(-1)))))))**(p_)), x), x, (x)**(Symbol('g'))))),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=15,
    ),
    # Rule 16
    RubiRulePattern(
        pattern=Int(Pq_*(x*_c_)**_m_/(x**n_*_b_ + a_), x),
        constraints=(FreeQ([a_, _b_, _c_, _m_], x), PolyQ(Pq_, x), IGtQ(n_/2, 0), Expon(Pq_, x) < n_, SumQ(Sum((((_c_ * x))**((_m_ + Symbol('ii'))) * (Coeff(Pq_, x, Symbol('ii')) + (Coeff(Pq_, x, ((n_ * (Integer(2))**(Integer(-1))) + Symbol('ii'))) * (x)**((n_ * (Integer(2))**(Integer(-1)))))) * (((_c_)**(Symbol('ii')) * (a_ + (_b_ * (x)**(n_)))))**(Integer(-1))), [Symbol('ii'), Integer(0), ((n_ * (Integer(2))**(Integer(-1))) + Integer(-1))])),),
        replacement=With(List(Set(Symbol('v'), Sum((((_c_ * x))**((_m_ + Symbol('ii'))) * (Coeff(Pq_, x, Symbol('ii')) + (Coeff(Pq_, x, ((n_ * (Integer(2))**(Integer(-1))) + Symbol('ii'))) * (x)**((n_ * (Integer(2))**(Integer(-1)))))) * (((_c_)**(Symbol('ii')) * (a_ + (_b_ * (x)**(n_)))))**(Integer(-1))), List(Symbol('ii'), Integer(0), ((n_ * (Integer(2))**(Integer(-1))) + Integer(-1)))))), Int(Symbol('v'), x)),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=16,
    ),
    # Rule 17
    RubiRulePattern(
        pattern=Int(Pq_/(x*sqrt(x**n_*_b_ + a_)), x),
        constraints=(FreeQ([a_, _b_], x), PolyQ(Pq_, x), IGtQ(n_, 0), NeQ(Coeff(Pq_, x, 0), 0),),
        replacement=Coeff(Pq_, x, 0)*Int(1/(x*sqrt(x**n_*_b_ + a_)), x) + Int(ExpandToSum((Pq_ - Coeff(Pq_, x, 0))/x, x)/sqrt(x**n_*_b_ + a_), x),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=17,
    ),
    # Rule 18
    RubiRulePattern(
        pattern=Int(Pq_*(x*_c_)**_m_*(x**n_*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _m_, p_], x), PolyQ(Pq_, x), IGtQ(n_/2, 0), Not(PolyQ(Pq_, x**(n_/2))),),
        replacement=Module(List(Set(Symbol('q'), Expon(Pq_, x)), Symbol('j'), Symbol('k')), Int(Sum((((_c_ * x))**((_m_ + Symbol('j'))) * ((_c_)**(Symbol('j')))**(Integer(-1)) * Sum((Coeff(Pq_, x, (Symbol('j') + (Symbol('k') * n_ * (Integer(2))**(Integer(-1))))) * (x)**((Symbol('k') * n_ * (Integer(2))**(Integer(-1))))), List(Symbol('k'), Integer(0), ((Integer(2) * (Symbol('q') + (Integer(-1) * Symbol('j'))) * (n_)**(Integer(-1))) + Integer(1)))) * ((a_ + (_b_ * (x)**(n_))))**(p_)), List(Symbol('j'), Integer(0), ((n_ * (Integer(2))**(Integer(-1))) + Integer(-1)))), x)),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=18,
    ),
    # Rule 19
    RubiRulePattern(
        pattern=Int(Pq_*(x*_c_)**_m_/(x**n_*_b_ + a_), x),
        constraints=(FreeQ([a_, _b_, _c_, _m_], x), PolyQ(Pq_, x), IntegerQ(n_), Not(IGtQ(_m_, 0)),),
        replacement=Int(ExpandIntegrand(Pq_*(x*_c_)**_m_/(x**n_*_b_ + a_), x), x),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=19,
    ),
    # Rule 20
    RubiRulePattern(
        pattern=Int(Pq_*(x*_c_)**m_*(x**n_*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, p_], x), PolyQ(Pq_, x), IGtQ(n_, 0), LtQ(m_, -1), LeQ(n_ - 1, Expon(Pq_, x)), NeQ(Coeff(Pq_, x, 0), 0),),
        replacement=With(List(Set(Symbol('Pq0'), Coeff(Pq_, x, Integer(0)))), ((Symbol('Pq0') * ((_c_ * x))**((m_ + Integer(1))) * ((a_ + (_b_ * (x)**(n_))))**((p_ + Integer(1))) * ((a_ * _c_ * (m_ + Integer(1))))**(Integer(-1))) + (((Integer(2) * a_ * _c_ * (m_ + Integer(1))))**(Integer(-1)) * Int((((_c_ * x))**((m_ + Integer(1))) * ExpandToSum(((Integer(2) * a_ * (m_ + Integer(1)) * (Pq_ + (Integer(-1) * Symbol('Pq0'))) * (x)**(Integer(-1))) + (Integer(-1) * (Integer(2) * _b_ * Symbol('Pq0') * (m_ + (n_ * (p_ + Integer(1))) + Integer(1)) * (x)**((n_ + Integer(-1)))))), x) * ((a_ + (_b_ * (x)**(n_))))**(p_)), x)))),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=20,
    ),
    # Rule 21
    RubiRulePattern(
        pattern=Int(Pq_*(x*_c_)**_m_*(x**n_*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _m_, p_], x), PolyQ(Pq_, x), IGtQ(n_, 0), NeQ(_m_ + n_*p_ + Expon(Pq_, x) + 1, 0), -n_ + Expon(Pq_, x) >= 0, Or(IntegerQ(2*p_), IntegerQ(p_ + (Expon(Pq_, x) + 1)/(2*n_))),),
        replacement=With(List(Set(Symbol('q'), Expon(Pq_, x))), With(List(Set(Symbol('Pqq'), Coeff(Pq_, x, Symbol('q')))), ((Symbol('Pqq') * ((_c_ * x))**((_m_ + Symbol('q') + (Integer(-1) * n_) + Integer(1))) * ((a_ + (_b_ * (x)**(n_))))**((p_ + Integer(1))) * ((_b_ * (_c_)**((Symbol('q') + (Integer(-1) * n_) + Integer(1))) * (_m_ + Symbol('q') + (n_ * p_) + Integer(1))))**(Integer(-1))) + (((_b_ * (_m_ + Symbol('q') + (n_ * p_) + Integer(1))))**(Integer(-1)) * Int((((_c_ * x))**(_m_) * ExpandToSum(((_b_ * (_m_ + Symbol('q') + (n_ * p_) + Integer(1)) * (Pq_ + (Integer(-1) * (Symbol('Pqq') * (x)**(Symbol('q')))))) + (Integer(-1) * (a_ * Symbol('Pqq') * (_m_ + Symbol('q') + (Integer(-1) * n_) + Integer(1)) * (x)**((Symbol('q') + (Integer(-1) * n_)))))), x) * ((a_ + (_b_ * (x)**(n_))))**(p_)), x))))),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=21,
    ),
    # Rule 22
    RubiRulePattern(
        pattern=Int(x**_m_*Pq_*(x**n_*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, p_], x), PolyQ(Pq_, x), ILtQ(n_, 0), IntegerQ(_m_),),
        replacement=With(List(Set(Symbol('q'), Expon(Pq_, x))), (Integer(-1) * Subst(Int((ExpandToSum(((x)**(Symbol('q')) * ReplaceAll(Pq_, Rule(x, (x)**(Integer(-1))))), x) * ((a_ + (_b_ * (x)**((Integer(-1) * n_)))))**(p_) * ((x)**((_m_ + Symbol('q') + Integer(2))))**(Integer(-1))), x), x, (x)**(Integer(-1))))),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=22,
    ),
    # Rule 23
    RubiRulePattern(
        pattern=Int(Pq_*(x*_c_)**_m_*(x**n_*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, p_], x), PolyQ(Pq_, x), ILtQ(n_, 0), FractionQ(_m_),),
        replacement=With(List(Set(Symbol('g'), Denominator(_m_)), Set(Symbol('q'), Expon(Pq_, x))), ((Integer(-1) * Symbol('g')) * (_c_)**(Integer(-1)) * Subst(Int((ExpandToSum(((x)**((Symbol('g') * Symbol('q'))) * ReplaceAll(Pq_, Rule(x, ((_c_)**(Integer(-1)) * (x)**((Integer(-1) * Symbol('g'))))))), x) * ((a_ + (_b_ * (_c_)**((Integer(-1) * n_)) * (x)**(((Integer(-1) * Symbol('g')) * n_)))))**(p_) * ((x)**(((Symbol('g') * (_m_ + Symbol('q') + Integer(1))) + Integer(1))))**(Integer(-1))), x), x, (((_c_ * x))**((Symbol('g'))**(Integer(-1))))**(Integer(-1))))),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=23,
    ),
    # Rule 24
    RubiRulePattern(
        pattern=Int(Pq_*(x*_c_)**m_*(x**n_*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _c_, m_, p_], x), PolyQ(Pq_, x), ILtQ(n_, 0), Not(RationalQ(m_)),),
        replacement=With(List(Set(Symbol('q'), Expon(Pq_, x))), ((Integer(-1) * ((_c_ * x))**(m_)) * ((x)**(Integer(-1)))**(m_) * Subst(Int((ExpandToSum(((x)**(Symbol('q')) * ReplaceAll(Pq_, Rule(x, (x)**(Integer(-1))))), x) * ((a_ + (_b_ * (x)**((Integer(-1) * n_)))))**(p_) * ((x)**((m_ + Symbol('q') + Integer(2))))**(Integer(-1))), x), x, (x)**(Integer(-1))))),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=24,
    ),
    # Rule 25
    RubiRulePattern(
        pattern=Int(x**_m_*Pq_*(x**n_*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _m_, p_], x), PolyQ(Pq_, x), FractionQ(n_),),
        replacement=With(List(Set(Symbol('g'), Denominator(n_))), (Symbol('g') * Subst(Int(((x)**(((Symbol('g') * (_m_ + Integer(1))) + Integer(-1))) * ReplaceAll(Pq_, Rule(x, (x)**(Symbol('g')))) * ((a_ + (_b_ * (x)**((Symbol('g') * n_)))))**(p_)), x), x, (x)**((Symbol('g'))**(Integer(-1)))))),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=25,
    ),
    # Rule 26
    RubiRulePattern(
        pattern=Int(Pq_*(x*c_)**m_*(x**n_*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, c_, m_, p_], x), PolyQ(Pq_, x), FractionQ(n_),),
        replacement=c_**IntPart(m_)*(x*c_)**FracPart(m_)*Int(x**m_*Pq_*(x**n_*_b_ + a_)**p_, x)/x**FracPart(m_),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=26,
    ),
    # Rule 27
    RubiRulePattern(
        pattern=Int(x**_m_*Pq_*(x**n_*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, _m_, n_, p_], x), PolyQ(Pq_, x**n_), IntegerQ(Simplify(n_/(_m_ + 1))), Not(IntegerQ(n_)),),
        replacement=Subst(Int((x**Simplify(n_/(_m_ + 1))*_b_ + a_)**p_*ReplaceAll(SubstFor(x**n_, Pq_, x), Rule(x, x**Simplify(n_/(_m_ + 1)))), x), x, x**(_m_ + 1))/(_m_ + 1),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=27,
    ),
    # Rule 28
    RubiRulePattern(
        pattern=Int(Pq_*(x*c_)**m_*(x**n_*_b_ + a_)**p_, x),
        constraints=(FreeQ([a_, _b_, c_, m_, n_, p_], x), PolyQ(Pq_, x**n_), IntegerQ(Simplify(n_/(m_ + 1))), Not(IntegerQ(n_)),),
        replacement=c_**IntPart(m_)*(x*c_)**FracPart(m_)*Int(x**m_*Pq_*(x**n_*_b_ + a_)**p_, x)/x**FracPart(m_),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=28,
    ),
    # Rule 29
    RubiRulePattern(
        pattern=Int(Pq_*(x*_c_)**_m_*(x**n_*_b_ + a_)**_p_, x),
        constraints=(FreeQ([a_, _b_, _c_, _m_, n_, _p_], x), Or(PolyQ(Pq_, x), PolyQ(Pq_, x**n_)), Not(IGtQ(_m_, 0)),),
        replacement=Int(ExpandIntegrand(Pq_*(x*_c_)**_m_*(x**n_*_b_ + a_)**_p_, x), x),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=29,
    ),
    # Rule 30
    RubiRulePattern(
        pattern=Int(Pq_*u_**_m_*(a_ + _b_*v_**_n_)**p_, x),
        constraints=(FreeQ([a_, _b_, _m_, _n_, p_], x), LinearPairQ(u_, v_, x), PolyQ(Pq_, v_**_n_),),
        replacement=u_**_m_*Subst(Int(x**_m_*(x**_n_*_b_ + a_)**p_*SubstFor(v_, Pq_, x), x), x, v_)/(v_**_m_*Coeff(v_, x, 1)),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=30,
    ),
    # Rule 31
    RubiRulePattern(
        pattern=Int(Pq_*(x*_c_)**_m_*(x**_n_*_b1_ + a1_)**_p_*(x**_n_*_b2_ + a2_)**_p_, x),
        constraints=(FreeQ([a1_, _b1_, a2_, _b2_, _c_, _m_, _n_, _p_], x), PolyQ(Pq_, x), EqQ(a1_*_b2_ + a2_*_b1_, 0), Or(IntegerQ(_p_), And(GtQ(a1_, 0), GtQ(a2_, 0))),),
        replacement=Int(Pq_*(x*_c_)**_m_*(x**(2*_n_)*_b1_*_b2_ + a1_*a2_)**_p_, x),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=31,
    ),
    # Rule 32
    RubiRulePattern(
        pattern=Int(Pq_*(x*_c_)**_m_*(x**_n_*_b1_ + a1_)**_p_*(x**_n_*_b2_ + a2_)**_p_, x),
        constraints=(FreeQ([a1_, _b1_, a2_, _b2_, _c_, _m_, _n_, _p_], x), PolyQ(Pq_, x), EqQ(a1_*_b2_ + a2_*_b1_, 0), Not(And(EqQ(_n_, 1), LinearQ(Pq_, x))),),
        replacement=(x**_n_*_b1_ + a1_)**FracPart(_p_)*(x**_n_*_b2_ + a2_)**FracPart(_p_)*Int(Pq_*(x*_c_)**_m_*(x**(2*_n_)*_b1_*_b2_ + a1_*a2_)**_p_, x)/(x**(2*_n_)*_b1_*_b2_ + a1_*a2_)**FracPart(_p_),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=32,
    ),
    # Rule 33
    RubiRulePattern(
        pattern=Int((x*_h_)**_m_*(x**_n_*_b_ + a_)**_p_*(x**_n_*_d_ + c_)**_p_*(x**_n_*_f_ + x**_n2_*_g_ + e_), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, e_, _f_, _g_, _h_, _m_, _n_, _p_], x), EqQ(_n2_, 2*_n_), EqQ(a_*c_*_f_*(_m_ + 1) - e_*(a_*_d_ + _b_*c_)*(_m_ + _n_*(_p_ + 1) + 1), 0), EqQ(a_*c_*_g_*(_m_ + 1) - _b_*_d_*e_*(_m_ + 2*_n_*(_p_ + 1) + 1), 0), NeQ(_m_, -1),),
        replacement=e_*(x*_h_)**(_m_ + 1)*(x**_n_*_b_ + a_)**(_p_ + 1)*(x**_n_*_d_ + c_)**(_p_ + 1)/(a_*c_*_h_*(_m_ + 1)),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=33,
    ),
    # Rule 34
    RubiRulePattern(
        pattern=Int((x*_h_)**_m_*(x**_n_*_b_ + a_)**_p_*(x**_n_*_d_ + c_)**_p_*(x**_n2_*_g_ + e_), x),
        constraints=(FreeQ([a_, _b_, c_, _d_, e_, _g_, _h_, _m_, _n_, _p_], x), EqQ(_n2_, 2*_n_), EqQ(_m_ + _n_*(_p_ + 1) + 1, 0), EqQ(a_*c_*_g_*(_m_ + 1) - _b_*_d_*e_*(_m_ + 2*_n_*(_p_ + 1) + 1), 0), NeQ(_m_, -1),),
        replacement=e_*(x*_h_)**(_m_ + 1)*(x**_n_*_b_ + a_)**(_p_ + 1)*(x**_n_*_d_ + c_)**(_p_ + 1)/(a_*c_*_h_*(_m_ + 1)),
        module_name='1.1.3.8 P(x) (c x)^m (a+b x^n)^p',
        rule_number=34,
    ),

]

# Summary: 34 rules translated, 0 skipped
